package goradius

// HuaweiVendorDefinition defines the Huawei vendor (ID 2011) used by Huawei
// NE/ME BRAS, AR routers, and AC/AP WLAN controllers. Ported from FreeRADIUS
// dictionary.huawei, reconciled between the 3.2.x and master revisions:
// master's additions (user-group-name 251, user-service-type 252) and type
// corrections (nat-port-forwarding string, acct-terminate-subcause integer)
// are applied. Source: Huawei "Description of RADIUS Attributes"
// (support.huawei.com EDOC1100279002 / EDOC1100055480).
//
// No official per-packet placement table is machine-readable, so all
// attributes stay unrestricted. IDs 192/193 carry the DHCPv6 lease structure
// (T1, T2, preferred-lifetime, valid-lifetime) as raw octets; ID 187 carries
// raw DHCP option bytes.
var HuaweiVendorDefinition = &VendorDefinition{
	ID:   2011,
	Name: "huawei",
	Attributes: []*AttributeDefinition{
		{ID: 1, Name: "huawei-input-burst-size", DataType: DataTypeInteger},
		{ID: 2, Name: "huawei-input-average-rate", DataType: DataTypeInteger},
		{ID: 3, Name: "huawei-input-peak-rate", DataType: DataTypeInteger},
		{ID: 4, Name: "huawei-output-burst-size", DataType: DataTypeInteger},
		{ID: 5, Name: "huawei-output-average-rate", DataType: DataTypeInteger},
		{ID: 6, Name: "huawei-output-peak-rate", DataType: DataTypeInteger},
		{ID: 7, Name: "huawei-in-kb-before-t-switch", DataType: DataTypeInteger},
		{ID: 8, Name: "huawei-out-kb-before-t-switch", DataType: DataTypeInteger},
		{ID: 9, Name: "huawei-in-pkt-before-t-switch", DataType: DataTypeInteger},
		{ID: 10, Name: "huawei-out-pkt-before-t-switch", DataType: DataTypeInteger},
		{ID: 11, Name: "huawei-in-kb-after-t-switch", DataType: DataTypeInteger},
		{ID: 12, Name: "huawei-out-kb-after-t-switch", DataType: DataTypeInteger},
		{ID: 13, Name: "huawei-in-pkt-after-t-switch", DataType: DataTypeInteger},
		{ID: 14, Name: "huawei-out-pkt-after-t-switch", DataType: DataTypeInteger},
		{ID: 15, Name: "huawei-remanent-volume", DataType: DataTypeInteger},
		{ID: 16, Name: "huawei-tariff-switch-interval", DataType: DataTypeInteger},
		{ID: 17, Name: "huawei-isp-id", DataType: DataTypeString},
		{ID: 18, Name: "huawei-max-users-per-logic-port", DataType: DataTypeInteger},
		{ID: 20, Name: "huawei-command", DataType: DataTypeInteger},
		{ID: 22, Name: "huawei-priority", DataType: DataTypeInteger},
		{ID: 24, Name: "huawei-control-identifier", DataType: DataTypeInteger},
		{
			ID:       25,
			Name:     "huawei-result-code",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"succeeded": 0,
			},
		},
		{ID: 26, Name: "huawei-connect-id", DataType: DataTypeInteger},
		{ID: 27, Name: "huawei-portalurl", DataType: DataTypeString},
		{ID: 28, Name: "huawei-ftp-directory", DataType: DataTypeString},
		{ID: 29, Name: "huawei-exec-privilege", DataType: DataTypeInteger},
		{ID: 30, Name: "huawei-ip-address", DataType: DataTypeInteger},
		{ID: 31, Name: "huawei-qos-profile-name", DataType: DataTypeString},
		{ID: 32, Name: "huawei-sip-server", DataType: DataTypeString},
		{ID: 33, Name: "huawei-user-password", DataType: DataTypeString},
		{ID: 34, Name: "huawei-command-mode", DataType: DataTypeString},
		{ID: 35, Name: "huawei-renewal-time", DataType: DataTypeInteger},
		{ID: 36, Name: "huawei-rebinding-time", DataType: DataTypeInteger},
		{ID: 37, Name: "huawei-igmp-enable", DataType: DataTypeInteger},
		{ID: 39, Name: "huawei-destnation-ip-addr", DataType: DataTypeString},
		{ID: 40, Name: "huawei-destnation-volume", DataType: DataTypeString},
		{ID: 59, Name: "huawei-startup-stamp", DataType: DataTypeInteger},
		{ID: 60, Name: "huawei-iphost-addr", DataType: DataTypeString},
		{ID: 61, Name: "huawei-up-priority", DataType: DataTypeInteger},
		{ID: 62, Name: "huawei-down-priority", DataType: DataTypeInteger},
		{ID: 63, Name: "huawei-tunnel-vpn-instance", DataType: DataTypeString},
		{ID: 64, Name: "huawei-vt-name", DataType: DataTypeInteger},
		{ID: 65, Name: "huawei-user-date", DataType: DataTypeString},
		{ID: 66, Name: "huawei-user-class", DataType: DataTypeString},
		{ID: 70, Name: "huawei-ppp-ncp-type", DataType: DataTypeInteger},
		{ID: 71, Name: "huawei-vsi-name", DataType: DataTypeString},
		{ID: 72, Name: "huawei-subnet-mask", DataType: DataTypeIPAddr},
		{ID: 73, Name: "huawei-gateway-address", DataType: DataTypeIPAddr},
		{ID: 74, Name: "huawei-lease-time", DataType: DataTypeInteger},
		{ID: 75, Name: "huawei-primary-wins", DataType: DataTypeIPAddr},
		{ID: 76, Name: "huawei-secondary-wins", DataType: DataTypeIPAddr},
		{ID: 77, Name: "huawei-input-peak-burst-size", DataType: DataTypeInteger},
		{ID: 78, Name: "huawei-output-peak-burst-size", DataType: DataTypeInteger},
		{ID: 79, Name: "huawei-reduced-cir", DataType: DataTypeInteger},
		{ID: 80, Name: "huawei-tunnel-session-limit", DataType: DataTypeInteger},
		{ID: 81, Name: "huawei-zone-name", DataType: DataTypeString},
		{ID: 82, Name: "huawei-data-filter", DataType: DataTypeString},
		{ID: 83, Name: "huawei-access-service", DataType: DataTypeString},
		{ID: 84, Name: "huawei-accounting-level", DataType: DataTypeInteger},
		{
			ID:       85,
			Name:     "huawei-portal-mode",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"padm":          0,
				"redirectional": 1,
				"non-captive":   2,
			},
		},
		{ID: 86, Name: "huawei-dpi-policy-name", DataType: DataTypeString},
		{ID: 87, Name: "huawei-policy-route", DataType: DataTypeIPAddr},
		{ID: 88, Name: "huawei-framed-pool", DataType: DataTypeString},
		{ID: 89, Name: "huawei-l2tp-terminate-cause", DataType: DataTypeString},
		{ID: 90, Name: "huawei-multi-account-mode", DataType: DataTypeInteger},
		{ID: 91, Name: "huawei-queue-profile", DataType: DataTypeString},
		{ID: 92, Name: "huawei-layer4-session-limit", DataType: DataTypeInteger},
		{ID: 93, Name: "huawei-multicast-profile", DataType: DataTypeString},
		{ID: 94, Name: "huawei-vpn-instance", DataType: DataTypeString},
		{ID: 95, Name: "huawei-policy-name", DataType: DataTypeString},
		{ID: 96, Name: "huawei-tunnel-group-name", DataType: DataTypeString},
		{ID: 97, Name: "huawei-multicast-source-group", DataType: DataTypeString},
		{ID: 98, Name: "huawei-multicast-receive-group", DataType: DataTypeIPAddr},
		{ID: 99, Name: "huawei-user-multicast-type", DataType: DataTypeInteger},
		{ID: 100, Name: "huawei-reduced-pir", DataType: DataTypeInteger},
		{ID: 101, Name: "huawei-li-id", DataType: DataTypeString},
		{ID: 102, Name: "huawei-li-md-address", DataType: DataTypeIPAddr},
		{ID: 103, Name: "huawei-li-md-port", DataType: DataTypeInteger},
		{ID: 104, Name: "huawei-li-md-vpninstance", DataType: DataTypeString},
		{ID: 105, Name: "huawei-service-chg-cmd", DataType: DataTypeInteger},
		{ID: 106, Name: "huawei-acct-packet-type", DataType: DataTypeInteger},
		{ID: 107, Name: "huawei-call-reference", DataType: DataTypeInteger},
		{ID: 108, Name: "huawei-pstn-port", DataType: DataTypeInteger},
		{ID: 109, Name: "huawei-voip-service-type", DataType: DataTypeInteger},
		{ID: 110, Name: "huawei-acct-connection-time", DataType: DataTypeInteger},
		{ID: 112, Name: "huawei-error-reason", DataType: DataTypeInteger},
		{ID: 113, Name: "huawei-remain-monney", DataType: DataTypeInteger},
		{ID: 123, Name: "huawei-org-gk-ipaddr", DataType: DataTypeIPAddr},
		{ID: 124, Name: "huawei-org-gw-ipaddr", DataType: DataTypeIPAddr},
		{ID: 125, Name: "huawei-dst-gk-ipaddr", DataType: DataTypeIPAddr},
		{ID: 126, Name: "huawei-dst-gw-ipaddr", DataType: DataTypeIPAddr},
		{ID: 127, Name: "huawei-access-num", DataType: DataTypeString},
		{ID: 128, Name: "huawei-remain-time", DataType: DataTypeInteger},
		{ID: 131, Name: "huawei-codec-type", DataType: DataTypeInteger},
		{ID: 132, Name: "huawei-transfer-num", DataType: DataTypeString},
		{ID: 133, Name: "huawei-new-user-name", DataType: DataTypeString},
		{ID: 134, Name: "huawei-transfer-station-id", DataType: DataTypeString},
		{ID: 135, Name: "huawei-primary-dns", DataType: DataTypeIPAddr},
		{ID: 136, Name: "huawei-secondary-dns", DataType: DataTypeIPAddr},
		{ID: 137, Name: "huawei-only-account-type", DataType: DataTypeInteger},
		{ID: 138, Name: "huawei-domain-name", DataType: DataTypeString},
		{ID: 139, Name: "huawei-ancp-profile", DataType: DataTypeString},
		{ID: 140, Name: "huawei-http-redirect-url", DataType: DataTypeString},
		{ID: 141, Name: "huawei-loopback-address", DataType: DataTypeString},
		{
			ID:       142,
			Name:     "huawei-qos-profile-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"original":      0,
				"l2tp-inbound":  1,
				"l2tp-outbound": 2,
				"l2tp":          3,
			},
		},
		{ID: 143, Name: "huawei-max-list-num", DataType: DataTypeInteger},
		{ID: 144, Name: "huawei-acct-ipv6-input-octets", DataType: DataTypeInteger},
		{ID: 145, Name: "huawei-acct-ipv6-output-octets", DataType: DataTypeInteger},
		{ID: 146, Name: "huawei-acct-ipv6-input-packets", DataType: DataTypeInteger},
		{ID: 147, Name: "huawei-acct-ipv6-output-packets", DataType: DataTypeInteger},
		{ID: 148, Name: "huawei-acct-ipv6-input-gigawords", DataType: DataTypeInteger},
		{ID: 149, Name: "huawei-acct-ipv6-output-gigawords", DataType: DataTypeInteger},
		{ID: 150, Name: "huawei-dhcpv6-option37", DataType: DataTypeString},
		{ID: 151, Name: "huawei-dhcpv6-option38", DataType: DataTypeString},
		{ID: 153, Name: "huawei-user-mac", DataType: DataTypeString},
		{ID: 154, Name: "huawei-dns-server-ipv6-address", DataType: DataTypeIPv6Addr},
		{ID: 155, Name: "huawei-dhcpv4-option121", DataType: DataTypeString},
		{ID: 156, Name: "huawei-dhcpv4-option43", DataType: DataTypeString},
		{ID: 157, Name: "huawei-framed-pool-group", DataType: DataTypeString},
		{ID: 158, Name: "huawei-framed-ipv6-address", DataType: DataTypeIPv6Addr},
		{ID: 159, Name: "huawei-acct-update-address", DataType: DataTypeInteger},
		{ID: 160, Name: "huawei-nat-policy-name", DataType: DataTypeString},
		{ID: 161, Name: "huawei-nat-public-address", DataType: DataTypeIPAddr},
		{ID: 162, Name: "huawei-nat-start-port", DataType: DataTypeInteger},
		{ID: 163, Name: "huawei-nat-end-port", DataType: DataTypeInteger},
		// master corrects this from integer to string.
		{ID: 164, Name: "huawei-nat-port-forwarding", DataType: DataTypeString},
		{ID: 165, Name: "huawei-nat-port-range-update", DataType: DataTypeInteger},
		{ID: 166, Name: "huawei-ds-lite-tunnel-name", DataType: DataTypeString},
		{ID: 167, Name: "huawei-pcp-server-name", DataType: DataTypeString},
		{
			ID:       168,
			Name:     "huawei-public-ip-addr-state",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"safe":    0,
				"warning": 1,
				"danger":  2,
			},
		},
		{
			ID:       180,
			Name:     "huawei-auth-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ppp":            1,
				"web":            2,
				"dot1x":          3,
				"fast":           4,
				"bind":           5,
				"wlan":           6,
				"administrative": 7,
				"tunnel":         8,
				"mip":            9,
				"none":           10,
			},
		},
		// master corrects this from string to integer.
		{ID: 181, Name: "huawei-acct-terminate-subcause", DataType: DataTypeInteger},
		{ID: 182, Name: "huawei-down-qos-profile-name", DataType: DataTypeString},
		{
			ID:       183,
			Name:     "huawei-port-mirror",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disable":         0,
				"uplink-enable":   1,
				"downlink-enable": 2,
				"enable":          3,
			},
		},
		{ID: 184, Name: "huawei-account-info", DataType: DataTypeString},
		{ID: 185, Name: "huawei-service-info", DataType: DataTypeString},
		{ID: 187, Name: "huawei-dhcp-option", DataType: DataTypeOctets},
		{ID: 188, Name: "huawei-avpair", DataType: DataTypeString},
		{ID: 191, Name: "huawei-delegated-ipv6-prefix-pool", DataType: DataTypeString},
		// 192/193 carry the DHCPv6 lease struct (T1 byte, T2 byte,
		// preferred-lifetime uint32, valid-lifetime uint32) as raw octets.
		{ID: 192, Name: "huawei-ipv6-prefix-lease", DataType: DataTypeOctets},
		{ID: 193, Name: "huawei-ipv6-address-lease", DataType: DataTypeOctets},
		// FreeRADIUS 3.2.x and master disagree (ipv6prefix vs ipv6addr); master's
		// ipv6addr is used.
		{ID: 194, Name: "huawei-ipv6-policy-route", DataType: DataTypeIPv6Addr},
		{
			ID:       196,
			Name:     "huawei-mng-ipv6",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"unsupported": 0,
				"supported":   1,
			},
		},
		{ID: 206, Name: "huawei-dpsk-info", DataType: DataTypeString},
		{ID: 211, Name: "huawei-flow-info", DataType: DataTypeString},
		{ID: 212, Name: "huawei-flow-id", DataType: DataTypeInteger},
		{ID: 214, Name: "huawei-dhcp-server-ip", DataType: DataTypeIPAddr},
		{
			ID:       215,
			Name:     "huawei-application-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"fixed":         1,
				"nomadic":       2,
				"portable":      3,
				"simple-mobile": 4,
				"full-mobile":   5,
			},
		},
		{ID: 216, Name: "huawei-indication-flag", DataType: DataTypeOctets},
		{ID: 217, Name: "huawei-original-nas-ip-address", DataType: DataTypeIPAddr},
		{
			ID:       218,
			Name:     "huawei-user-priority",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"common": 0,
				"copper": 1,
				"silver": 2,
				"gold":   3,
			},
		},
		{ID: 219, Name: "huawei-acs-url", DataType: DataTypeString},
		{ID: 220, Name: "huawei-provision-code", DataType: DataTypeString},
		{ID: 221, Name: "huawei-application-scene", DataType: DataTypeOctets},
		{ID: 222, Name: "huawei-ms-maximum-mac-study-number", DataType: DataTypeOctets},
		{ID: 232, Name: "huawei-ggsn-vendor", DataType: DataTypeString},
		{ID: 233, Name: "huawei-ggsn-version", DataType: DataTypeString},
		{ID: 238, Name: "huawei-ext-specific", DataType: DataTypeString},
		// master-only additions.
		{ID: 251, Name: "huawei-user-group-name", DataType: DataTypeString},
		{ID: 252, Name: "huawei-user-service-type", DataType: DataTypeInteger},
		{ID: 253, Name: "huawei-web-url", DataType: DataTypeString},
		{ID: 254, Name: "huawei-version", DataType: DataTypeString},
		{ID: 255, Name: "huawei-product-id", DataType: DataTypeString},
	},
}
