package goradius

// MikrotikVendorDefinition defines the Mikrotik vendor and its attributes
var MikrotikVendorDefinition = &VendorDefinition{
	ID:          14988,
	Name:        "mikrotik",
	Description: "Mikrotik RouterOS RADIUS attributes",
	Attributes: []*AttributeDefinition{
		{ID: 1, Name: "mikrotik-recv-limit", DataType: DataTypeInteger},
		{ID: 2, Name: "mikrotik-xmit-limit", DataType: DataTypeInteger},
		{ID: 3, Name: "mikrotik-group", DataType: DataTypeString},
		{ID: 4, Name: "mikrotik-wireless-forward", DataType: DataTypeInteger},
		{ID: 5, Name: "mikrotik-wireless-skip-dot1x", DataType: DataTypeInteger},
		{
			ID:       6,
			Name:     "mikrotik-wireless-enc-algo",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"no-encryption": 0,
				"40-bit-wep":    1,
				"104-bit-wep":   2,
				"aes-ccm":       3,
				"tkip":          4,
			},
		},
		{ID: 7, Name: "mikrotik-wireless-enc-key", DataType: DataTypeString},
		{ID: 8, Name: "mikrotik-rate-limit", DataType: DataTypeString},
		{ID: 9, Name: "mikrotik-realm", DataType: DataTypeString},
		{ID: 10, Name: "mikrotik-host-ip", DataType: DataTypeIPAddr},
		{ID: 11, Name: "mikrotik-mark-id", DataType: DataTypeString},
		{ID: 12, Name: "mikrotik-advertise-url", DataType: DataTypeString},
		{ID: 13, Name: "mikrotik-advertise-interval", DataType: DataTypeInteger},
		{ID: 14, Name: "mikrotik-recv-limit-gigawords", DataType: DataTypeInteger},
		{ID: 15, Name: "mikrotik-xmit-limit-gigawords", DataType: DataTypeInteger},
		{ID: 16, Name: "mikrotik-wireless-psk", DataType: DataTypeString},
		{ID: 17, Name: "mikrotik-total-limit", DataType: DataTypeInteger},
		{ID: 18, Name: "mikrotik-total-limit-gigawords", DataType: DataTypeInteger},
		{ID: 19, Name: "mikrotik-address-list", DataType: DataTypeString},
		{ID: 20, Name: "mikrotik-wireless-mpkey", DataType: DataTypeString},
		{ID: 21, Name: "mikrotik-wireless-comment", DataType: DataTypeString},
		{ID: 22, Name: "mikrotik-delegated-ipv6-pool", DataType: DataTypeString},
		{ID: 23, Name: "mikrotik-dhcp-option-set", DataType: DataTypeString},
		{ID: 24, Name: "mikrotik-dhcp-option-param-str1", DataType: DataTypeString},
		{ID: 25, Name: "mikrotik-dhcp-option-paramstr2", DataType: DataTypeString},
		{ID: 26, Name: "mikrotik-wireless-vlanid", DataType: DataTypeInteger},
		{ID: 27, Name: "mikrotik-wireless-vlanid-type", DataType: DataTypeInteger},
		{ID: 28, Name: "mikrotik-wireless-minsignal", DataType: DataTypeString},
		{ID: 29, Name: "mikrotik-wireless-maxsignal", DataType: DataTypeString},
	},
}
