package goradius

// EricssonABVendorDefinition defines the Ericsson-AB vendor (ID 2352), the
// Redback Networks / SmartEdge / SSR BNG attribute set (Redback was acquired
// by Ericsson). Ported from FreeRADIUS dictionary.ericsson.ab. This is the
// BNG-relevant Ericsson vendor: subscriber binding, L2TP tunnels, QoS
// policing/metering, DSL line attributes, and service activation.
//
// Tagged service and tunnel attributes keep their has_tag flag; the 64-bit
// accounting counters (IDs 128-136) use the integer64 type. The dictionary
// carries no per-packet placement data, so all attributes stay unrestricted.
var EricssonABVendorDefinition = &VendorDefinition{
	ID:   2352,
	Name: "ericsson-ab",
	Attributes: []*AttributeDefinition{
		{ID: 1, Name: "ericsson-ab-client-dns-pri", DataType: DataTypeIPAddr},
		{ID: 2, Name: "ericsson-ab-client-dns-sec", DataType: DataTypeIPAddr},
		{ID: 3, Name: "ericsson-ab-dhcp-max-leases", DataType: DataTypeInteger},
		{ID: 4, Name: "ericsson-ab-context-name", DataType: DataTypeString},
		{ID: 5, Name: "ericsson-ab-bridge-group", DataType: DataTypeString},
		{ID: 6, Name: "ericsson-ab-bg-aging-time", DataType: DataTypeString},
		{ID: 7, Name: "ericsson-ab-bg-path-cost", DataType: DataTypeString},
		{ID: 8, Name: "ericsson-ab-bg-span-dis", DataType: DataTypeString},
		{ID: 9, Name: "ericsson-ab-bg-trans-bpdu", DataType: DataTypeString},
		{ID: 10, Name: "ericsson-ab-rate-limit-rate", DataType: DataTypeInteger},
		{ID: 11, Name: "ericsson-ab-rate-limit-burst", DataType: DataTypeInteger},
		{ID: 12, Name: "ericsson-ab-police-rate", DataType: DataTypeInteger},
		{ID: 13, Name: "ericsson-ab-police-burst", DataType: DataTypeInteger},
		{
			ID:       14,
			Name:     "ericsson-ab-source-validation",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"enabled":  1,
				"disabled": 2,
			},
		},
		{
			ID:       15,
			Name:     "ericsson-ab-tunnel-domain",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"enabled":  1,
				"disabled": 2,
			},
		},
		{ID: 16, Name: "ericsson-ab-tunnel-local-name", DataType: DataTypeString},
		{ID: 17, Name: "ericsson-ab-tunnel-remote-name", DataType: DataTypeString},
		{
			ID:       18,
			Name:     "ericsson-ab-tunnel-function",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"lac-only": 1,
				"lns-only": 2,
				"lac-lns":  3,
			},
		},
		{ID: 19, Name: "ericsson-ab-tunnel-flow-control", DataType: DataTypeInteger},
		{ID: 20, Name: "ericsson-ab-tunnel-static", DataType: DataTypeInteger},
		{ID: 21, Name: "ericsson-ab-tunnel-max-sessions", DataType: DataTypeInteger},
		{ID: 22, Name: "ericsson-ab-tunnel-max-tunnels", DataType: DataTypeInteger},
		{
			ID:       23,
			Name:     "ericsson-ab-tunnel-session-auth",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"chap":     1,
				"pap":      2,
				"chap-pap": 3,
			},
		},
		{ID: 24, Name: "ericsson-ab-tunnel-window", DataType: DataTypeInteger},
		{ID: 25, Name: "ericsson-ab-tunnel-retransmit", DataType: DataTypeInteger},
		{ID: 26, Name: "ericsson-ab-tunnel-cmd-timeout", DataType: DataTypeInteger},
		{ID: 27, Name: "ericsson-ab-pppoe-url", DataType: DataTypeString},
		{ID: 28, Name: "ericsson-ab-pppoe-motm", DataType: DataTypeString},
		{
			ID:       29,
			Name:     "ericsson-ab-tunnel-group",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"enabled":  1,
				"disabled": 2,
			},
		},
		{ID: 30, Name: "ericsson-ab-tunnel-context", DataType: DataTypeString},
		{
			ID:       31,
			Name:     "ericsson-ab-tunnel-algorithm",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"first":        1,
				"load-balance": 2,
				"wrr":          3,
			},
		},
		{ID: 32, Name: "ericsson-ab-tunnel-deadtime", DataType: DataTypeInteger},
		{
			ID:       33,
			Name:     "ericsson-ab-mcast-send",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"no-send":          1,
				"send":             2,
				"unsolicited-send": 3,
			},
		},
		{
			ID:       34,
			Name:     "ericsson-ab-mcast-receive",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"no-receive": 1,
				"receive":    2,
			},
		},
		{ID: 35, Name: "ericsson-ab-mcast-maxgroups", DataType: DataTypeInteger},
		{ID: 36, Name: "ericsson-ab-ip-address-pool-name", DataType: DataTypeString},
		{
			ID:       37,
			Name:     "ericsson-ab-tunnel-dnis",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"dnis":          1,
				"dnis-only":     2,
				"dnis-generate": 4,
			},
		},
		{
			ID:       38,
			Name:     "ericsson-ab-medium-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"dsl":       11,
				"cable":     12,
				"wireless":  13,
				"satellite": 14,
			},
		},
		{
			ID:       39,
			Name:     "ericsson-ab-pvc-encapsulation-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"aaa-encaps-atm-raw":                  1,
				"aaa-encaps-atm-route1483":            2,
				"aaa-encaps-atm-auto1483":             3,
				"aaa-encaps-atm-multi":                4,
				"aaa-encaps-atm-bridge1483":           5,
				"aaa-encaps-atm-ppp":                  6,
				"aaa-encaps-atm-ppp-serial":           7,
				"aaa-encaps-atm-ppp-nlpid":            8,
				"aaa-encaps-atm-ppp-auto":             9,
				"aaa-encaps-atm-pppoe":                10,
				"aaa-encaps-atm-l2tp":                 11,
				"aaa-encaps-atm-ppp-llc":              12,
				"aaa-encaps-frame-auto1490":           13,
				"aaa-encaps-frame-multi":              14,
				"aaa-encaps-frame-bridge1490":         15,
				"aaa-encaps-frame-ppp":                16,
				"aaa-encaps-frame-ppp-auto":           17,
				"aaa-encaps-frame-pppoe":              18,
				"aaa-encaps-frame-route1490":          19,
				"aaa-encaps-frame-l2tp":               20,
				"aaa-encaps-l2tp-vc-muxed":            21,
				"aaa-encaps-eth":                      22,
				"aaa-encaps-eth-pppoe":                23,
				"aaa-encaps-eth-multi":                24,
				"aaa-encaps-eth-dot1q":                25,
				"aaa-encaps-eth-dot1q-pppoe":          26,
				"aaa-encaps-atm-multi-pppoe":          27,
				"aaa-encaps-atm-multi-ipv6oe":         28,
				"aaa-encaps-atm-multi-pppoe-n-ipv6oe": 29,
				"aaa-encaps-eth-dot1q-tunnel":         30,
				"aaa-encaps-eth-dot1q-tunnel-pppoe":   31,
			},
		},
		{ID: 40, Name: "ericsson-ab-pvc-profile-name", DataType: DataTypeString},
		{
			ID:       41,
			Name:     "ericsson-ab-pvc-circuit-padding",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"aaa-circuit-padding":    1,
				"aaa-circuit-no-padding": 2,
			},
		},
		{
			ID:       42,
			Name:     "ericsson-ab-bind-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"aaa-auth-bind":            1,
				"aaa-bypass-bind":          2,
				"aaa-interface-bind":       3,
				"aaa-subscribe-bind":       4,
				"aaa-tunnel-bind":          5,
				"aaa-session-bind":         6,
				"aaa-q8021-bind":           7,
				"aaa-multi-bind":           8,
				"aaa-dhcp-bind":            9,
				"aaa-multi-bind-sub":       10,
				"aaa-bridge-group-bind":    11,
				"aaa-vlan-bind":            12,
				"aaa-vlan-group-bind":      13,
				"aaa-auto-subscriber-bind": 14,
			},
		},
		{
			ID:       43,
			Name:     "ericsson-ab-bind-auth-protocol",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"aaa-ppp-pap":           1,
				"aaa-ppp-chap":          2,
				"aaa-ppp-chap-wait":     3,
				"aaa-ppp-chap-pap":      4,
				"aaa-ppp-chap-wait-pap": 5,
				"aaa-ppp-eap":           6,
				"aaa-ppp-pap-chap":      7,
				"aaa-ppp-pap-chap-wait": 8,
			},
		},
		{ID: 44, Name: "ericsson-ab-bind-auth-max-sessions", DataType: DataTypeInteger},
		{ID: 45, Name: "ericsson-ab-bind-bypass-bypass", DataType: DataTypeString},
		{ID: 46, Name: "ericsson-ab-bind-auth-context", DataType: DataTypeString},
		{ID: 47, Name: "ericsson-ab-bind-auth-service-grp", DataType: DataTypeString},
		{ID: 48, Name: "ericsson-ab-bind-bypass-context", DataType: DataTypeString},
		{ID: 49, Name: "ericsson-ab-bind-int-context", DataType: DataTypeString},
		{ID: 50, Name: "ericsson-ab-bind-tun-context", DataType: DataTypeString},
		{ID: 51, Name: "ericsson-ab-bind-ses-context", DataType: DataTypeString},
		{ID: 52, Name: "ericsson-ab-bind-dot1q-slot", DataType: DataTypeInteger},
		{ID: 53, Name: "ericsson-ab-bind-dot1q-port", DataType: DataTypeInteger},
		{ID: 54, Name: "ericsson-ab-bind-dot1q-vlan-tag-id", DataType: DataTypeInteger},
		{ID: 55, Name: "ericsson-ab-bind-int-interface-name", DataType: DataTypeString},
		{ID: 56, Name: "ericsson-ab-bind-l2tp-tunnel-name", DataType: DataTypeString},
		{ID: 57, Name: "ericsson-ab-bind-l2tp-flow-control", DataType: DataTypeInteger},
		{ID: 58, Name: "ericsson-ab-bind-sub-user-at-context", DataType: DataTypeString},
		{ID: 59, Name: "ericsson-ab-bind-sub-password", DataType: DataTypeString},
		{ID: 60, Name: "ericsson-ab-ip-host-addr", DataType: DataTypeString},
		{
			ID:       61,
			Name:     "ericsson-ab-ip-tos-field",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"normal":                                                           0,
				"min-cost-only":                                                    1,
				"max-reliability-only":                                             2,
				"max-reliability-plus-min-cost":                                    3,
				"max-throughput-only":                                              4,
				"max-throughput-plus-min-cost":                                     5,
				"max-throughput-plus-max-reliability":                              6,
				"max-throughput-plus-max-reliability-plus-min-cost":                7,
				"min-delay-only":                                                   8,
				"min-delay-plus-min-cost":                                          9,
				"min-delay-plus-max-reliability":                                   10,
				"min-delay-plus-max-reliability-plus-min-cost":                     11,
				"min-delay-plus-max-throughput":                                    12,
				"min-delay-plus-max-throughput-plus-min-cost":                      13,
				"min-delay-plus-max-throughput-plus-max-reliability":               14,
				"min-delay-plus-max-throughput-plus-max-reliability-plus-min-cost": 15,
			},
		},
		{ID: 62, Name: "ericsson-ab-nas-real-port", DataType: DataTypeInteger},
		{ID: 63, Name: "ericsson-ab-tunnel-session-auth-ctx", DataType: DataTypeString},
		{ID: 64, Name: "ericsson-ab-tunnel-session-auth-service-grp", DataType: DataTypeString},
		{ID: 65, Name: "ericsson-ab-tunnel-rate-limit-rate", DataType: DataTypeInteger},
		{ID: 66, Name: "ericsson-ab-tunnel-rate-limit-burst", DataType: DataTypeInteger},
		{ID: 67, Name: "ericsson-ab-tunnel-police-rate", DataType: DataTypeInteger},
		{ID: 68, Name: "ericsson-ab-tunnel-police-burst", DataType: DataTypeInteger},
		{ID: 69, Name: "ericsson-ab-tunnel-l2f-second-password", DataType: DataTypeString},
		{ID: 70, Name: "ericsson-ab-acl-definition", DataType: DataTypeString},
		{ID: 71, Name: "ericsson-ab-pppoe-ip-route-add", DataType: DataTypeString},
		{ID: 72, Name: "ericsson-ab-tty-level-max", DataType: DataTypeInteger},
		{ID: 73, Name: "ericsson-ab-tty-level-start", DataType: DataTypeInteger},
		{ID: 74, Name: "ericsson-ab-tunnel-checksum", DataType: DataTypeInteger},
		{ID: 75, Name: "ericsson-ab-tunnel-profile", DataType: DataTypeString},
		{ID: 78, Name: "ericsson-ab-tunnel-client-vpn", DataType: DataTypeString},
		{ID: 79, Name: "ericsson-ab-tunnel-server-vpn", DataType: DataTypeString},
		{ID: 80, Name: "ericsson-ab-tunnel-client-rhost", DataType: DataTypeString},
		{ID: 81, Name: "ericsson-ab-tunnel-server-rhost", DataType: DataTypeString},
		{ID: 82, Name: "ericsson-ab-tunnel-client-int-addr", DataType: DataTypeIPAddr},
		{ID: 83, Name: "ericsson-ab-tunnel-server-int-addr", DataType: DataTypeIPAddr},
		{ID: 84, Name: "ericsson-ab-ppp-compression", DataType: DataTypeInteger},
		{
			ID:       85,
			Name:     "ericsson-ab-tunnel-hello-timer",
			DataType: DataTypeInteger,
			HasTag:   true,
		},
		{ID: 86, Name: "ericsson-ab-redback-reason", DataType: DataTypeInteger},
		{ID: 87, Name: "ericsson-ab-qos-policing-profile-name", DataType: DataTypeString},
		{ID: 88, Name: "ericsson-ab-qos-metering-profile-name", DataType: DataTypeString},
		{ID: 89, Name: "ericsson-ab-qos-policy-queuing", DataType: DataTypeString},
		{ID: 90, Name: "ericsson-ab-igmp-service-profile-name", DataType: DataTypeString},
		{ID: 91, Name: "ericsson-ab-subscriber-profile-name", DataType: DataTypeString},
		{ID: 92, Name: "ericsson-ab-forward-policy", DataType: DataTypeString},
		{ID: 93, Name: "ericsson-ab-remote-port", DataType: DataTypeString},
		{ID: 94, Name: "ericsson-ab-reauth", DataType: DataTypeString},
		{ID: 95, Name: "ericsson-ab-reauth-more", DataType: DataTypeInteger},
		{ID: 96, Name: "ericsson-ab-agent-remote-id", DataType: DataTypeOctets},
		{ID: 97, Name: "ericsson-ab-agent-circuit-id", DataType: DataTypeOctets},
		{
			ID:       98,
			Name:     "ericsson-ab-platform-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"sms":           1,
				"smartedge-800": 2,
				"se-400":        3,
				"se-100":        4,
			},
		},
		{ID: 99, Name: "ericsson-ab-client-nbns-pri", DataType: DataTypeIPAddr},
		{ID: 100, Name: "ericsson-ab-client-nbns-sec", DataType: DataTypeIPAddr},
		{ID: 101, Name: "ericsson-ab-shaping-profile-name", DataType: DataTypeString},
		{ID: 103, Name: "ericsson-ab-bg-cct-addr-max", DataType: DataTypeInteger},
		{ID: 104, Name: "ericsson-ab-ip-interface-name", DataType: DataTypeString},
		{ID: 105, Name: "ericsson-ab-nat-policy-name", DataType: DataTypeString},
		{ID: 106, Name: "ericsson-ab-rb-npm-service-id", DataType: DataTypeString},
		{ID: 107, Name: "ericsson-ab-http-redirect-profile-name", DataType: DataTypeString},
		{ID: 108, Name: "ericsson-ab-bind-auto-sub-user", DataType: DataTypeString},
		{ID: 109, Name: "ericsson-ab-bind-auto-sub-context", DataType: DataTypeString},
		{ID: 110, Name: "ericsson-ab-bind-auto-sub-password", DataType: DataTypeString},
		{
			ID:       111,
			Name:     "ericsson-ab-circuit-protocol-encap",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"encaps-pppoe": 27,
			},
		},
		{ID: 112, Name: "ericsson-ab-os-version", DataType: DataTypeString},
		{ID: 113, Name: "ericsson-ab-session-traffic-limit", DataType: DataTypeString},
		{ID: 114, Name: "ericsson-ab-qos-reference", DataType: DataTypeString},
		{ID: 121, Name: "ericsson-ab-rate-limit-excess-burst", DataType: DataTypeOctets},
		{ID: 122, Name: "ericsson-ab-police-excess-burst", DataType: DataTypeOctets},
		{ID: 123, Name: "ericsson-ab-tunnel-rate-limit-excess-burst", DataType: DataTypeOctets},
		{ID: 124, Name: "ericsson-ab-tunnel-police-excess-burst", DataType: DataTypeOctets},
		{ID: 125, Name: "ericsson-ab-dhcp-vendor-class-id", DataType: DataTypeString},
		{ID: 126, Name: "ericsson-ab-qos-rate", DataType: DataTypeString},
		{ID: 127, Name: "ericsson-ab-dhcp-vendor-encap-option", DataType: DataTypeString},
		{ID: 128, Name: "ericsson-ab-acct-input-octets-64", DataType: DataTypeInteger64},
		{ID: 129, Name: "ericsson-ab-acct-output-octets-64", DataType: DataTypeInteger64},
		{ID: 130, Name: "ericsson-ab-acct-input-packets-64", DataType: DataTypeInteger64},
		{ID: 131, Name: "ericsson-ab-acct-output-packets-64", DataType: DataTypeInteger64},
		{ID: 132, Name: "ericsson-ab-assigned-ip-address", DataType: DataTypeIPAddr},
		{ID: 133, Name: "ericsson-ab-acct-mcast-in-octets-64", DataType: DataTypeInteger64},
		{ID: 134, Name: "ericsson-ab-acct-mcast-out-octets-64", DataType: DataTypeInteger64},
		{ID: 135, Name: "ericsson-ab-acct-mcast-in-packets-64", DataType: DataTypeInteger64},
		{ID: 136, Name: "ericsson-ab-acct-mcast-out-packets-64", DataType: DataTypeInteger64},
		{ID: 137, Name: "ericsson-ab-lac-port", DataType: DataTypeInteger},
		{ID: 138, Name: "ericsson-ab-lac-real-port", DataType: DataTypeInteger},
		{
			ID:       139,
			Name:     "ericsson-ab-lac-port-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"nas-port-type-10bt":      40,
				"nas-port-type-100bt":     41,
				"nas-port-type-ds3-fr":    42,
				"nas-port-type-ds3-atm":   43,
				"nas-port-type-oc3":       44,
				"nas-port-type-hssi":      45,
				"nas-port-type-eia530":    46,
				"nas-port-type-t1":        47,
				"nas-port-type-chan-t3":   48,
				"nas-port-type-ds1-fr":    49,
				"nas-port-type-e3-atm":    50,
				"nas-port-type-ima-atm":   51,
				"nas-port-type-ds3-atm-2": 52,
				"nas-port-type-oc3-atm-2": 53,
				"nas-port-type-1000bsx":   54,
				"nas-port-type-e1-fr":     55,
				"nas-port-type-e1-atm":    56,
				"nas-port-type-e3-fr":     57,
				"nas-port-type-oc3-pos":   58,
				"nas-port-type-oc12-pos":  59,
				"nas-port-type-pppoe":     60,
			},
		},
		{
			ID:       140,
			Name:     "ericsson-ab-lac-real-port-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"nas-port-type-10bt":      40,
				"nas-port-type-100bt":     41,
				"nas-port-type-ds3-fr":    42,
				"nas-port-type-ds3-atm":   43,
				"nas-port-type-oc3":       44,
				"nas-port-type-hssi":      45,
				"nas-port-type-eia530":    46,
				"nas-port-type-t1":        47,
				"nas-port-type-chan-t3":   48,
				"nas-port-type-ds1-fr":    49,
				"nas-port-type-e3-atm":    50,
				"nas-port-type-ima-atm":   51,
				"nas-port-type-ds3-atm-2": 52,
				"nas-port-type-oc3-atm-2": 53,
				"nas-port-type-1000bsx":   54,
				"nas-port-type-e1-fr":     55,
				"nas-port-type-e1-atm":    56,
				"nas-port-type-e3-fr":     57,
				"nas-port-type-oc3-pos":   58,
				"nas-port-type-oc12-pos":  59,
				"nas-port-type-pppoe":     60,
			},
		},
		{ID: 141, Name: "ericsson-ab-acct-dyn-ac-ent", DataType: DataTypeString},
		{ID: 142, Name: "ericsson-ab-session-error-code", DataType: DataTypeInteger},
		{ID: 143, Name: "ericsson-ab-session-error-msg", DataType: DataTypeString},
		{
			ID:       144,
			Name:     "ericsson-ab-acct-update-reason",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"aaa-load-acct-session-up":            1,
				"aaa-load-acct-session-down":          2,
				"aaa-load-acct-periodic":              3,
				"aaa-load-acct-dyn-ac-ent-start":      4,
				"aaa-load-acct-dyn-ac-ent-stop":       5,
				"aaa-load-acct-dyn-ac-ent-timeout":    6,
				"aaa-load-acct-subscriber-reauthor":   7,
				"aaa-load-acct-ppp-ipcp-up":           8,
				"aaa-load-acct-ppp-mp-link-up":        9,
				"aaa-load-acct-dhcp-ip-addr-granted":  10,
				"aaa-load-acct-dhcp-ip-addr-released": 11,
				"aaa-load-acct-acl-timered-action":    12,
				"aaa-load-acct-acl-action":            13,
				"aaa-load-acct-cmd":                   14,
				"aaa-load-acct-test":                  15,
			},
		},
		{ID: 145, Name: "ericsson-ab-mac-addr", DataType: DataTypeString},
		{ID: 146, Name: "ericsson-ab-vlan-source-info", DataType: DataTypeString},
		{ID: 147, Name: "ericsson-ab-acct-mcast-in-octets", DataType: DataTypeInteger},
		{ID: 148, Name: "ericsson-ab-acct-mcast-out-octets", DataType: DataTypeInteger},
		{ID: 149, Name: "ericsson-ab-acct-mcast-in-packets", DataType: DataTypeInteger},
		{ID: 150, Name: "ericsson-ab-acct-mcast-out-packets", DataType: DataTypeInteger},
		{ID: 151, Name: "ericsson-ab-reauth-session-id", DataType: DataTypeString},
		{ID: 156, Name: "ericsson-ab-qos-rate-inbound", DataType: DataTypeString},
		{ID: 157, Name: "ericsson-ab-qos-rate-outbound", DataType: DataTypeString},
		{ID: 158, Name: "ericsson-ab-route-tag", DataType: DataTypeInteger},
		{ID: 159, Name: "ericsson-ab-li-id", DataType: DataTypeInteger},
		{ID: 160, Name: "ericsson-ab-li-md-address", DataType: DataTypeIPAddr},
		{ID: 161, Name: "ericsson-ab-li-md-port", DataType: DataTypeInteger},
		{ID: 162, Name: "ericsson-ab-li-action", DataType: DataTypeInteger},
		{ID: 163, Name: "ericsson-ab-li-profile", DataType: DataTypeString},
		{ID: 164, Name: "ericsson-ab-dynamic-policy-filter", DataType: DataTypeString},
		{ID: 165, Name: "ericsson-ab-http-redirect-url", DataType: DataTypeString},
		{ID: 166, Name: "ericsson-ab-dsl-actual-rate-up", DataType: DataTypeInteger},
		{ID: 167, Name: "ericsson-ab-dsl-actual-rate-down", DataType: DataTypeInteger},
		{ID: 168, Name: "ericsson-ab-dsl-min-rate-up", DataType: DataTypeInteger},
		{ID: 169, Name: "ericsson-ab-dsl-min-rate-down", DataType: DataTypeInteger},
		{ID: 170, Name: "ericsson-ab-dsl-attainable-rate-up", DataType: DataTypeInteger},
		{ID: 171, Name: "ericsson-ab-dsl-attainable-rate-down", DataType: DataTypeInteger},
		{ID: 172, Name: "ericsson-ab-dsl-max-rate-up", DataType: DataTypeInteger},
		{ID: 173, Name: "ericsson-ab-dsl-max-rate-down", DataType: DataTypeInteger},
		{ID: 174, Name: "ericsson-ab-dsl-min-low-power-rate-up", DataType: DataTypeInteger},
		{ID: 175, Name: "ericsson-ab-dsl-min-low-power-rate-down", DataType: DataTypeInteger},
		{ID: 176, Name: "ericsson-ab-dsl-max-inter-delay-up", DataType: DataTypeInteger},
		{ID: 177, Name: "ericsson-ab-dsl-actual-inter-delay-up", DataType: DataTypeInteger},
		{ID: 178, Name: "ericsson-ab-dsl-max-inter-delay-down", DataType: DataTypeInteger},
		{ID: 179, Name: "ericsson-ab-dsl-actual-inter-delay-down", DataType: DataTypeInteger},
		{
			ID:       180,
			Name:     "ericsson-ab-dsl-line-state",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"showtime": 1,
				"idle":     2,
				"silent":   3,
			},
		},
		{ID: 181, Name: "ericsson-ab-dsl-l2-encapsulation", DataType: DataTypeInteger},
		{
			ID:       182,
			Name:     "ericsson-ab-dsl-transmission-system",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"adsl1":   1,
				"adsl2":   2,
				"adsl2+":  3,
				"vdsl1":   4,
				"vdsl2":   5,
				"sdsl":    6,
				"unknown": 7,
			},
		},
		{ID: 183, Name: "ericsson-ab-dsl-pppoa-pppoe-inter-work-flag", DataType: DataTypeInteger},
		{ID: 185, Name: "ericsson-ab-dsl-actual-rate-down-factor", DataType: DataTypeInteger},
		{ID: 184, Name: "ericsson-ab-dsl-combined-line-info", DataType: DataTypeString},
		{ID: 186, Name: "ericsson-ab-class-volume-limit", DataType: DataTypeString},
		{ID: 187, Name: "ericsson-ab-class-volume-in-counter", DataType: DataTypeString},
		{ID: 188, Name: "ericsson-ab-class-volume-out-counter", DataType: DataTypeString},
		{ID: 189, Name: "ericsson-ab-flow-fac-profile", DataType: DataTypeString},
		{
			ID:       190,
			Name:     "ericsson-ab-service-name",
			DataType: DataTypeString,
			HasTag:   true,
		},
		{
			ID:       191,
			Name:     "ericsson-ab-service-action",
			DataType: DataTypeInteger,
			HasTag:   true,
			Values: map[string]uint32{
				"de-activate":           0,
				"activate-with-acct":    1,
				"activate-without-acct": 2,
			},
		},
		{
			ID:       192,
			Name:     "ericsson-ab-service-parameter",
			DataType: DataTypeString,
			HasTag:   true,
		},
		{
			ID:       193,
			Name:     "ericsson-ab-service-error-cause",
			DataType: DataTypeInteger,
			HasTag:   true,
			Values: map[string]uint32{
				"service-success":             0,
				"unsupported-attribute":       401,
				"missing-attribute":           402,
				"invalid-request":             404,
				"resource-unavailable":        506,
				"generic-service-error":       550,
				"service-not-found":           551,
				"service-already-active":      552,
				"service-accounting-disabled": 553,
				"service-duplicate-parameter": 554,
			},
		},
		{
			ID:       194,
			Name:     "ericsson-ab-deactivate-service-name",
			DataType: DataTypeString,
			HasTag:   true,
		},
		{ID: 195, Name: "ericsson-ab-qos-profile-overhead", DataType: DataTypeString},
		{ID: 196, Name: "ericsson-ab-dynamic-qos-param", DataType: DataTypeString},
		{ID: 197, Name: "ericsson-ab-acct-alt-session-id", DataType: DataTypeString},
		{ID: 198, Name: "ericsson-ab-idle-timeout-threshold", DataType: DataTypeInteger},
		{ID: 199, Name: "ericsson-ab-double-authentication", DataType: DataTypeInteger},
		{ID: 200, Name: "ericsson-ab-sbc-adjacency", DataType: DataTypeString},
		{ID: 201, Name: "ericsson-ab-dhcp-field", DataType: DataTypeOctets},
		{ID: 202, Name: "ericsson-ab-dhcp-option", DataType: DataTypeOctets},
		{ID: 203, Name: "ericsson-ab-security-service", DataType: DataTypeString},
		{
			ID:       204,
			Name:     "ericsson-ab-reauth-service-name",
			DataType: DataTypeString,
			HasTag:   true,
		},
		{ID: 205, Name: "ericsson-ab-flow-ip-profile", DataType: DataTypeString},
		{ID: 206, Name: "ericsson-ab-radius-throttle-watermark", DataType: DataTypeInteger},
		{ID: 207, Name: "ericsson-ab-rb-ipv6-dns", DataType: DataTypeString},
		{ID: 208, Name: "ericsson-ab-rb-ipv6-option", DataType: DataTypeString},
		{ID: 209, Name: "ericsson-ab-cluster-partition-id", DataType: DataTypeString},
		{ID: 210, Name: "ericsson-ab-circuit-group-member", DataType: DataTypeString},
		{ID: 212, Name: "ericsson-ab-delegated-max-prefix", DataType: DataTypeInteger},
		{ID: 213, Name: "ericsson-ab-ipv4-address-release-control", DataType: DataTypeString},
		{ID: 214, Name: "ericsson-ab-acct-input-ipv4-octets", DataType: DataTypeInteger},
		{ID: 215, Name: "ericsson-ab-acct-output-ipv4-octets", DataType: DataTypeInteger},
		{ID: 216, Name: "ericsson-ab-acct-input-ipv4-packets", DataType: DataTypeInteger},
		{ID: 217, Name: "ericsson-ab-acct-output-ipv4-packets", DataType: DataTypeInteger},
		{ID: 218, Name: "ericsson-ab-acct-input-ipv4-gigawords", DataType: DataTypeInteger},
		{ID: 219, Name: "ericsson-ab-acct-output-ipv4-gigawords", DataType: DataTypeInteger},
		{ID: 220, Name: "ericsson-ab-acct-input-ipv6-octets", DataType: DataTypeInteger},
		{ID: 221, Name: "ericsson-ab-acct-output-ipv6-octets", DataType: DataTypeInteger},
		{ID: 222, Name: "ericsson-ab-acct-input-ipv6-packets", DataType: DataTypeInteger},
		{ID: 223, Name: "ericsson-ab-acct-output-ipv6-packets", DataType: DataTypeInteger},
		{ID: 224, Name: "ericsson-ab-acct-input-ipv6-gigawords", DataType: DataTypeInteger},
		{ID: 225, Name: "ericsson-ab-acct-output-ipv6-gigawords", DataType: DataTypeInteger},
	},
}
