package goradius

// MicrosoftVendorDefinition defines the Microsoft vendor (ID 311) and its attributes.
// Ported from FreeRADIUS dictionary.microsoft. Includes the MS-CHAP/MPPE family and
// the DNS/NBNS server attributes used by broadband access gateways.
// Usage masks follow RFC 2548 Section 3 "Table of Attributes"; attributes 34-63
// post-date RFC 2548 and stay unrestricted.
var MicrosoftVendorDefinition = &VendorDefinition{
	ID:   311,
	Name: "microsoft",
	Attributes: []*AttributeDefinition{
		{
			ID:       1,
			Name:     "ms-chap-response",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       2,
			Name:     "ms-chap-error",
			DataType: DataTypeString,
			Usage:    UsageAccessReject,
		},
		{
			ID:       3,
			Name:     "ms-chap-cpw-1",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       4,
			Name:     "ms-chap-cpw-2",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       5,
			Name:     "ms-chap-lm-enc-pw",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       6,
			Name:     "ms-chap-nt-enc-pw",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       7,
			Name:     "ms-mppe-encryption-policy",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"encryption-allowed":  1,
				"encryption-required": 2,
			},
		},
		{
			ID:       8,
			Name:     "ms-mppe-encryption-types",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"rc4-40bit-allowed":       1,
				"rc4-128bit-allowed":      2,
				"rc4-40or128-bit-allowed": 6,
			},
		},
		{
			ID:       9,
			Name:     "ms-ras-vendor",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       10,
			Name:     "ms-chap-domain",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       11,
			Name:     "ms-chap-challenge",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest | UsageAccessChallenge,
		},
		{
			ID:         12,
			Name:       "ms-chap-mppe-keys",
			DataType:   DataTypeOctets,
			Usage:      UsageAccessAccept,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:       13,
			Name:     "ms-bap-usage",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"not-allowed": 0,
				"allowed":     1,
				"required":    2,
			},
		},
		{
			ID:       14,
			Name:     "ms-link-utilization-threshold",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       15,
			Name:     "ms-link-drop-time-limit",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
		},
		{
			ID:         16,
			Name:       "ms-mppe-send-key",
			DataType:   DataTypeOctets,
			Usage:      UsageAccessAccept,
			Encryption: EncryptionTunnelPassword,
		},
		{
			ID:         17,
			Name:       "ms-mppe-recv-key",
			DataType:   DataTypeOctets,
			Usage:      UsageAccessAccept,
			Encryption: EncryptionTunnelPassword,
		},
		{
			ID:       18,
			Name:     "ms-ras-version",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       19,
			Name:     "ms-old-arap-password",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       20,
			Name:     "ms-new-arap-password",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       21,
			Name:     "ms-arap-pw-change-reason",
			DataType: DataTypeInteger,
			Usage:    UsageAccessChallenge,
			Values: map[string]uint32{
				"just-change-password":           1,
				"expired-password":               2,
				"admin-requires-password-change": 3,
				"password-too-short":             4,
			},
		},
		{
			ID:       22,
			Name:     "ms-filter",
			DataType: DataTypeOctets,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       23,
			Name:     "ms-acct-auth-type",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
			Values: map[string]uint32{
				"pap":       1,
				"chap":      2,
				"ms-chap-1": 3,
				"ms-chap-2": 4,
				"eap":       5,
			},
		},
		{
			ID:       24,
			Name:     "ms-acct-eap-type",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
			Values: map[string]uint32{
				"md5":                4,
				"otp":                5,
				"generic-token-card": 6,
				"tls":                13,
			},
		},
		{
			ID:       25,
			Name:     "ms-chap2-response",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       26,
			Name:     "ms-chap2-success",
			DataType: DataTypeOctets,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       27,
			Name:     "ms-chap2-cpw",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       28,
			Name:     "ms-primary-dns-server",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       29,
			Name:     "ms-secondary-dns-server",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       30,
			Name:     "ms-primary-nbns-server",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       31,
			Name:     "ms-secondary-nbns-server",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{ID: 34, Name: "ms-ras-client-name", DataType: DataTypeString},
		{ID: 35, Name: "ms-ras-client-version", DataType: DataTypeString},
		{ID: 36, Name: "ms-quarantine-ipfilter", DataType: DataTypeOctets},
		{ID: 37, Name: "ms-quarantine-session-timeout", DataType: DataTypeInteger},
		{ID: 40, Name: "ms-user-security-identity", DataType: DataTypeString},
		{
			ID:       41,
			Name:     "ms-identity-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"machine-health-check":       1,
				"ignore-user-lookup-failure": 2,
			},
		},
		{ID: 42, Name: "ms-service-class", DataType: DataTypeString},
		{ID: 44, Name: "ms-quarantine-user-class", DataType: DataTypeString},
		{
			ID:       45,
			Name:     "ms-quarantine-state",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"full-access": 0,
				"quarantine":  1,
				"probation":   2,
			},
		},
		{ID: 46, Name: "ms-quarantine-grace-time", DataType: DataTypeInteger},
		{
			ID:       47,
			Name:     "ms-network-access-server-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"unspecified":             0,
				"terminal-server-gateway": 1,
				"remote-access-server":    2,
				"dhcp-server":             3,
				"wireless-access-point":   4,
				"hra":                     5,
				"hcap-server":             6,
			},
		},
		{
			ID:       48,
			Name:     "ms-afw-zone",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ms-afw-zone-boundary-policy":    1,
				"ms-afw-zone-unprotected-policy": 2,
				"ms-afw-zone-protected-policy":   3,
			},
		},
		{
			ID:       49,
			Name:     "ms-afw-protection-level",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"hecp-response-sign-only":        1,
				"hecp-response-sign-and-encrypt": 2,
			},
		},
		{ID: 50, Name: "ms-machine-name", DataType: DataTypeString},
		{ID: 51, Name: "ms-ipv6-filter", DataType: DataTypeOctets},
		{ID: 52, Name: "ms-ipv4-remediation-servers", DataType: DataTypeOctets},
		{ID: 53, Name: "ms-ipv6-remediation-servers", DataType: DataTypeOctets},
		{
			ID:       54,
			Name:     "ms-rnap-not-quarantine-capable",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"soh-sent":     0,
				"soh-not-sent": 1,
			},
		},
		{ID: 55, Name: "ms-quarantine-soh", DataType: DataTypeOctets},
		{ID: 56, Name: "ms-ras-correlation", DataType: DataTypeOctets},
		{
			ID:       57,
			Name:     "ms-extended-quarantine-state",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"transition": 1,
				"infected":   2,
				"unknown":    3,
				"no-data":    4,
			},
		},
		{ID: 58, Name: "ms-hcap-user-groups", DataType: DataTypeString},
		{ID: 59, Name: "ms-hcap-location-group-name", DataType: DataTypeString},
		{ID: 60, Name: "ms-hcap-user-name", DataType: DataTypeString},
		{ID: 61, Name: "ms-user-ipv4-address", DataType: DataTypeIPAddr},
		{ID: 62, Name: "ms-user-ipv6-address", DataType: DataTypeIPv6Addr},
		{ID: 63, Name: "ms-tsg-device-redirection", DataType: DataTypeInteger},
	},
}
