package goradius

// AscendVendorDefinition contains the Ascend vendor definition with all its attributes
var AscendVendorDefinition = &VendorDefinition{
	ID:   529,
	Name: "ascend",
	Attributes: []*AttributeDefinition{
		{ID: 2, Name: "ascend-max-shared-users", DataType: DataTypeInteger},
		{ID: 7, Name: "ascend-uu-info", DataType: DataTypeString},
		{ID: 9, Name: "ascend-cir-timer", DataType: DataTypeInteger},
		{ID: 10, Name: "ascend-fr-08-mode", DataType: DataTypeInteger},
		{ID: 11, Name: "ascend-destination-nas-port", DataType: DataTypeInteger},
		{ID: 12, Name: "ascend-fr-svc-addr", DataType: DataTypeString},
		{ID: 13, Name: "ascend-nas-port-format", DataType: DataTypeInteger},
		{ID: 14, Name: "ascend-atm-fault-management", DataType: DataTypeInteger},
		{ID: 15, Name: "ascend-atm-loopback-cell-loss", DataType: DataTypeInteger},
		{ID: 16, Name: "ascend-ckt-type", DataType: DataTypeInteger},
		{ID: 17, Name: "ascend-svc-enabled", DataType: DataTypeInteger},
		{
			ID:       18,
			Name:     "ascend-session-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"g.711-g.726-voice": 0,
				"g.711-fax":         1,
				"g.711-modem":       2,
				"g.726-voice":       3,
				"g.726-fax":         4,
				"g.726-modem":       5,
				"g.711-g.726-fax":   6,
				"g.711-g.726-modem": 7,
				"g.729-voice":       8,
				"g.729-fax":         9,
				"g.729-modem":       10,
			},
		},
		{ID: 19, Name: "ascend-h323-gatekeeper", DataType: DataTypeIPAddr},
		{ID: 20, Name: "ascend-global-call-id", DataType: DataTypeString},
		{ID: 21, Name: "ascend-h323-conference-id", DataType: DataTypeInteger},
		{ID: 22, Name: "ascend-h323-fegw-address", DataType: DataTypeIPAddr},
		{ID: 23, Name: "ascend-h323-dialed-time", DataType: DataTypeInteger},
		{ID: 24, Name: "ascend-dialed-number", DataType: DataTypeString},
		{ID: 25, Name: "ascend-inter-arrival-jitter", DataType: DataTypeInteger},
		{ID: 26, Name: "ascend-dropped-octets", DataType: DataTypeInteger},
		{ID: 27, Name: "ascend-dropped-packets", DataType: DataTypeInteger},
		{ID: 28, Name: "ascend-auth-delay", DataType: DataTypeInteger},
		{ID: 29, Name: "ascend-x25-pad-x3-profile", DataType: DataTypeInteger},
		{ID: 30, Name: "ascend-x25-pad-x3-parameters", DataType: DataTypeString},
		{ID: 31, Name: "ascend-tunnel-vrouter-name", DataType: DataTypeString},
		{ID: 32, Name: "ascend-x25-reverse-charging", DataType: DataTypeInteger},
		{ID: 33, Name: "ascend-x25-nui-prompt", DataType: DataTypeString},
		{ID: 34, Name: "ascend-x25-nui-password-prompt", DataType: DataTypeString},
		{ID: 35, Name: "ascend-x25-cug", DataType: DataTypeString},
		{ID: 36, Name: "ascend-x25-pad-alias-1", DataType: DataTypeString},
		{ID: 37, Name: "ascend-x25-pad-alias-2", DataType: DataTypeString},
		{ID: 38, Name: "ascend-x25-pad-alias-3", DataType: DataTypeString},
		{ID: 39, Name: "ascend-x25-x121-address", DataType: DataTypeString},
		{ID: 40, Name: "ascend-x25-nui", DataType: DataTypeString},
		{ID: 41, Name: "ascend-x25-rpoa", DataType: DataTypeString},
		{ID: 42, Name: "ascend-x25-pad-prompt", DataType: DataTypeString},
		{ID: 43, Name: "ascend-x25-pad-banner", DataType: DataTypeString},
		{ID: 44, Name: "ascend-x25-profile-name", DataType: DataTypeString},
		{ID: 45, Name: "ascend-recv-name", DataType: DataTypeString},
		{ID: 46, Name: "ascend-bi-directional-auth", DataType: DataTypeInteger},
		{ID: 47, Name: "ascend-mtu", DataType: DataTypeInteger},
		{
			ID:       48,
			Name:     "ascend-call-direction",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"incoming": 0,
				"outgoing": 1,
			},
		},
		{
			ID:       49,
			Name:     "ascend-service-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"analog-modem":        0,
				"digital-modem":       1,
				"digital-modem-128k":  2,
				"digital-v.110":       3,
				"digital-v.120":       4,
				"digital-v.110-128k":  5,
				"digital-v.120-128k":  6,
				"digital-leased-line": 7,
				"digital-t1":          8,
				"digital-t3":          9,
				"digital-e1":          10,
				"digital-e3":          11,
				"voice-over-ip":       12,
				"digital-v.35":        13,
				"digital-x.25":        14,
				"digital-frame-relay": 15,
				"digital-atm":         16,
				"isdn":                17,
				"isdn-128k":           18,
				"isdn-384k":           19,
				"isdn-1536k":          20,
				"isdn-1920k":          21,
				"digital-hdlc":        22,
				"digital-ppp":         23,
				"digital-mp":          24,
			},
		},
		{ID: 50, Name: "ascend-filter-required", DataType: DataTypeInteger},
		{ID: 51, Name: "ascend-traffic-shaper", DataType: DataTypeInteger},
		{ID: 52, Name: "ascend-access-intercept-lea", DataType: DataTypeString},
		{ID: 53, Name: "ascend-access-intercept-log", DataType: DataTypeString},
		{ID: 54, Name: "ascend-private-route-table-id", DataType: DataTypeString},
		{ID: 55, Name: "ascend-private-route-required", DataType: DataTypeInteger},
		{ID: 56, Name: "ascend-cache-refresh", DataType: DataTypeInteger},
		{ID: 57, Name: "ascend-cache-time", DataType: DataTypeInteger},
		{ID: 58, Name: "ascend-egress-enabled", DataType: DataTypeInteger},
		{ID: 59, Name: "ascend-qos-upstream", DataType: DataTypeString},
		{ID: 60, Name: "ascend-qos-downstream", DataType: DataTypeString},
		{ID: 61, Name: "ascend-atm-connect-vpi", DataType: DataTypeInteger},
		{ID: 62, Name: "ascend-atm-connect-vci", DataType: DataTypeInteger},
		{ID: 63, Name: "ascend-atm-connect-group", DataType: DataTypeInteger},
		{ID: 64, Name: "ascend-atm-group", DataType: DataTypeInteger},
		{ID: 65, Name: "ascend-ipx-header-compression", DataType: DataTypeInteger},
		{ID: 66, Name: "ascend-calling-id-type-of-num", DataType: DataTypeInteger},
		{ID: 67, Name: "ascend-calling-id-number-plan", DataType: DataTypeInteger},
		{ID: 68, Name: "ascend-calling-id-presentatn", DataType: DataTypeInteger},
		{ID: 69, Name: "ascend-calling-id-screening", DataType: DataTypeInteger},
		{ID: 70, Name: "ascend-bir-enable", DataType: DataTypeInteger},
		{ID: 71, Name: "ascend-bir-proxy", DataType: DataTypeInteger},
		{ID: 72, Name: "ascend-bir-bridge-group", DataType: DataTypeInteger},
		{ID: 73, Name: "ascend-ipsec-profile", DataType: DataTypeString},
		{ID: 74, Name: "ascend-pppoe-enable", DataType: DataTypeInteger},
		{ID: 75, Name: "ascend-bridge-non-pppoe", DataType: DataTypeInteger},
		{ID: 76, Name: "ascend-atm-direct", DataType: DataTypeInteger},
		{ID: 77, Name: "ascend-atm-direct-profile", DataType: DataTypeString},
		{ID: 78, Name: "ascend-client-primary-wins", DataType: DataTypeIPAddr},
		{ID: 79, Name: "ascend-client-secondary-wins", DataType: DataTypeIPAddr},
		{ID: 80, Name: "ascend-client-assign-wins", DataType: DataTypeInteger},
		{ID: 81, Name: "ascend-auth-type", DataType: DataTypeInteger},
		{ID: 82, Name: "ascend-port-redir-protocol", DataType: DataTypeInteger},
		{ID: 83, Name: "ascend-port-redir-portnum", DataType: DataTypeInteger},
		{ID: 84, Name: "ascend-port-redir-server", DataType: DataTypeIPAddr},
		{ID: 85, Name: "ascend-ip-pool-chaining", DataType: DataTypeInteger},
		{ID: 86, Name: "ascend-owner-ip-addr", DataType: DataTypeIPAddr},
		{ID: 87, Name: "ascend-ip-tos", DataType: DataTypeInteger},
		{ID: 88, Name: "ascend-ip-tos-precedence", DataType: DataTypeInteger},
		{ID: 89, Name: "ascend-ip-tos-apply-to", DataType: DataTypeInteger},
		{ID: 90, Name: "ascend-filter", DataType: DataTypeString},
		{ID: 91, Name: "ascend-telnet-profile", DataType: DataTypeString},
		{ID: 92, Name: "ascend-dsl-rate-type", DataType: DataTypeInteger},
		{ID: 93, Name: "ascend-redirect-number", DataType: DataTypeString},
		{ID: 94, Name: "ascend-atm-vpi", DataType: DataTypeInteger},
		{ID: 95, Name: "ascend-atm-vci", DataType: DataTypeInteger},
		{ID: 96, Name: "ascend-source-ip-check", DataType: DataTypeInteger},
		{ID: 97, Name: "ascend-dsl-rate-mode", DataType: DataTypeInteger},
		{ID: 98, Name: "ascend-dsl-upstream-limit", DataType: DataTypeInteger},
		{ID: 99, Name: "ascend-dsl-downstream-limit", DataType: DataTypeInteger},
		{ID: 100, Name: "ascend-dsl-cir-recv-limit", DataType: DataTypeInteger},
		{ID: 101, Name: "ascend-dsl-cir-xmit-limit", DataType: DataTypeInteger},
		{ID: 102, Name: "ascend-vrouter-name", DataType: DataTypeString},
		{ID: 103, Name: "ascend-source-auth", DataType: DataTypeString},
		{ID: 104, Name: "ascend-private-route", DataType: DataTypeString},
		{ID: 105, Name: "ascend-numbering-plan-id", DataType: DataTypeInteger},
		{ID: 106, Name: "ascend-fr-link-status-dlci", DataType: DataTypeInteger},
		{ID: 107, Name: "ascend-calling-subaddress", DataType: DataTypeString},
		{ID: 108, Name: "ascend-callback-delay", DataType: DataTypeInteger},
		{ID: 109, Name: "ascend-endpoint-disc", DataType: DataTypeString},
		{ID: 110, Name: "ascend-remote-fw", DataType: DataTypeString},
		{ID: 111, Name: "ascend-multicast-gleave-delay", DataType: DataTypeInteger},
		{ID: 112, Name: "ascend-cbcp-enable", DataType: DataTypeInteger},
		{ID: 113, Name: "ascend-cbcp-mode", DataType: DataTypeInteger},
		{ID: 114, Name: "ascend-cbcp-delay", DataType: DataTypeInteger},
		{ID: 115, Name: "ascend-cbcp-trunk-group", DataType: DataTypeInteger},
		{ID: 116, Name: "ascend-appletalk-route", DataType: DataTypeString},
		{ID: 117, Name: "ascend-appletalk-peer-mode", DataType: DataTypeInteger},
		{ID: 118, Name: "ascend-route-appletalk", DataType: DataTypeInteger},
		{ID: 119, Name: "ascend-fcp-parameter", DataType: DataTypeString},
		{ID: 120, Name: "ascend-modem-portno", DataType: DataTypeInteger},
		{ID: 121, Name: "ascend-modem-slotno", DataType: DataTypeInteger},
		{ID: 122, Name: "ascend-modem-shelfno", DataType: DataTypeInteger},
		{ID: 123, Name: "ascend-call-attempt-limit", DataType: DataTypeInteger},
		{ID: 124, Name: "ascend-call-block-duration", DataType: DataTypeInteger},
		{ID: 125, Name: "ascend-maximum-call-duration", DataType: DataTypeInteger},
		{ID: 126, Name: "ascend-temporary-rtes", DataType: DataTypeInteger},
		{ID: 127, Name: "ascend-tunneling-protocol", DataType: DataTypeInteger},
		{ID: 128, Name: "ascend-shared-profile-enable", DataType: DataTypeInteger},
		{ID: 129, Name: "ascend-primary-home-agent", DataType: DataTypeString},
		{ID: 130, Name: "ascend-secondary-home-agent", DataType: DataTypeString},
		{ID: 131, Name: "ascend-dialout-allowed", DataType: DataTypeInteger},
		{ID: 132, Name: "ascend-client-gateway", DataType: DataTypeIPAddr},
		{ID: 133, Name: "ascend-bacp-enable", DataType: DataTypeInteger},
		{ID: 134, Name: "ascend-dhcp-maximum-leases", DataType: DataTypeInteger},
		{ID: 135, Name: "ascend-client-primary-dns", DataType: DataTypeIPAddr},
		{ID: 136, Name: "ascend-client-secondary-dns", DataType: DataTypeIPAddr},
		{ID: 137, Name: "ascend-client-assign-dns", DataType: DataTypeInteger},
		{ID: 138, Name: "ascend-user-acct-type", DataType: DataTypeInteger},
		{ID: 139, Name: "ascend-user-acct-host", DataType: DataTypeIPAddr},
		{ID: 140, Name: "ascend-user-acct-port", DataType: DataTypeInteger},
		{ID: 141, Name: "ascend-user-acct-key", DataType: DataTypeString},
		{ID: 142, Name: "ascend-user-acct-base", DataType: DataTypeInteger},
		{ID: 143, Name: "ascend-user-acct-time", DataType: DataTypeInteger},
		{ID: 144, Name: "ascend-assign-ip-client", DataType: DataTypeIPAddr},
		{ID: 145, Name: "ascend-assign-ip-server", DataType: DataTypeIPAddr},
		{ID: 146, Name: "ascend-assign-ip-global-pool", DataType: DataTypeString},
		{ID: 147, Name: "ascend-dhcp-reply", DataType: DataTypeInteger},
		{ID: 148, Name: "ascend-dhcp-pool-number", DataType: DataTypeInteger},
		{ID: 149, Name: "ascend-expect-callback", DataType: DataTypeInteger},
		{ID: 150, Name: "ascend-event-type", DataType: DataTypeInteger},
		{ID: 151, Name: "ascend-session-svr-key", DataType: DataTypeString},
		{ID: 152, Name: "ascend-multicast-rate-limit", DataType: DataTypeInteger},
		{ID: 153, Name: "ascend-if-netmask", DataType: DataTypeIPAddr},
		{ID: 154, Name: "ascend-remote-addr", DataType: DataTypeIPAddr},
		{ID: 155, Name: "ascend-multicast-client", DataType: DataTypeInteger},
		{ID: 156, Name: "ascend-fr-circuit-name", DataType: DataTypeString},
		{ID: 157, Name: "ascend-fr-linkup", DataType: DataTypeInteger},
		{ID: 158, Name: "ascend-fr-nailed-grp", DataType: DataTypeInteger},
		{ID: 159, Name: "ascend-fr-type", DataType: DataTypeInteger},
		{ID: 160, Name: "ascend-fr-link-mgt", DataType: DataTypeInteger},
		{ID: 161, Name: "ascend-fr-n391", DataType: DataTypeInteger},
		{ID: 162, Name: "ascend-fr-dce-n392", DataType: DataTypeInteger},
		{ID: 163, Name: "ascend-fr-dte-n392", DataType: DataTypeInteger},
		{ID: 164, Name: "ascend-fr-dce-n393", DataType: DataTypeInteger},
		{ID: 165, Name: "ascend-fr-dte-n393", DataType: DataTypeInteger},
		{ID: 166, Name: "ascend-fr-t391", DataType: DataTypeInteger},
		{ID: 167, Name: "ascend-fr-t392", DataType: DataTypeInteger},
		{ID: 168, Name: "ascend-bridge-address", DataType: DataTypeString},
		{ID: 169, Name: "ascend-ts-idle-limit", DataType: DataTypeInteger},
		{ID: 170, Name: "ascend-ts-idle-mode", DataType: DataTypeInteger},
		{ID: 171, Name: "ascend-dba-monitor", DataType: DataTypeInteger},
		{ID: 172, Name: "ascend-base-channel-count", DataType: DataTypeInteger},
		{ID: 173, Name: "ascend-minimum-channels", DataType: DataTypeInteger},
		{ID: 174, Name: "ascend-ipx-route", DataType: DataTypeString},
		{ID: 175, Name: "ascend-ft1-caller", DataType: DataTypeInteger},
		{ID: 176, Name: "ascend-backup", DataType: DataTypeString},
		{
			ID:       177,
			Name:     "ascend-call-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"analog-modem":  0,
				"digital-modem": 1,
				"digital-v.110": 2,
				"digital-v.120": 3,
				"isdn":          4,
				"x.25":          5,
				"digital-t1":    6,
				"digital-56k":   7,
				"digital-64k":   8,
				"digital-128k":  9,
				"digital-192k":  10,
				"digital-256k":  11,
				"digital-320k":  12,
				"digital-384k":  13,
			},
		},
		{ID: 178, Name: "ascend-group", DataType: DataTypeString},
		{ID: 179, Name: "ascend-fr-dlci", DataType: DataTypeInteger},
		{ID: 180, Name: "ascend-fr-profile-name", DataType: DataTypeString},
		{ID: 181, Name: "ascend-ara-pw", DataType: DataTypeString},
		{ID: 182, Name: "ascend-ipx-node-addr", DataType: DataTypeString},
		{ID: 183, Name: "ascend-home-agent-ip-addr", DataType: DataTypeIPAddr},
		{ID: 184, Name: "ascend-home-agent-password", DataType: DataTypeString},
		{ID: 185, Name: "ascend-home-network-name", DataType: DataTypeString},
		{ID: 186, Name: "ascend-home-agent-udp-port", DataType: DataTypeInteger},
		{ID: 187, Name: "ascend-multilink-id", DataType: DataTypeInteger},
		{ID: 188, Name: "ascend-num-in-multilink", DataType: DataTypeInteger},
		{ID: 189, Name: "ascend-first-dest", DataType: DataTypeIPAddr},
		{ID: 190, Name: "ascend-pre-input-octets", DataType: DataTypeInteger},
		{ID: 191, Name: "ascend-pre-output-octets", DataType: DataTypeInteger},
		{ID: 192, Name: "ascend-pre-input-packets", DataType: DataTypeInteger},
		{ID: 193, Name: "ascend-pre-output-packets", DataType: DataTypeInteger},
		{ID: 194, Name: "ascend-maximum-time", DataType: DataTypeInteger},
		{
			ID:       195,
			Name:     "ascend-disconnect-cause",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"none":                         0,
				"local-disconnect":             1,
				"rlogin-remote-disconnect":     2,
				"ppp-lcp-remote-disconnect":    3,
				"ppp-lcp-local-disconnect":     4,
				"ppp-pap-auth-failed":          5,
				"ppp-chap-auth-failed":         6,
				"ppp-remote-terminate":         7,
				"ppp-remote-close-event":       8,
				"ncp-remote-terminate":         9,
				"ncp-remote-close-event":       10,
				"radius-request-timeout":       11,
				"primary-radius-server-down":   12,
				"secondary-radius-server-down": 13,
				"telnet-remote-disconnect":     14,
				"administrative-disconnect":    15,
				"callback-request":             16,
				"invalid-phone-number":         17,
				"fax-connection":               18,
				"modem-handshake-failed":       19,
				"lost-carrier":                 20,
				"dcd-on-timeout":               21,
				"user-error":                   22,
				"idle-timeout":                 23,
				"session-timeout":              24,
				"host-request":                 25,
				"call-back-request":            26,
				"trunk-down":                   27,
				"preempted":                    28,
				"physical-state-change":        29,
				"dest-out-of-order":            30,
				"remote-user-hangup":           31,
				"ppp-lqm-failure":              32,
				"dte-ring-limit":               33,
				"auto-logout-limit":            34,
				"t1-quiesce":                   35,
				"call-duration":                36,
				"vpn-lcp-failure":              37,
				"vpn-auth-failure":             38,
				"vpn-lqm-failure":              39,
				"v110-timeout":                 40,
			},
		},
		{
			ID:       196,
			Name:     "ascend-connect-progress",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"no-progress":            0,
				"call-up":                1,
				"call-down":              2,
				"alarms-cleared":         3,
				"call-setup":             4,
				"call-alerting":          5,
				"call-connect":           6,
				"incoming-call":          7,
				"initial-call-proc":      8,
				"activation-request":     9,
				"activation-complete":    10,
				"v110-on":                11,
				"v110-off":               12,
				"v120-on":                13,
				"v120-off":               14,
				"leased-line-on":         15,
				"leased-line-off":        16,
				"raw-tcp-session":        17,
				"telnet-session":         18,
				"rlogin-session":         19,
				"rlogin-host-connected":  20,
				"ppp-lcp-open":           21,
				"ppp-lcp-not-open":       22,
				"ppp-authentication":     23,
				"ppp-auth-pending":       24,
				"ppp-ncp-open":           25,
				"ppp-ncp-not-open":       26,
				"lan-session-up":         27,
				"lan-session-down":       28,
				"host-connected":         29,
				"host-disconnected":      30,
				"t1-in-service":          31,
				"t1-out-of-service":      32,
				"modem-connected":        33,
				"modem-disconnected":     34,
				"cd-on":                  35,
				"cd-off":                 36,
				"t1-channel-activated":   37,
				"t1-channel-deactivated": 38,
				"link-compressed":        39,
				"link-decompressed":      40,
			},
		},
		{ID: 197, Name: "ascend-data-rate", DataType: DataTypeInteger},
		{ID: 198, Name: "ascend-presession-time", DataType: DataTypeInteger},
		{ID: 199, Name: "ascend-token-idle", DataType: DataTypeInteger},
		{ID: 200, Name: "ascend-token-immediate", DataType: DataTypeInteger},
		{ID: 201, Name: "ascend-require-auth", DataType: DataTypeInteger},
		{ID: 202, Name: "ascend-number-sessions", DataType: DataTypeString},
		{ID: 203, Name: "ascend-authen-alias", DataType: DataTypeString},
		{ID: 204, Name: "ascend-token-expiry", DataType: DataTypeInteger},
		{ID: 205, Name: "ascend-menu-selector", DataType: DataTypeString},
		{ID: 206, Name: "ascend-menu-item", DataType: DataTypeString},
		{ID: 207, Name: "ascend-pw-warntime", DataType: DataTypeInteger},
		{ID: 208, Name: "ascend-pw-lifetime", DataType: DataTypeInteger},
		{ID: 209, Name: "ascend-ip-direct", DataType: DataTypeIPAddr},
		{ID: 210, Name: "ascend-ppp-vj-slot-comp", DataType: DataTypeInteger},
		{ID: 211, Name: "ascend-ppp-vj-1172", DataType: DataTypeInteger},
		{ID: 212, Name: "ascend-ppp-async-map", DataType: DataTypeInteger},
		{ID: 213, Name: "ascend-third-prompt", DataType: DataTypeString},
		{ID: 214, Name: "ascend-send-secret", DataType: DataTypeString, Encryption: EncryptionAscendSecret},
		{ID: 215, Name: "ascend-receive-secret", DataType: DataTypeString, Encryption: EncryptionAscendSecret},
		{ID: 216, Name: "ascend-ipx-peer-mode", DataType: DataTypeInteger},
		{ID: 217, Name: "ascend-ip-pool-definition", DataType: DataTypeString},
		{ID: 218, Name: "ascend-assign-ip-pool", DataType: DataTypeInteger},
		{ID: 219, Name: "ascend-fr-direct", DataType: DataTypeInteger},
		{ID: 220, Name: "ascend-fr-direct-profile", DataType: DataTypeString},
		{ID: 221, Name: "ascend-fr-direct-dlci", DataType: DataTypeInteger},
		{ID: 222, Name: "ascend-handle-ipx", DataType: DataTypeInteger},
		{ID: 223, Name: "ascend-netware-timeout", DataType: DataTypeInteger},
		{ID: 224, Name: "ascend-ipx-alias", DataType: DataTypeInteger},
		{ID: 225, Name: "ascend-metric", DataType: DataTypeInteger},
		{ID: 226, Name: "ascend-pri-number-type", DataType: DataTypeInteger},
		{ID: 227, Name: "ascend-dial-number", DataType: DataTypeString},
		{ID: 228, Name: "ascend-route-ip", DataType: DataTypeInteger},
		{ID: 229, Name: "ascend-route-ipx", DataType: DataTypeInteger},
		{ID: 230, Name: "ascend-bridge", DataType: DataTypeInteger},
		{ID: 231, Name: "ascend-send-auth", DataType: DataTypeInteger},
		{ID: 232, Name: "ascend-send-passwd", DataType: DataTypeString},
		{ID: 233, Name: "ascend-link-compression", DataType: DataTypeInteger},
		{ID: 234, Name: "ascend-target-util", DataType: DataTypeInteger},
		{ID: 235, Name: "ascend-maximum-channels", DataType: DataTypeInteger},
		{ID: 236, Name: "ascend-inc-channel-count", DataType: DataTypeInteger},
		{ID: 237, Name: "ascend-dec-channel-count", DataType: DataTypeInteger},
		{ID: 238, Name: "ascend-seconds-of-history", DataType: DataTypeInteger},
		{ID: 239, Name: "ascend-history-weigh-type", DataType: DataTypeInteger},
		{ID: 240, Name: "ascend-add-seconds", DataType: DataTypeInteger},
		{ID: 241, Name: "ascend-remove-seconds", DataType: DataTypeInteger},
		{ID: 242, Name: "ascend-data-filter", DataType: DataTypeABinary},
		{ID: 243, Name: "ascend-call-filter", DataType: DataTypeABinary},
		{ID: 244, Name: "ascend-idle-limit", DataType: DataTypeInteger},
		{ID: 245, Name: "ascend-preempt-limit", DataType: DataTypeInteger},
		{ID: 246, Name: "ascend-callback", DataType: DataTypeInteger},
		{
			ID:       247,
			Name:     "ascend-data-svc",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"switched-voice-bearer": 0,
				"switched-56kr":         1,
				"switched-64kr":         2,
				"switched-56k":          3,
				"switched-64k":          4,
				"switched-128k":         5,
				"switched-192k":         6,
				"switched-256k":         7,
				"switched-320k":         8,
				"switched-384k":         9,
				"switched-448k":         10,
				"switched-512k":         11,
				"switched-576k":         12,
				"switched-640k":         13,
				"switched-704k":         14,
				"switched-768k":         15,
				"switched-832k":         16,
				"switched-896k":         17,
				"switched-960k":         18,
				"switched-1024k":        19,
				"switched-1088k":        20,
				"switched-1152k":        21,
				"switched-1216k":        22,
				"switched-1280k":        23,
				"switched-1344k":        24,
				"switched-1408k":        25,
				"switched-1472k":        26,
				"switched-1536k":        27,
				"switched-1600k":        28,
				"switched-1664k":        29,
				"switched-1728k":        30,
				"switched-1792k":        31,
				"switched-1856k":        32,
				"switched-1920k":        33,
				"switched-multirate":    34,
				"switched-v.110":        35,
				"switched-v.120":        36,
				"switched-x.75":         37,
				"switched-ao-di":        38,
				"switched-modem":        39,
				"switched-fax":          40,
				"switched-piafs":        41,
				"switched-btx":          42,
				"leased-line":           43,
				"nailed-56kr":           44,
				"nailed-64k":            45,
				"nailed-128k":           46,
				"nailed-192k":           47,
				"nailed-256k":           48,
				"nailed-320k":           49,
				"nailed-384k":           50,
				"nailed-448k":           51,
				"nailed-512k":           52,
				"nailed-576k":           53,
				"nailed-640k":           54,
				"nailed-704k":           55,
				"nailed-768k":           56,
				"nailed-832k":           57,
				"nailed-896k":           58,
				"nailed-960k":           59,
				"nailed-1024k":          60,
				"nailed-1088k":          61,
				"nailed-1152k":          62,
				"nailed-1216k":          63,
				"nailed-1280k":          64,
				"nailed-1344k":          65,
				"nailed-1408k":          66,
				"nailed-1472k":          67,
				"nailed-1536k":          68,
				"switched-fr":           69,
			},
		},
		{ID: 248, Name: "ascend-force-56", DataType: DataTypeInteger},
		{ID: 249, Name: "ascend-billing-number", DataType: DataTypeString},
		{ID: 250, Name: "ascend-call-by-call", DataType: DataTypeInteger},
		{ID: 251, Name: "ascend-transit-number", DataType: DataTypeString},
		{ID: 252, Name: "ascend-host-info", DataType: DataTypeString},
		{ID: 253, Name: "ascend-ppp-address", DataType: DataTypeIPAddr},
		{ID: 254, Name: "ascend-mpp-idle-percent", DataType: DataTypeInteger},
		{ID: 255, Name: "ascend-xmit-rate", DataType: DataTypeInteger},
	},
}
