package goradius

// JuniperVendorDefinition contains the Juniper vendor definition with all its attributes
var JuniperVendorDefinition = &VendorDefinition{
	ID:   2636,
	Name: "juniper",
	Attributes: []*AttributeDefinition{
		{ID: 1, Name: "juniper-local-user-name", DataType: DataTypeString},
		{ID: 2, Name: "juniper-allow-commands", DataType: DataTypeString, Multiline: true},
		{ID: 3, Name: "juniper-deny-commands", DataType: DataTypeString, Multiline: true},
		{ID: 4, Name: "juniper-allow-configuration", DataType: DataTypeString, Multiline: true},
		{ID: 5, Name: "juniper-deny-configuration", DataType: DataTypeString, Multiline: true},
		{ID: 8, Name: "juniper-interactive-command", DataType: DataTypeString},
		{ID: 9, Name: "juniper-configuration-change", DataType: DataTypeString},
		{ID: 10, Name: "juniper-user-permissions", DataType: DataTypeString, Multiline: true},
		{ID: 11, Name: "juniper-authentication-type", DataType: DataTypeString},
		{ID: 12, Name: "juniper-session-port", DataType: DataTypeInteger},
		{ID: 13, Name: "juniper-allow-configuration-regexps", DataType: DataTypeString, Multiline: true},
		{ID: 14, Name: "juniper-deny-configuration-regexps", DataType: DataTypeString, Multiline: true},
		{
			ID:       21,
			Name:     "juniper-ctp-group",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"read_only":        1,
				"admin":            2,
				"privileged_admin": 3,
				"auditor":          4,
			},
		},
		{
			ID:       22,
			Name:     "juniper-ctpview-app-group",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"net_view":     1,
				"net_admin":    2,
				"global_admin": 3,
			},
		},
		{
			ID:       23,
			Name:     "juniper-ctpview-os-group",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"web_manager":  1,
				"system_admin": 2,
				"auditor":      3,
			},
		},
		{ID: 31, Name: "juniper-primary-dns", DataType: DataTypeIPAddr},
		{ID: 32, Name: "juniper-primary-wins", DataType: DataTypeIPAddr},
		{ID: 33, Name: "juniper-secondary-dns", DataType: DataTypeIPAddr},
		{ID: 34, Name: "juniper-secondary-wins", DataType: DataTypeIPAddr},
		{ID: 35, Name: "juniper-interface-id", DataType: DataTypeString},
		{ID: 36, Name: "juniper-ip-pool-name", DataType: DataTypeString},
		{ID: 37, Name: "juniper-keep-alive", DataType: DataTypeInteger},
		{ID: 38, Name: "juniper-cos-traffic-control-profile", DataType: DataTypeString},
		{ID: 39, Name: "juniper-cos-parameter", DataType: DataTypeString},
		{ID: 40, Name: "juniper-encapsulation-overhead", DataType: DataTypeInteger},
		{ID: 41, Name: "juniper-cell-overhead", DataType: DataTypeInteger},
		{ID: 42, Name: "juniper-tx-connect-speed", DataType: DataTypeInteger},
		{ID: 43, Name: "juniper-rx-connect-speed", DataType: DataTypeInteger},
		{ID: 44, Name: "juniper-firewall-filter-name", DataType: DataTypeString},
		{ID: 45, Name: "juniper-policer-parameter", DataType: DataTypeString},
		{ID: 46, Name: "juniper-local-group-name", DataType: DataTypeString},
		{ID: 47, Name: "juniper-local-interface", DataType: DataTypeString},
		{ID: 48, Name: "juniper-switching-filter", DataType: DataTypeString},
		{ID: 49, Name: "juniper-voip-vlan", DataType: DataTypeString},
		{ID: 50, Name: "juniper-cwa-redirect", DataType: DataTypeString},
		{ID: 52, Name: "juniper-av-pair", DataType: DataTypeString},
	},
}
