package goradius

// ERXVendorDefinition contains the ERX vendor definition with all its attributes.
// Usage masks are transcribed from the Juniper AAA Service Framework tables
// (access, accounting, CoA, and Disconnect message support); attributes without
// a mask have no documented placement and stay unrestricted.
var ERXVendorDefinition = &VendorDefinition{
	ID:   4874,
	Name: "erx",
	Attributes: []*AttributeDefinition{
		{
			ID:       1,
			Name:     "erx-virtual-router-name",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccessAccept | UsageAccountingRequest | UsageCoARequest,
		},
		{ID: 2, Name: "erx-address-pool-name", DataType: DataTypeString},
		{ID: 3, Name: "erx-local-loopback-interface", DataType: DataTypeString},
		{
			ID:       4,
			Name:     "erx-primary-dns",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       5,
			Name:     "erx-secondary-dns",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       6,
			Name:     "erx-primary-wins",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       7,
			Name:     "erx-secondary-wins",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       8,
			Name:     "erx-tunnel-virtual-router",
			DataType: DataTypeString,
			HasTag:   true,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       9,
			Name:     "erx-tunnel-password",
			DataType: DataTypeString,
			HasTag:   true,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       10,
			Name:     "erx-ingress-policy-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       11,
			Name:     "erx-egress-policy-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       12,
			Name:     "erx-ingress-statistics",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
			Values: map[string]uint32{
				"disable": 0,
				"enable":  1,
			},
		},
		{
			ID:       13,
			Name:     "erx-egress-statistics",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
			Values: map[string]uint32{
				"disable": 0,
				"enable":  1,
			},
		},
		{
			ID:       14,
			Name:     "erx-atm-service-category",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
			Values: map[string]uint32{
				"ubr":    1,
				"ubrpcr": 2,
				"nrtvbr": 3,
				"cbr":    4,
			},
		},
		{
			ID:       15,
			Name:     "erx-atm-pcr",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       16,
			Name:     "erx-atm-scr",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       17,
			Name:     "erx-atm-mbs",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       18,
			Name:     "erx-cli-initial-access-level",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       19,
			Name:     "erx-cli-allow-all-vr-access",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
			Values: map[string]uint32{
				"disable": 0,
				"enable":  1,
			},
		},
		{
			ID:       20,
			Name:     "erx-alternate-cli-access-level",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       21,
			Name:     "erx-alternate-cli-vrouter-name",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       22,
			Name:     "erx-sa-validate",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disable": 0,
				"enable":  1,
			},
		},
		{
			ID:       23,
			Name:     "erx-igmp-enable",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"disable": 0,
				"enable":  1,
			},
		},
		{
			ID:       24,
			Name:     "erx-pppoe-description",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       25,
			Name:     "erx-redirect-vr-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{ID: 26, Name: "erx-qos-profile-name", DataType: DataTypeString},
		{ID: 27, Name: "erx-pppoe-max-sessions", DataType: DataTypeInteger},
		{ID: 28, Name: "erx-pppoe-url", DataType: DataTypeString},
		{
			ID:       29,
			Name:     "erx-qos-profile-interface-type",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
			Values: map[string]uint32{
				"ip":          1,
				"atm":         2,
				"hdlc":        3,
				"ethernet":    4,
				"server-port": 5,
				"atm-1483":    6,
				"frame-relay": 7,
				"mpls-minor":  8,
				"cbf":         9,
				"ip-tunnel":   10,
				"vlan-sub":    11,
				"pppoe-sub":   12,
			},
		},
		{
			ID:       30,
			Name:     "erx-tunnel-nas-port-method",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"none":       0,
				"cisco-clid": 1,
			},
		},
		{
			ID:       31,
			Name:     "erx-service-bundle",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       32,
			Name:     "erx-tunnel-tos",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       33,
			Name:     "erx-tunnel-maximum-sessions",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       34,
			Name:     "erx-framed-ip-route-tag",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{ID: 35, Name: "erx-dial-out-number", DataType: DataTypeString},
		{ID: 36, Name: "erx-ppp-username", DataType: DataTypeString},
		{ID: 37, Name: "erx-ppp-password", DataType: DataTypeString},
		{
			ID:       38,
			Name:     "erx-ppp-auth-protocol",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"none":     0,
				"pap":      1,
				"chap":     2,
				"pap-chap": 3,
				"chap-pap": 4,
			},
		},
		{ID: 39, Name: "erx-minimum-bps", DataType: DataTypeInteger},
		{ID: 40, Name: "erx-maximum-bps", DataType: DataTypeInteger},
		{
			ID:       41,
			Name:     "erx-bearer-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"none":    0,
				"analog":  1,
				"digital": 2,
			},
		},
		{
			ID:       42,
			Name:     "erx-input-gigapkts",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       43,
			Name:     "erx-output-gigapkts",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{ID: 44, Name: "erx-tunnel-interface-id", DataType: DataTypeString},
		{ID: 45, Name: "erx-ipv6-virtual-router", DataType: DataTypeString},
		{ID: 46, Name: "erx-ipv6-local-interface", DataType: DataTypeString},
		{
			ID:       47,
			Name:     "erx-ipv6-primary-dns",
			DataType: DataTypeIPv6Addr,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       48,
			Name:     "erx-ipv6-secondary-dns",
			DataType: DataTypeIPv6Addr,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       49,
			Name:     "sdx-service-name",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       50,
			Name:     "sdx-session-volume-quota",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       51,
			Name:     "sdx-tunnel-disconnect-cause-info",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{ID: 52, Name: "erx-radius-client-address", DataType: DataTypeIPAddr},
		{ID: 53, Name: "erx-service-description", DataType: DataTypeString},
		{ID: 54, Name: "erx-l2tp-recv-window-size", DataType: DataTypeInteger},
		{
			ID:       55,
			Name:     "erx-dhcp-options",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       56,
			Name:     "erx-dhcp-mac-addr",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       57,
			Name:     "erx-dhcp-gi-address",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:         58,
			Name:       "erx-li-action",
			DataType:   DataTypeInteger,
			Usage:      UsageAccessAccept | UsageCoARequest,
			Encryption: EncryptionTunnelPassword,
			Values: map[string]uint32{
				"off":  0,
				"on":   1,
				"noop": 2,
			},
		},
		{
			ID:         59,
			Name:       "erx-med-dev-handle",
			DataType:   DataTypeOctets,
			Encryption: EncryptionTunnelPassword,
			Usage:      UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:         60,
			Name:       "erx-med-ip-address",
			DataType:   DataTypeIPAddr,
			Encryption: EncryptionTunnelPassword,
			Usage:      UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:         61,
			Name:       "erx-med-port-number",
			DataType:   DataTypeInteger,
			Encryption: EncryptionTunnelPassword,
			Usage:      UsageAccessAccept | UsageCoARequest,
		},
		{ID: 62, Name: "erx-mlppp-bundle-name", DataType: DataTypeString},
		{
			ID:       63,
			Name:     "erx-interface-desc",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       64,
			Name:     "erx-tunnel-group",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       65,
			Name:     "erx-service-activate",
			DataType: DataTypeString,
			HasTag:   true,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:       66,
			Name:     "erx-service-deactivate",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:       67,
			Name:     "erx-service-volume",
			DataType: DataTypeInteger,
			HasTag:   true,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:       68,
			Name:     "erx-service-timeout",
			DataType: DataTypeInteger,
			HasTag:   true,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:       69,
			Name:     "erx-service-statistics",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept | UsageCoARequest,
			HasTag:   true,
			Values: map[string]uint32{
				"disabled":    0,
				"time":        1,
				"time-volume": 2,
			},
		},
		{
			ID:       70,
			Name:     "erx-df-bit",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"dont-ignore-df-bit": 0,
				"ignore-df-bit":      1,
			},
		},
		{
			ID:       71,
			Name:     "erx-igmp-access-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       72,
			Name:     "erx-igmp-access-src-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{ID: 73, Name: "erx-igmp-oif-map-name", DataType: DataTypeString},
		{
			ID:       74,
			Name:     "erx-mld-access-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       75,
			Name:     "erx-mld-access-src-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{ID: 76, Name: "erx-mld-oif-map-name", DataType: DataTypeString},
		{
			ID:       77,
			Name:     "erx-mld-version",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"v1": 1,
				"v2": 2,
			},
		},
		{
			ID:       78,
			Name:     "erx-igmp-version",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"v1": 1,
				"v2": 2,
				"v3": 3,
			},
		},
		{ID: 79, Name: "erx-ip-mcast-adm-bw-limit", DataType: DataTypeInteger},
		{ID: 80, Name: "erx-ipv6-mcast-adm-bw-limit", DataType: DataTypeInteger},
		{ID: 81, Name: "erx-l2c-access-loop-parameters", DataType: DataTypeString},
		{ID: 82, Name: "erx-qos-parameters", DataType: DataTypeString},
		{
			ID:       83,
			Name:     "erx-service-session",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       84,
			Name:     "erx-mobile-ip-algorithm",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       85,
			Name:     "erx-mobile-ip-spi",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       86,
			Name:     "erx-mobile-ip-key",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       87,
			Name:     "erx-mobile-ip-replay",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       88,
			Name:     "erx-mobile-ip-access-control",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       89,
			Name:     "erx-mobile-ip-lifetime",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       90,
			Name:     "erx-l2tp-resynch-method",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disable":                     0,
				"failover":                    1,
				"silent-failover":             2,
				"failover-with-silent-backup": 3,
			},
		},
		{
			ID:       91,
			Name:     "erx-tunnel-switch-profile",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       92,
			Name:     "erx-l2c-up-stream-data",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       93,
			Name:     "erx-l2c-down-stream-data",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       94,
			Name:     "erx-tunnel-tx-speed-method",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"static-layer2":  1,
				"dynamic-layer2": 2,
				"qos":            3,
				"actual":         4,
			},
		},
		{ID: 95, Name: "erx-igmp-query-interval", DataType: DataTypeInteger},
		{ID: 96, Name: "erx-igmp-max-resp-time", DataType: DataTypeInteger},
		{
			ID:       97,
			Name:     "erx-igmp-immediate-leave",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{ID: 98, Name: "erx-mld-query-interval", DataType: DataTypeInteger},
		{ID: 99, Name: "erx-mld-max-resp-time", DataType: DataTypeInteger},
		{
			ID:       100,
			Name:     "erx-mld-immediate-leave",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       101,
			Name:     "erx-ip-block-multicast",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       102,
			Name:     "erx-igmp-explicit-tracking",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       103,
			Name:     "erx-igmp-no-tracking-v2-grps",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       104,
			Name:     "erx-mld-explicit-tracking",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       105,
			Name:     "erx-mld-no-tracking-v1-grps",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       106,
			Name:     "erx-ipv6-ingress-policy-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       107,
			Name:     "erx-ipv6-egress-policy-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       108,
			Name:     "erx-cos-shaping-pmt-type",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:       109,
			Name:     "erx-dhcp-guided-relay-server",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       110,
			Name:     "erx-acc-loop-cir-id",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       111,
			Name:     "erx-acc-aggr-cir-id-bin",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       112,
			Name:     "erx-acc-aggr-cir-id-asc",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       113,
			Name:     "erx-act-data-rate-up",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       114,
			Name:     "erx-act-data-rate-dn",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       115,
			Name:     "erx-min-data-rate-up",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       116,
			Name:     "erx-min-data-rate-dn",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       117,
			Name:     "erx-att-data-rate-up",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       118,
			Name:     "erx-att-data-rate-dn",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       119,
			Name:     "erx-max-data-rate-up",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       120,
			Name:     "erx-max-data-rate-dn",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       121,
			Name:     "erx-min-lp-data-rate-up",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       122,
			Name:     "erx-min-lp-data-rate-dn",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       123,
			Name:     "erx-max-interlv-delay-up",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       124,
			Name:     "erx-act-interlv-delay-up",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       125,
			Name:     "erx-max-interlv-delay-dn",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       126,
			Name:     "erx-act-interlv-delay-dn",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       127,
			Name:     "erx-dsl-line-state",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
			Values: map[string]uint32{
				"showtime": 1,
				"idle":     2,
				"silent":   3,
			},
		},
		{
			ID:       128,
			Name:     "erx-dsl-type",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
			Values: map[string]uint32{
				"adsl1":     1,
				"adsl2":     2,
				"adsl2plus": 3,
				"vdsl1":     4,
				"vdsl2":     5,
				"sdsl":      6,
				"unknown":   7,
			},
		},
		{ID: 129, Name: "erx-ipv6-ndra-prefix", DataType: DataTypeIPv6Prefix},
		{
			ID:       130,
			Name:     "erx-qos-set-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},

		// Junos OS Evolved per-queue statistics; JunosE left these IDs unassigned
		// (Juniper AAA Service Framework VSA table)
		{ID: 131, Name: "erx-queue-2-output-gigapackets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 132, Name: "erx-queue-2-output-packets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 133, Name: "erx-queue-3-output-gigapackets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 134, Name: "erx-queue-3-output-packets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 135, Name: "erx-queue-4-output-gigapackets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 136, Name: "erx-queue-4-output-packets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 137, Name: "erx-queue-5-output-gigapackets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 138, Name: "erx-queue-5-output-packets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 139, Name: "erx-queue-6-output-gigapackets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{
			ID:       140,
			Name:     "erx-service-acct-interval",
			DataType: DataTypeInteger,
			HasTag:   true,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:       141,
			Name:     "erx-downstream-calc-rate",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       142,
			Name:     "erx-upstream-calc-rate",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       143,
			Name:     "erx-max-clients-per-interface",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       144,
			Name:     "erx-ppp-monitor-ingress-only",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{ID: 145, Name: "erx-queue-6-output-packets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{
			ID:       146,
			Name:     "erx-cos-scheduler-pmt-type",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{ID: 147, Name: "erx-backup-address-pool", DataType: DataTypeString},
		{ID: 149, Name: "erx-queue-7-output-gigapackets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 150, Name: "erx-icr-partition-id", DataType: DataTypeString},
		{
			ID:       151,
			Name:     "erx-ipv6-acct-input-octets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       152,
			Name:     "erx-ipv6-acct-output-octets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       153,
			Name:     "erx-ipv6-acct-input-packets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       154,
			Name:     "erx-ipv6-acct-output-packets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       155,
			Name:     "erx-ipv6-acct-input-gigawords",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       156,
			Name:     "erx-ipv6-acct-output-gigawords",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{ID: 157, Name: "erx-ipv6-ndra-pool-name", DataType: DataTypeString},
		{
			ID:       158,
			Name:     "erx-pppoe-padn",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       159,
			Name:     "erx-dhcp-option-82",
			DataType: DataTypeOctets,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       160,
			Name:     "erx-vlan-map-id",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       161,
			Name:     "erx-ipv6-delegated-pool-name",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       162,
			Name:     "erx-tx-connect-speed",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       163,
			Name:     "erx-rx-connect-speed",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       164,
			Name:     "erx-ipv4-release-control",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{ID: 165, Name: "erx-pcp-server-name", DataType: DataTypeString},
		{
			ID:       173,
			Name:     "erx-service-activate-type",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept | UsageCoARequest,
			HasTag:   true,
			Values: map[string]uint32{
				"dynamic":  1,
				"opscript": 1,
			},
		},
		{
			ID:       174,
			Name:     "erx-client-profile-name",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccessAccept,
		},
		{ID: 175, Name: "erx-redirect-gw-address", DataType: DataTypeIPAddr},
		{ID: 176, Name: "erx-apn-name", DataType: DataTypeString},
		{
			ID:       177,
			Name:     "erx-cos-shaping-rate",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{ID: 178, Name: "erx-action-reason", DataType: DataTypeString},
		{
			ID:       179,
			Name:     "erx-service-volume-gigawords",
			DataType: DataTypeInteger,
			HasTag:   true,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:       180,
			Name:     "erx-update-service",
			DataType: DataTypeString,
			HasTag:   true,
			Usage:    UsageCoARequest,
		},
		{
			ID:       181,
			Name:     "erx-dhcpv6-guided-relay-server",
			DataType: DataTypeIPv6Addr,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       182,
			Name:     "erx-acc-loop-remote-id",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       183,
			Name:     "erx-acc-loop-encap",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       184,
			Name:     "erx-inner-vlan-map-id",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       185,
			Name:     "erx-core-facing-interface",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{ID: 186, Name: "erx-pcp-port-map", DataType: DataTypeString},
		{ID: 187, Name: "erx-vcpe-lan-extension", DataType: DataTypeString},
		{
			ID:       188,
			Name:     "erx-vcpe-ipv4-offload",
			DataType: DataTypeString,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       189,
			Name:     "erx-dhcp-first-relay-ipv4-address",
			DataType: DataTypeIPAddr,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       190,
			Name:     "erx-dhcp-first-relay-ipv6-address",
			DataType: DataTypeIPv6Addr,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       191,
			Name:     "erx-input-interface-filter",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest | UsageCoARequest,
		},
		{
			ID:       192,
			Name:     "erx-output-interface-filter",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest | UsageAccountingRequest | UsageCoARequest,
		},
		{
			ID:       193,
			Name:     "erx-pim-enable",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       194,
			Name:     "erx-bulk-coa-transaction-id",
			DataType: DataTypeInteger,
			Usage:    UsageCoARequest,
		},
		{
			ID:       195,
			Name:     "erx-bulk-coa-identifier",
			DataType: DataTypeInteger,
			Usage:    UsageCoARequest,
		},
		{
			ID:       196,
			Name:     "erx-ipv4-input-service-set",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       197,
			Name:     "erx-ipv4-output-service-set",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       198,
			Name:     "erx-ipv4-input-service-filter",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       199,
			Name:     "erx-ipv4-output-service-filter",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       200,
			Name:     "erx-ipv6-input-service-set",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       201,
			Name:     "erx-ipv6-output-service-set",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       202,
			Name:     "erx-ipv6-input-service-filter",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       203,
			Name:     "erx-ipv6-output-service-filter",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       204,
			Name:     "erx-adv-pcef-profile-name",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       205,
			Name:     "erx-adv-pcef-rule-name",
			DataType: DataTypeString,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       206,
			Name:     "erx-re-authentication-catalyst",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"disabled":     0,
				"client-renew": 1,
			},
		},
		{
			ID:       207,
			Name:     "erx-dhcpv6-options",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest | UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       208,
			Name:     "erx-dhcp-header",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       209,
			Name:     "erx-dhcpv6-header",
			DataType: DataTypeOctets,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       210,
			Name:     "erx-acct-request-reason",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
			Values: map[string]uint32{
				"acct-start-ack":            1,
				"periodic":                  2,
				"ip-active":                 4,
				"ip-inactive":               8,
				"ipv6-active":               16,
				"ipv6-inactive":             32,
				"session-active":            64,
				"session-inactive":          128,
				"line-speed-change":         256,
				"address-assignment-change": 512,
				"coa-complete":              1024,
			},
		},
		{
			ID:       211,
			Name:     "erx-inner-tag-protocol-id",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       212,
			Name:     "erx-routing-services",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       213,
			Name:     "erx-interface-set-targeting-weight",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       214,
			Name:     "erx-interface-targeting-weight",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       216,
			Name:     "erx-hybrid-access-dsl-downstream-speed",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       217,
			Name:     "erx-hybrid-access-lte-downstream-speed",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
		},
		{
			ID:       218,
			Name:     "erx-connection-status-message",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:       219,
			Name:     "erx-pon-access-type",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
			Values: map[string]uint32{
				"other":    0,
				"gpon":     1,
				"xg-pon1":  2,
				"twdm-pon": 3,
				"xgs-pon":  4,
				"wdm-pon":  5,
				"unknown":  7,
			},
		},
		{
			ID:       220,
			Name:     "erx-ont-onu-average-data-rate-downstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       221,
			Name:     "erx-ont-onu-peak-data-rate-downstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       222,
			Name:     "erx-ont-onu-maximum-data-rate-upstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       223,
			Name:     "erx-ont-onu-assured-data-rate-upstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       224,
			Name:     "erx-pon-tree-maximum-data-rate-upstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       225,
			Name:     "erx-pon-tree-maximum-data-rate-downstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       226,
			Name:     "erx-expected-throughput-upstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       227,
			Name:     "erx-expected-throughput-downstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       228,
			Name:     "erx-attainable-expected-throughput-upstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       229,
			Name:     "erx-attainable-expected-throughput-downstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       230,
			Name:     "erx-gamma-data-rate-upstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       231,
			Name:     "erx-gamma-data-rate-downstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       232,
			Name:     "erx-attainable-gamma-data-rate-upstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},
		{
			ID:       233,
			Name:     "erx-attainable-gamma-data-rate-downstream",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
		},

		// Junos BNG attributes not present in the FreeRADIUS dictionary.
		// Source: Juniper AAA Service Framework table "Supported Juniper Networks VSAs",
		// https://www.juniper.net/documentation/us/en/software/junos/subscriber-mgmt-sessions/topics/topic-map/radius-std-attributes-vsas-support.html
		// The queue output counters are reported by Junos OS Evolved; 237/238 carry
		// the CGNAT NAPT mode and NAT port-block information.
		{
			ID:       215,
			Name:     "erx-queue-7-output-packets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       237,
			Name:     "erx-cgnat-napt-mode-enable",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept,
			HasTag:   true,
		},
		{ID: 238, Name: "erx-napt-block-info", DataType: DataTypeString},
		{
			ID:       239,
			Name:     "erx-queue-0-output-gigawords",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       240,
			Name:     "erx-queue-0-output-octets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       241,
			Name:     "erx-queue-1-output-gigawords",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       242,
			Name:     "erx-queue-1-output-octets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       243,
			Name:     "erx-queue-2-output-gigawords",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       244,
			Name:     "erx-queue-2-output-octets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       245,
			Name:     "erx-queue-3-output-gigawords",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       246,
			Name:     "erx-queue-3-output-octets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       247,
			Name:     "erx-queue-4-output-gigawords",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       248,
			Name:     "erx-queue-4-output-octets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       249,
			Name:     "erx-queue-5-output-gigawords",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       250,
			Name:     "erx-queue-5-output-octets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       251,
			Name:     "erx-queue-6-output-gigawords",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       252,
			Name:     "erx-queue-6-output-octets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       253,
			Name:     "erx-queue-7-output-gigawords",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       254,
			Name:     "erx-queue-7-output-octets",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
	},
}
