package goradius

// AscendVendorDefinition contains the Ascend vendor definition with all its attributes.
// Usage masks are set only where the Lucent TAOS RADIUS Guide (7820-0729-007) or the
// Ascend MAX 6000 RADIUS reference documents a packet direction; the remaining
// attributes have no surviving per-attribute placement documentation and stay
// unrestricted.
var AscendVendorDefinition = &VendorDefinition{
	ID:   529,
	Name: "ascend",
	Attributes: []*AttributeDefinition{
		{ID: 2, Name: "ascend-max-shared-users", DataType: DataTypeInteger},
		{ID: 7, Name: "ascend-uu-info", DataType: DataTypeString},
		{ID: 9, Name: "ascend-cir-timer", DataType: DataTypeInteger},
		{ID: 10, Name: "ascend-fr-08-mode", DataType: DataTypeInteger},
		{ID: 11, Name: "ascend-destination-nas-port", DataType: DataTypeInteger},
		{ID: 12, Name: "ascend-fr-svc-addr", DataType: DataTypeString},
		{
			ID:       13,
			Name:     "ascend-nas-port-format",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"1_2_2":   3,
				"2_4_5_5": 2,
				"2_4_6_4": 1,
				"unknown": 0,
			},
		},
		{
			ID:       14,
			Name:     "ascend-atm-fault-management",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"vc-end-to-end-loopback": 2,
				"vc-no-loopback":         0,
				"vc-segment-loopback":    1,
			},
		},
		{ID: 15, Name: "ascend-atm-loopback-cell-loss", DataType: DataTypeInteger},
		{
			ID:       16,
			Name:     "ascend-ckt-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-pvc": 0,
				"ascend-svc": 1,
			},
		},
		{
			ID:       17,
			Name:     "ascend-svc-enabled",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-svc-enabled-no":  0,
				"ascend-svc-enabled-yes": 1,
			},
		},
		{
			ID:       18,
			Name:     "ascend-session-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-session-g711-alaw":  3,
				"ascend-session-g711-ulaw":  2,
				"ascend-session-g723":       4,
				"ascend-session-g723-64kps": 6,
				"ascend-session-g728":       7,
				"ascend-session-g729":       5,
				"ascend-session-rt24":       8,
				"ascend-session-unknown":    1,
				"ascend-session-unused":     0,
			},
		},
		{ID: 19, Name: "ascend-h323-gatekeeper", DataType: DataTypeIPAddr},
		{ID: 20, Name: "ascend-global-call-id", DataType: DataTypeString},
		{ID: 21, Name: "ascend-h323-conference-id", DataType: DataTypeInteger},
		{ID: 22, Name: "ascend-h323-fegw-address", DataType: DataTypeIPAddr},
		{ID: 23, Name: "ascend-h323-dialed-time", DataType: DataTypeInteger},
		{ID: 24, Name: "ascend-dialed-number", DataType: DataTypeString},
		{ID: 25, Name: "ascend-inter-arrival-jitter", DataType: DataTypeInteger},
		{ID: 26, Name: "ascend-dropped-octets", DataType: DataTypeInteger},
		{ID: 27, Name: "ascend-dropped-packets", DataType: DataTypeInteger},
		{ID: 28, Name: "ascend-auth-delay", DataType: DataTypeInteger},
		{
			ID:       29,
			Name:     "ascend-x25-pad-x3-profile",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"cc_ssp":   4,
				"cc_tsp":   5,
				"crt":      0,
				"custom":   11,
				"default":  2,
				"hardcopy": 6,
				"hdx":      7,
				"infonet":  1,
				"null":     10,
				"pos":      9,
				"scen":     3,
				"shark":    8,
			},
		},
		{ID: 30, Name: "ascend-x25-pad-x3-parameters", DataType: DataTypeString},
		{ID: 31, Name: "ascend-tunnel-vrouter-name", DataType: DataTypeString},
		{
			ID:       32,
			Name:     "ascend-x25-reverse-charging",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"reverse-charging-no":  0,
				"reverse-charging-yes": 1,
			},
		},
		{ID: 33, Name: "ascend-x25-nui-prompt", DataType: DataTypeString},
		{ID: 34, Name: "ascend-x25-nui-password-prompt", DataType: DataTypeString},
		{ID: 35, Name: "ascend-x25-cug", DataType: DataTypeString},
		{ID: 36, Name: "ascend-x25-pad-alias-1", DataType: DataTypeString},
		{ID: 37, Name: "ascend-x25-pad-alias-2", DataType: DataTypeString},
		{ID: 38, Name: "ascend-x25-pad-alias-3", DataType: DataTypeString},
		{ID: 39, Name: "ascend-x25-x121-address", DataType: DataTypeString},
		{ID: 40, Name: "ascend-x25-nui", DataType: DataTypeString},
		{ID: 41, Name: "ascend-x25-rpoa", DataType: DataTypeString},
		{ID: 42, Name: "ascend-x25-pad-prompt", DataType: DataTypeString},
		{ID: 43, Name: "ascend-x25-pad-banner", DataType: DataTypeString},
		{ID: 44, Name: "ascend-x25-profile-name", DataType: DataTypeString},
		{ID: 45, Name: "ascend-recv-name", DataType: DataTypeString},
		{
			ID:       46,
			Name:     "ascend-bi-directional-auth",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"bi-directional-auth-allowed":  1,
				"bi-directional-auth-none":     0,
				"bi-directional-auth-required": 2,
			},
		},
		{ID: 47, Name: "ascend-mtu", DataType: DataTypeInteger},
		{
			ID:       48,
			Name:     "ascend-call-direction",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-call-direction-incoming": 0,
				"ascend-call-direction-outgoing": 1,
			},
		},
		{
			ID:       49,
			Name:     "ascend-service-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-service-type-atm":         20,
				"ascend-service-type-combinet":    7,
				"ascend-service-type-euraw":       9,
				"ascend-service-type-euui":        10,
				"ascend-service-type-fr":          8,
				"ascend-service-type-hdlcnrm":     21,
				"ascend-service-type-ipfax":       19,
				"ascend-service-type-mp":          15,
				"ascend-service-type-mpp":         5,
				"ascend-service-type-nettonet":    25,
				"ascend-service-type-none":        1,
				"ascend-service-type-notused":     0,
				"ascend-service-type-other":       2,
				"ascend-service-type-ppp":         3,
				"ascend-service-type-pseutunppp":  18,
				"ascend-service-type-rawtcp":      13,
				"ascend-service-type-slip":        4,
				"ascend-service-type-telnet":      11,
				"ascend-service-type-telnetbin":   12,
				"ascend-service-type-termserver":  14,
				"ascend-service-type-virtualconn": 16,
				"ascend-service-type-visa2":       23,
				"ascend-service-type-voip":        22,
				"ascend-service-type-x25":         6,
				"ascend-service-type-x25dchan":    17,
			},
		},
		{
			ID:       50,
			Name:     "ascend-filter-required",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"required-no":  0,
				"required-yes": 1,
			},
		},
		{ID: 51, Name: "ascend-traffic-shaper", DataType: DataTypeInteger},
		{ID: 52, Name: "ascend-access-intercept-lea", DataType: DataTypeString},
		{ID: 53, Name: "ascend-access-intercept-log", DataType: DataTypeString},
		{ID: 54, Name: "ascend-private-route-table-id", DataType: DataTypeString},
		{
			ID:       55,
			Name:     "ascend-private-route-required",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"required-no":  0,
				"required-yes": 1,
			},
		},
		{
			ID:       56,
			Name:     "ascend-cache-refresh",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"refresh-no":  0,
				"refresh-yes": 1,
			},
		},
		{ID: 57, Name: "ascend-cache-time", DataType: DataTypeInteger},
		{ID: 58, Name: "ascend-egress-enabled", DataType: DataTypeInteger},
		{ID: 59, Name: "ascend-qos-upstream", DataType: DataTypeString},
		{ID: 60, Name: "ascend-qos-downstream", DataType: DataTypeString},
		{ID: 61, Name: "ascend-atm-connect-vpi", DataType: DataTypeInteger},
		{ID: 62, Name: "ascend-atm-connect-vci", DataType: DataTypeInteger},
		{ID: 63, Name: "ascend-atm-connect-group", DataType: DataTypeInteger},
		{ID: 64, Name: "ascend-atm-group", DataType: DataTypeInteger},
		{
			ID:       65,
			Name:     "ascend-ipx-header-compression",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ipx-header-compression-no":  0,
				"ipx-header-compression-yes": 1,
			},
		},
		{
			ID:       66,
			Name:     "ascend-calling-id-type-of-num",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"abbreviated-number":   6,
				"international-number": 1,
				"national-number":      2,
				"network-specific":     3,
				"subscriber-number":    4,
				"unknown":              0,
			},
		},
		{
			ID:       67,
			Name:     "ascend-calling-id-number-plan",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"data":           3,
				"isdn-telephony": 1,
				"national":       8,
				"private":        9,
				"telex":          4,
				"unknown":        0,
			},
		},
		{
			ID:       68,
			Name:     "ascend-calling-id-presentatn",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"allowed":              0,
				"number-not-available": 2,
				"restricted":           1,
			},
		},
		{
			ID:       69,
			Name:     "ascend-calling-id-screening",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"network-provided":     3,
				"user-not-screened":    0,
				"user-provided-failed": 2,
				"user-provided-passed": 1,
			},
		},
		{
			ID:       70,
			Name:     "ascend-bir-enable",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"bir-enable-no":  0,
				"bir-enable-yes": 1,
			},
		},
		{
			ID:       71,
			Name:     "ascend-bir-proxy",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"bir-proxy-no":  0,
				"bir-proxy-yes": 1,
			},
		},
		{ID: 72, Name: "ascend-bir-bridge-group", DataType: DataTypeInteger},
		{ID: 73, Name: "ascend-ipsec-profile", DataType: DataTypeString},
		{
			ID:       74,
			Name:     "ascend-pppoe-enable",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"pppoe-no":  0,
				"pppoe-yes": 1,
			},
		},
		{
			ID:       75,
			Name:     "ascend-bridge-non-pppoe",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"bridge-non-pppoe-no":  0,
				"bridge-non-pppoe-yes": 1,
			},
		},
		{
			ID:       76,
			Name:     "ascend-atm-direct",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"atm-direct-no":  0,
				"atm-direct-yes": 1,
			},
		},
		{ID: 77, Name: "ascend-atm-direct-profile", DataType: DataTypeString},
		{ID: 78, Name: "ascend-client-primary-wins", DataType: DataTypeIPAddr},
		{ID: 79, Name: "ascend-client-secondary-wins", DataType: DataTypeIPAddr},
		{
			ID:       80,
			Name:     "ascend-client-assign-wins",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"wins-assign-no":  0,
				"wins-assign-yes": 1,
			},
		},
		{
			ID:       81,
			Name:     "ascend-auth-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"auth-any":     2,
				"auth-chap":    4,
				"auth-default": 1,
				"auth-ms-chap": 5,
				"auth-none":    0,
				"auth-pap":     3,
			},
		},
		{
			ID:       82,
			Name:     "ascend-port-redir-protocol",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-proto-tcp": 6,
				"ascend-proto-udp": 17,
			},
		},
		{ID: 83, Name: "ascend-port-redir-portnum", DataType: DataTypeInteger},
		{ID: 84, Name: "ascend-port-redir-server", DataType: DataTypeIPAddr},
		{
			ID:       85,
			Name:     "ascend-ip-pool-chaining",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ip-pool-chaining-no":  0,
				"ip-pool-chaining-yes": 1,
			},
		},
		{ID: 86, Name: "ascend-owner-ip-addr", DataType: DataTypeIPAddr},
		{
			ID:       87,
			Name:     "ascend-ip-tos",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ip-tos-cost":        2,
				"ip-tos-disabled":    1,
				"ip-tos-latency":     16,
				"ip-tos-normal":      0,
				"ip-tos-reliability": 4,
				"ip-tos-throughput":  8,
			},
		},
		{
			ID:       88,
			Name:     "ascend-ip-tos-precedence",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ip-tos-precedence-pri-five":   160,
				"ip-tos-precedence-pri-four":   128,
				"ip-tos-precedence-pri-normal": 0,
				"ip-tos-precedence-pri-one":    32,
				"ip-tos-precedence-pri-seven":  224,
				"ip-tos-precedence-pri-six":    192,
				"ip-tos-precedence-pri-three":  96,
				"ip-tos-precedence-pri-two":    64,
			},
		},
		{
			ID:       89,
			Name:     "ascend-ip-tos-apply-to",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ip-tos-apply-to-both":     3072,
				"ip-tos-apply-to-incoming": 1024,
				"ip-tos-apply-to-outgoing": 2048,
			},
		},
		{ID: 90, Name: "ascend-filter", DataType: DataTypeString},
		{ID: 91, Name: "ascend-telnet-profile", DataType: DataTypeString},
		{
			ID:       92,
			Name:     "ascend-dsl-rate-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"rate-type-adslcap":     2,
				"rate-type-adsldmt":     4,
				"rate-type-adsldmtcell": 3,
				"rate-type-disabled":    0,
				"rate-type-sdsl":        1,
			},
		},
		{ID: 93, Name: "ascend-redirect-number", DataType: DataTypeString},
		{ID: 94, Name: "ascend-atm-vpi", DataType: DataTypeInteger},
		{ID: 95, Name: "ascend-atm-vci", DataType: DataTypeInteger},
		{
			ID:       96,
			Name:     "ascend-source-ip-check",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"source-ip-check-no":  0,
				"source-ip-check-yes": 1,
			},
		},
		{
			ID:       97,
			Name:     "ascend-dsl-rate-mode",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"rate-mode-autobaud": 1,
				"rate-mode-single":   2,
			},
		},
		{
			ID:       98,
			Name:     "ascend-dsl-upstream-limit",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"adsldmt-up-896000":  153,
				"adslcap-up-1088000": 50,
				"adslcap-up-272000":  56,
				"adslcap-up-408000":  55,
				"adslcap-up-544000":  54,
				"adslcap-up-680000":  53,
				"adslcap-up-816000":  52,
				"adslcap-up-952000":  51,
				"adsldmt-up-1088000": 151,
				"adsldmt-up-128000":  160,
				"adsldmt-up-256000":  159,
				"adsldmt-up-384000":  158,
				"adsldmt-up-512000":  157,
				"adsldmt-up-640000":  156,
				"adsldmt-up-768000":  155,
				"adsldmt-up-800000":  154,
				"adsldmt-up-928000":  152,
				"adsldmt-up-auto":    150,
				"sdsl-1168000":       5,
				"sdsl-144000":        0,
				"sdsl-1552000":       6,
				"sdsl-2320000":       7,
				"sdsl-272000":        1,
				"sdsl-400000":        2,
				"sdsl-528000":        3,
				"sdsl-784000":        4,
			},
		},
		{
			ID:       99,
			Name:     "ascend-dsl-downstream-limit",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"adslcap-dn-1280000": 10,
				"adslcap-dn-1600000": 9,
				"adslcap-dn-1920000": 8,
				"adslcap-dn-2240000": 7,
				"adslcap-dn-2560000": 6,
				"adslcap-dn-2688000": 5,
				"adslcap-dn-3200000": 4,
				"adslcap-dn-4480000": 3,
				"adslcap-dn-5120000": 2,
				"adslcap-dn-6272000": 1,
				"adslcap-dn-640000":  12,
				"adslcap-dn-7168000": 0,
				"adslcap-dn-960000":  11,
				"adsldmt-dn-128000":  121,
				"adsldmt-dn-1280000": 114,
				"adsldmt-dn-1600000": 113,
				"adsldmt-dn-1920000": 112,
				"adsldmt-dn-2240000": 111,
				"adsldmt-dn-256000":  120,
				"adsldmt-dn-2560000": 110,
				"adsldmt-dn-2688000": 109,
				"adsldmt-dn-3200000": 108,
				"adsldmt-dn-384000":  119,
				"adsldmt-dn-4480000": 107,
				"adsldmt-dn-512000":  118,
				"adsldmt-dn-5120000": 106,
				"adsldmt-dn-6272000": 105,
				"adsldmt-dn-640000":  117,
				"adsldmt-dn-7168000": 104,
				"adsldmt-dn-768000":  116,
				"adsldmt-dn-8000000": 103,
				"adsldmt-dn-8960000": 102,
				"adsldmt-dn-9504000": 101,
				"adsldmt-dn-960000":  115,
				"adsldmt-dn-auto":    100,
			},
		},
		{ID: 100, Name: "ascend-dsl-cir-recv-limit", DataType: DataTypeInteger},
		{ID: 101, Name: "ascend-dsl-cir-xmit-limit", DataType: DataTypeInteger},
		{ID: 102, Name: "ascend-vrouter-name", DataType: DataTypeString},
		{ID: 103, Name: "ascend-source-auth", DataType: DataTypeString},
		{ID: 104, Name: "ascend-private-route", DataType: DataTypeString},
		{
			ID:       105,
			Name:     "ascend-numbering-plan-id",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"isdn-numbering-plan":    1,
				"private-numbering-plan": 9,
				"unknown-numbering-plan": 0,
			},
		},
		{
			ID:       106,
			Name:     "ascend-fr-link-status-dlci",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-fr-lmi-dlci-0":    0,
				"ascend-fr-lmi-dlci-1023": 1023,
			},
		},
		{ID: 107, Name: "ascend-calling-subaddress", DataType: DataTypeString},
		{ID: 108, Name: "ascend-callback-delay", DataType: DataTypeInteger},
		{ID: 109, Name: "ascend-endpoint-disc", DataType: DataTypeString},
		{ID: 110, Name: "ascend-remote-fw", DataType: DataTypeString},
		{ID: 111, Name: "ascend-multicast-gleave-delay", DataType: DataTypeInteger},
		{
			ID:       112,
			Name:     "ascend-cbcp-enable",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"cbcp-not-enabled": 0,
				"cbcp-enabled":     1,
			},
		},
		{
			ID:       113,
			Name:     "ascend-cbcp-mode",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"cbcp-no-callback":      1,
				"cbcp-user-callback":    2,
				"cbcp-profile-callback": 3,
				"cbcp-any-or-no":        7,
				"cbcp-off":              8,
			},
		},
		{ID: 114, Name: "ascend-cbcp-delay", DataType: DataTypeInteger},
		{ID: 115, Name: "ascend-cbcp-trunk-group", DataType: DataTypeInteger},
		{ID: 116, Name: "ascend-appletalk-route", DataType: DataTypeString},
		{
			ID:       117,
			Name:     "ascend-appletalk-peer-mode",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"appletalk-peer-dialin": 1,
				"appletalk-peer-router": 0,
			},
		},
		{
			ID:       118,
			Name:     "ascend-route-appletalk",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"route-appletalk-no":  0,
				"route-appletalk-yes": 1,
			},
		},
		{ID: 119, Name: "ascend-fcp-parameter", DataType: DataTypeString},
		{ID: 120, Name: "ascend-modem-portno", DataType: DataTypeInteger},
		{ID: 121, Name: "ascend-modem-slotno", DataType: DataTypeInteger},
		{ID: 122, Name: "ascend-modem-shelfno", DataType: DataTypeInteger},
		{ID: 123, Name: "ascend-call-attempt-limit", DataType: DataTypeInteger},
		{ID: 124, Name: "ascend-call-block-duration", DataType: DataTypeInteger},
		{ID: 125, Name: "ascend-maximum-call-duration", DataType: DataTypeInteger},
		{
			ID:       126,
			Name:     "ascend-temporary-rtes",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"temp-rtes-no":  0,
				"temp-rtes-yes": 1,
			},
		},
		{
			ID:       127,
			Name:     "ascend-tunneling-protocol",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"atmp-tunnel": 0,
				"vtp-tunnel":  1,
			},
		},
		{
			ID:       128,
			Name:     "ascend-shared-profile-enable",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"shared-profile-no":  0,
				"shared-profile-yes": 1,
			},
		},
		{ID: 129, Name: "ascend-primary-home-agent", DataType: DataTypeString},
		{ID: 130, Name: "ascend-secondary-home-agent", DataType: DataTypeString},
		{
			ID:       131,
			Name:     "ascend-dialout-allowed",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"dialout-not-allowed": 0,
				"dialout-allowed":     1,
			},
		},
		{ID: 132, Name: "ascend-client-gateway", DataType: DataTypeIPAddr},
		{
			ID:       133,
			Name:     "ascend-bacp-enable",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"bacp-no":  0,
				"bacp-yes": 1,
			},
		},
		{ID: 134, Name: "ascend-dhcp-maximum-leases", DataType: DataTypeInteger},
		{ID: 135, Name: "ascend-client-primary-dns", DataType: DataTypeIPAddr},
		{ID: 136, Name: "ascend-client-secondary-dns", DataType: DataTypeIPAddr},
		{
			ID:       137,
			Name:     "ascend-client-assign-dns",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"dns-assign-no":  0,
				"dns-assign-yes": 1,
			},
		},
		{
			ID:       138,
			Name:     "ascend-user-acct-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-user-acct-none":         0,
				"ascend-user-acct-user":         1,
				"ascend-user-acct-user-default": 2,
			},
		},
		{ID: 139, Name: "ascend-user-acct-host", DataType: DataTypeIPAddr},
		{ID: 140, Name: "ascend-user-acct-port", DataType: DataTypeInteger},
		{ID: 141, Name: "ascend-user-acct-key", DataType: DataTypeString},
		{
			ID:       142,
			Name:     "ascend-user-acct-base",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"base-10": 0,
				"base-16": 1,
			},
		},
		{ID: 143, Name: "ascend-user-acct-time", DataType: DataTypeInteger},
		{ID: 144, Name: "ascend-assign-ip-client", DataType: DataTypeIPAddr},
		{ID: 145, Name: "ascend-assign-ip-server", DataType: DataTypeIPAddr},
		{ID: 146, Name: "ascend-assign-ip-global-pool", DataType: DataTypeString},
		{
			ID:       147,
			Name:     "ascend-dhcp-reply",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"dhcp-reply-no":  0,
				"dhcp-reply-yes": 1,
			},
		},
		{ID: 148, Name: "ascend-dhcp-pool-number", DataType: DataTypeInteger},
		{
			ID:       149,
			Name:     "ascend-expect-callback",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"expect-callback-no":  0,
				"expect-callback-yes": 1,
			},
		},
		{
			ID:       150,
			Name:     "ascend-event-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-coldstart":     1,
				"ascend-session-event": 2,
			},
		},
		{ID: 151, Name: "ascend-session-svr-key", DataType: DataTypeString},
		{ID: 152, Name: "ascend-multicast-rate-limit", DataType: DataTypeInteger},
		{ID: 153, Name: "ascend-if-netmask", DataType: DataTypeIPAddr},
		{ID: 154, Name: "ascend-remote-addr", DataType: DataTypeIPAddr},
		{
			ID:       155,
			Name:     "ascend-multicast-client",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"multicast-no":  0,
				"multicast-yes": 1,
			},
		},
		{ID: 156, Name: "ascend-fr-circuit-name", DataType: DataTypeString},
		{
			ID:       157,
			Name:     "ascend-fr-linkup",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-linkup-default":  0,
				"ascend-linkup-alwaysup": 1,
			},
		},
		{ID: 158, Name: "ascend-fr-nailed-grp", DataType: DataTypeInteger},
		{
			ID:       159,
			Name:     "ascend-fr-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-fr-dte": 0,
				"ascend-fr-dce": 1,
				"ascend-fr-nni": 2,
			},
		},
		{
			ID:       160,
			Name:     "ascend-fr-link-mgt",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ascend-fr-no-link-mgt": 0,
				"ascend-fr-t1-617d":     1,
				"ascend-fr-q-933a":      2,
			},
		},
		{ID: 161, Name: "ascend-fr-n391", DataType: DataTypeInteger},
		{ID: 162, Name: "ascend-fr-dce-n392", DataType: DataTypeInteger},
		{ID: 163, Name: "ascend-fr-dte-n392", DataType: DataTypeInteger},
		{ID: 164, Name: "ascend-fr-dce-n393", DataType: DataTypeInteger},
		{ID: 165, Name: "ascend-fr-dte-n393", DataType: DataTypeInteger},
		{ID: 166, Name: "ascend-fr-t391", DataType: DataTypeInteger},
		{ID: 167, Name: "ascend-fr-t392", DataType: DataTypeInteger},
		{ID: 168, Name: "ascend-bridge-address", DataType: DataTypeString},
		{ID: 169, Name: "ascend-ts-idle-limit", DataType: DataTypeInteger},
		{
			ID:       170,
			Name:     "ascend-ts-idle-mode",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ts-idle-none":         0,
				"ts-idle-input":        1,
				"ts-idle-input-output": 2,
			},
		},
		{
			ID:       171,
			Name:     "ascend-dba-monitor",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"dba-transmit":      0,
				"dba-transmit-recv": 1,
				"dba-none":          2,
			},
		},
		{ID: 172, Name: "ascend-base-channel-count", DataType: DataTypeInteger},
		{ID: 173, Name: "ascend-minimum-channels", DataType: DataTypeInteger},
		{ID: 174, Name: "ascend-ipx-route", DataType: DataTypeString},
		{
			ID:       175,
			Name:     "ascend-ft1-caller",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ft1-no":  0,
				"ft1-yes": 1,
			},
		},
		{ID: 176, Name: "ascend-backup", DataType: DataTypeString},
		{
			ID:       177,
			Name:     "ascend-call-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"switched":      0,
				"nailed":        1,
				"nailed/mpp":    2,
				"perm/switched": 3,
				"ao/di":         6,
				"megamax":       7,
			},
		},
		{ID: 178, Name: "ascend-group", DataType: DataTypeString},
		{ID: 179, Name: "ascend-fr-dlci", DataType: DataTypeInteger},
		{ID: 180, Name: "ascend-fr-profile-name", DataType: DataTypeString},
		{ID: 181, Name: "ascend-ara-pw", DataType: DataTypeString},
		{ID: 182, Name: "ascend-ipx-node-addr", DataType: DataTypeString},
		{ID: 183, Name: "ascend-home-agent-ip-addr", DataType: DataTypeIPAddr},
		{ID: 184, Name: "ascend-home-agent-password", DataType: DataTypeString},
		{ID: 185, Name: "ascend-home-network-name", DataType: DataTypeString},
		{ID: 186, Name: "ascend-home-agent-udp-port", DataType: DataTypeInteger},
		{ID: 187, Name: "ascend-multilink-id", DataType: DataTypeInteger},
		{ID: 188, Name: "ascend-num-in-multilink", DataType: DataTypeInteger},
		{ID: 189, Name: "ascend-first-dest", DataType: DataTypeIPAddr},
		{ID: 190, Name: "ascend-pre-input-octets", DataType: DataTypeInteger},
		{ID: 191, Name: "ascend-pre-output-octets", DataType: DataTypeInteger},
		{ID: 192, Name: "ascend-pre-input-packets", DataType: DataTypeInteger},
		{ID: 193, Name: "ascend-pre-output-packets", DataType: DataTypeInteger},
		{ID: 194, Name: "ascend-maximum-time", DataType: DataTypeInteger, Usage: UsageAccessAccept},
		{
			ID:       195,
			Name:     "ascend-disconnect-cause",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"no-reason":                      0,
				"not-applicable":                 1,
				"unknown":                        2,
				"call-disconnected":              3,
				"clid-authentication-failed":     4,
				"clid-radius-timeout":            5,
				"modem-no-dcd":                   10,
				"dcd-detected-then-inactive":     11,
				"modem-invalid-result-codes":     12,
				"termsrv-user-quit":              20,
				"termsrv-idle-timeout":           21,
				"termsrv-exit-telnet":            22,
				"termsrv-no-ipaddr":              23,
				"termsrv-exit-raw-tcp":           24,
				"termsrv-exit-login-failed":      25,
				"termsrv-exit-raw-tcp-disabled":  26,
				"termsrv-ctrl-c-in-login":        27,
				"termsrv-destroyed":              28,
				"termsrv-user-closed-vcon":       29,
				"termsrv-vcon-destroyed":         30,
				"termsrv-exit-rlogin":            31,
				"termsrv-bad-rlogin-option":      32,
				"termsrv-not-enough-resources":   33,
				"mpp-no-null-msg-timeout":        35,
				"ppp-lcp-timeout":                40,
				"ppp-lcp-negotion-failed":        41,
				"ppp-pap-auth-failed":            42,
				"ppp-chap-auth-failed":           43,
				"ppp-rmt-auth-failed":            44,
				"ppp-rcv-terminate-req":          45,
				"ppp-rcv-close-event":            46,
				"ppp-no-ncps-open":               47,
				"ppp-mp-bundle-unknown":          48,
				"ppp-lcp-close-mp-add-fail":      49,
				"session-table-full":             50,
				"out-of-resources":               51,
				"invalid-ip-address":             52,
				"hostname-resolution-failed":     53,
				"bad-or-missing-port-number":     54,
				"host-reset":                     60,
				"connection-refused":             61,
				"connection-timeout":             62,
				"connection-closed":              63,
				"network-unreachable":            64,
				"host-unreachable":               65,
				"network-unreachable-admin":      66,
				"host-unreachable-admin":         67,
				"port-unreachable":               68,
				"session-timeout":                100,
				"invalid-incoming-user":          101,
				"disconnect-due-to-callback":     102,
				"proto-disabled-or-unsupported":  120,
				"disconnect-req-by-radius":       150,
				"disconnect-req-by-local-admin":  151,
				"v110-timeout-sync-retry-exceed": 160,
				"ppp-auth-timeout-exceeded":      170,
				"user-executed-do-hangup":        180,
				"remote-end-hung-up":             185,
				"resource-has-been-quiesced":     190,
				"max-call-duration-reached":      195,
			},
		},
		{
			ID:       196,
			Name:     "ascend-connect-progress",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"no-progress":               0,
				"call-up":                   10,
				"modem-up":                  30,
				"modem-awaiting-dcd":        31,
				"modem-awaiting-codes":      32,
				"termsrv-started":           40,
				"termsrv-raw-tcp-started":   41,
				"termsrv-telnet-started":    42,
				"termsrv-raw-tcp-connected": 43,
				"termsrv-telnet-connected":  44,
				"termsrv-rlogin-started":    45,
				"termsrv-rlogin-connected":  46,
				"modem-outdial-call-up":     50,
				"lan-session-up":            60,
				"lcp-opening":               61,
				"ccp-opening":               62,
				"ipncp-opening":             63,
				"bncp-opening":              64,
				"lcp-opened":                65,
				"ccp-opened":                66,
				"ipncp-opened":              67,
				"bncp-opened":               68,
				"lcp-state-initial":         69,
				"lcp-state-starting":        70,
				"lcp-state-closed":          71,
				"lcp-state-stopped":         72,
				"lcp-state-closing":         73,
				"lcp-state-stopping":        74,
				"lcp-state-request-sent":    75,
				"lcp-state-ack-received":    76,
				"lcp-state-ack-sent":        77,
				"ipxncp-opened":             80,
				"atncp-opened":              81,
				"bacp-opening":              82,
				"bacp-opened":               83,
				"v110-up":                   90,
				"v110-state-opened":         91,
				"v110-state-carrier":        92,
				"v110-state-reset":          93,
				"v110-state-closed":         94,
			},
		},
		{ID: 197, Name: "ascend-data-rate", DataType: DataTypeInteger, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 198, Name: "ascend-presession-time", DataType: DataTypeInteger},
		{ID: 199, Name: "ascend-token-idle", DataType: DataTypeInteger},
		{
			ID:       200,
			Name:     "ascend-token-immediate",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"tok-imm-no":  0,
				"tok-imm-yes": 1,
			},
		},
		{
			ID:       201,
			Name:     "ascend-require-auth",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"not-require-auth": 0,
				"require-auth":     1,
			},
		},
		{ID: 202, Name: "ascend-number-sessions", DataType: DataTypeString},
		{ID: 203, Name: "ascend-authen-alias", DataType: DataTypeString},
		{ID: 204, Name: "ascend-token-expiry", DataType: DataTypeInteger},
		{ID: 205, Name: "ascend-menu-selector", DataType: DataTypeString},
		{ID: 206, Name: "ascend-menu-item", DataType: DataTypeString},
		{
			ID:       207,
			Name:     "ascend-pw-warntime",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"days-of-warning": 0,
			},
		},
		{
			ID:       208,
			Name:     "ascend-pw-lifetime",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"lifetime-in-days": 0,
			},
		},
		{ID: 209, Name: "ascend-ip-direct", DataType: DataTypeIPAddr},
		{
			ID:       210,
			Name:     "ascend-ppp-vj-slot-comp",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"vj-slot-comp-no": 1,
			},
		},
		{
			ID:       211,
			Name:     "ascend-ppp-vj-1172",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ppp-vj-1172": 1,
			},
		},
		{ID: 212, Name: "ascend-ppp-async-map", DataType: DataTypeInteger},
		{ID: 213, Name: "ascend-third-prompt", DataType: DataTypeString},
		{
			ID:         214,
			Name:       "ascend-send-secret",
			DataType:   DataTypeString,
			Usage:      UsageAccessRequest | UsageAccessAccept,
			Encryption: EncryptionAscendSecret,
		},
		{
			ID:         215,
			Name:       "ascend-receive-secret",
			DataType:   DataTypeString,
			Usage:      UsageAccessAccept,
			Encryption: EncryptionAscendSecret,
		},
		{
			ID:       216,
			Name:     "ascend-ipx-peer-mode",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ipx-peer-router": 0,
				"ipx-peer-dialin": 1,
			},
		},
		{ID: 217, Name: "ascend-ip-pool-definition", DataType: DataTypeString},
		{ID: 218, Name: "ascend-assign-ip-pool", DataType: DataTypeInteger},
		{
			ID:       219,
			Name:     "ascend-fr-direct",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"fr-direct-no":  0,
				"fr-direct-yes": 1,
			},
		},
		{ID: 220, Name: "ascend-fr-direct-profile", DataType: DataTypeString},
		{ID: 221, Name: "ascend-fr-direct-dlci", DataType: DataTypeInteger},
		{
			ID:       222,
			Name:     "ascend-handle-ipx",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"handle-ipx-none":   0,
				"handle-ipx-client": 1,
				"handle-ipx-server": 2,
			},
		},
		{ID: 223, Name: "ascend-netware-timeout", DataType: DataTypeInteger},
		{ID: 224, Name: "ascend-ipx-alias", DataType: DataTypeInteger},
		{ID: 225, Name: "ascend-metric", DataType: DataTypeInteger},
		{
			ID:       226,
			Name:     "ascend-pri-number-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"unknown-number":      0,
				"intl-number":         1,
				"national-number":     2,
				"net-specific-number": 3,
				"local-number":        4,
				"abbrev-number":       5,
			},
		},
		{ID: 227, Name: "ascend-dial-number", DataType: DataTypeString},
		{
			ID:       228,
			Name:     "ascend-route-ip",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"route-ip-no":  0,
				"route-ip-yes": 1,
			},
		},
		{
			ID:       229,
			Name:     "ascend-route-ipx",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"route-ipx-no":  0,
				"route-ipx-yes": 1,
			},
		},
		{
			ID:       230,
			Name:     "ascend-bridge",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"bridge-no":  0,
				"bridge-yes": 1,
			},
		},
		{
			ID:       231,
			Name:     "ascend-send-auth",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"send-auth-none":    0,
				"send-auth-pap":     1,
				"send-auth-chap":    2,
				"send-auth-ms-chap": 3,
			},
		},
		{ID: 232, Name: "ascend-send-passwd", DataType: DataTypeString},
		{
			ID:       233,
			Name:     "ascend-link-compression",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"link-comp-none":         0,
				"link-comp-stac":         1,
				"link-comp-stac-draft-9": 2,
				"link-comp-ms-stac":      3,
			},
		},
		{ID: 234, Name: "ascend-target-util", DataType: DataTypeInteger},
		{ID: 235, Name: "ascend-maximum-channels", DataType: DataTypeInteger},
		{ID: 236, Name: "ascend-inc-channel-count", DataType: DataTypeInteger},
		{ID: 237, Name: "ascend-dec-channel-count", DataType: DataTypeInteger},
		{ID: 238, Name: "ascend-seconds-of-history", DataType: DataTypeInteger},
		{
			ID:       239,
			Name:     "ascend-history-weigh-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"history-constant":  0,
				"history-linear":    1,
				"history-quadratic": 2,
			},
		},
		{ID: 240, Name: "ascend-add-seconds", DataType: DataTypeInteger},
		{ID: 241, Name: "ascend-remove-seconds", DataType: DataTypeInteger},
		{ID: 242, Name: "ascend-data-filter", DataType: DataTypeABinary, Usage: UsageAccessAccept | UsageCoARequest},
		{ID: 243, Name: "ascend-call-filter", DataType: DataTypeABinary, Usage: UsageAccessAccept},
		{ID: 244, Name: "ascend-idle-limit", DataType: DataTypeInteger, Usage: UsageAccessAccept},
		{ID: 245, Name: "ascend-preempt-limit", DataType: DataTypeInteger},
		{
			ID:       246,
			Name:     "ascend-callback",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"callback-no":  0,
				"callback-yes": 1,
			},
		},
		{
			ID:       247,
			Name:     "ascend-data-svc",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"switched-voice-bearer":          0,
				"nailed-56kr":                    1,
				"nailed-64k":                     2,
				"switched-64kr":                  3,
				"switched-56k":                   4,
				"switched-384kr":                 5,
				"switched-384k":                  6,
				"switched-1536k":                 7,
				"switched-1536kr":                8,
				"switched-128k":                  9,
				"switched-192k":                  10,
				"switched-256k":                  11,
				"switched-320k":                  12,
				"switched-384k-mr":               13,
				"switched-448k":                  14,
				"switched-512k":                  15,
				"switched-576k":                  16,
				"switched-640k":                  17,
				"switched-704k":                  18,
				"switched-768k":                  19,
				"switched-832k":                  20,
				"switched-896k":                  21,
				"switched-960k":                  22,
				"switched-1024k":                 23,
				"switched-1088k":                 24,
				"switched-1152k":                 25,
				"switched-1216k":                 26,
				"switched-1280k":                 27,
				"switched-1344k":                 28,
				"switched-1408k":                 29,
				"switched-1472k":                 30,
				"switched-1600k":                 31,
				"switched-1664k":                 32,
				"switched-1728k":                 33,
				"switched-1792k":                 34,
				"switched-1856k":                 35,
				"switched-1920k":                 36,
				"switched-inherited":             37,
				"switched-restricted-bearer-x30": 38,
				"switched-clear-bearer-v110":     39,
				"switched-restricted-64-x30":     40,
				"switched-clear-56-v110":         41,
				"switched-modem":                 42,
				"switched-atmodem":               43,
				"switched-v110-24-56":            45,
				"switched-v110-48-56":            46,
				"switched-v110-96-56":            47,
				"switched-v110-192-56":           48,
				"switched-v110-384-56":           49,
				"switched-v110-24-56r":           50,
				"switched-v110-48-56r":           51,
				"switched-v110-96-56r":           52,
				"switched-v110-192-56r":          53,
				"switched-v110-384-56r":          54,
				"switched-v110-24-64":            55,
				"switched-v110-48-64":            56,
				"switched-v110-96-64":            57,
				"switched-v110-192-64":           58,
				"switched-v110-384-64":           59,
				"switched-v110-24-64r":           60,
				"switched-v110-48-64r":           61,
				"switched-v110-96-64r":           62,
				"switched-v110-384-64r":          64,
				"switched-v110-192-64r":          63,
				"switched-pots":                  68,
				"switched-atm":                   69,
				"switched-fr":                    70,
			},
		},
		{
			ID:       248,
			Name:     "ascend-force-56",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"force-56-no":  0,
				"force-56-yes": 1,
			},
		},
		{ID: 249, Name: "ascend-billing-number", DataType: DataTypeString},
		{ID: 250, Name: "ascend-call-by-call", DataType: DataTypeInteger},
		{ID: 251, Name: "ascend-transit-number", DataType: DataTypeString},
		{ID: 252, Name: "ascend-host-info", DataType: DataTypeString},
		{ID: 253, Name: "ascend-ppp-address", DataType: DataTypeIPAddr},
		{ID: 254, Name: "ascend-mpp-idle-percent", DataType: DataTypeInteger},
		{ID: 255, Name: "ascend-xmit-rate", DataType: DataTypeInteger, Usage: UsageAccessRequest | UsageAccountingRequest},
	},
}
