package goradius

// BenuVendorDefinition defines the Benu Networks vendor (ID 39406), used by
// the Ciena Virtual Broadband Network Gateway (vBNG) after Ciena acquired
// Benu Networks. Transcribed from the official Benu RADIUS VSA dictionary
// version 5.2 (July 2023).
//
// Usage masks are taken from the packet placements stated in the dictionary
// changelog (for example "Received in Access-Accept, and sent in Accounting");
// attributes without a stated placement stay unrestricted. IDs 1, 5-8, and 11
// are marked undefined in the official dictionary and are omitted. Attributes
// marked encrypt=1 use User-Password encryption.
// The official dictionary also defines a proprietary Acct-Terminate-Cause
// value (Benu-Port-Block-Released = 50) on the standard attribute, which is
// not represented here.
var BenuVendorDefinition = &VendorDefinition{
	ID:   39406,
	Name: "benu",
	Attributes: []*AttributeDefinition{
		{ID: 2, Name: "benu-start-privilege-level", DataType: DataTypeInteger},
		{ID: 3, Name: "benu-max-privilege-level", DataType: DataTypeInteger},
		{ID: 4, Name: "benu-redirection-url", DataType: DataTypeString},
		{
			ID:       9,
			Name:     "benu-registration-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"other":                 0,
				"dhcpv4":                1,
				"dhcpv6":                2,
				"router-solicitation":   3,
				"neighbor-solicitation": 4,
				"ip":                    5,
				"reservedip":            6,
				"pppoe":                 7,
				"ppp":                   8,
			},
		},
		{ID: 10, Name: "benu-vlan-id", DataType: DataTypeInteger},
		{ID: 12, Name: "benu-li-policy", DataType: DataTypeString},
		{ID: 13, Name: "benu-acl-policy", DataType: DataTypeString},
		{ID: 14, Name: "benu-li-id", DataType: DataTypeInteger},
		// Deprecated in the official dictionary.
		{ID: 15, Name: "benu-nat-ip-pool-name", DataType: DataTypeString},
		{ID: 16, Name: "benu-qos-policy", DataType: DataTypeString},
		{ID: 17, Name: "benu-li-server-port", DataType: DataTypeInteger},
		{ID: 18, Name: "benu-li-server-address", DataType: DataTypeIPAddr},
		{
			ID:       19,
			Name:     "benu-li-action",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"stop":  0,
				"start": 1,
			},
		},
		{ID: 20, Name: "benu-acct-reason-code", DataType: DataTypeString},
		{ID: 21, Name: "benu-password-change", DataType: DataTypeString},
		{ID: 22, Name: "benu-acl-redirect-url", DataType: DataTypeString},
		{ID: 23, Name: "benu-ssid", DataType: DataTypeString},
		// Deprecated in the official dictionary.
		{ID: 24, Name: "benu-dhcp-pool-id", DataType: DataTypeString},
		{ID: 25, Name: "benu-private-ip-address", DataType: DataTypeIPAddr},
		{ID: 26, Name: "benu-cos", DataType: DataTypeString},
		{ID: 27, Name: "benu-napt-profile", DataType: DataTypeString},
		{ID: 28, Name: "benu-napt-public-port-range", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 29, Name: "benu-pmkid", DataType: DataTypeOctets},
		{ID: 30, Name: "benu-nas-ip-address", DataType: DataTypeIPAddr},
		{ID: 31, Name: "benu-nas-identifier", DataType: DataTypeString},
		{
			ID:       32,
			Name:     "benu-wifi-service",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       33,
			Name:     "benu-wifi-service-supported",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest,
		},
		{
			ID:       34,
			Name:     "benu-device-type",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest,
			Values: map[string]uint32{
				"cpe": 1,
			},
		},
		{
			ID:       35,
			Name:     "benu-apn-network-id",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       36,
			Name:     "benu-msisdn",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       37,
			Name:     "benu-pgw-fqdn",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       38,
			Name:     "benu-secondary-pgw-fqdn",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       39,
			Name:     "benu-gtp-version",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{ID: 40, Name: "benu-splash-acl-policy", DataType: DataTypeString},
		{ID: 41, Name: "benu-splash-acl-redirect-url", DataType: DataTypeString},
		{ID: 42, Name: "benu-splash-acl-timeout", DataType: DataTypeInteger},
		{
			ID:       43,
			Name:     "benu-subscriber-id",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{ID: 44, Name: "benu-napt-start-port", DataType: DataTypeInteger},
		{ID: 45, Name: "benu-napt-end-port", DataType: DataTypeInteger},
		{ID: 46, Name: "benu-dhcp-vendor-class-id", DataType: DataTypeString},
		{ID: 47, Name: "benu-client-hostname", DataType: DataTypeString, Usage: UsageAccessRequest},
		{
			ID:       48,
			Name:     "benu-apn-ambr-ul",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{
			ID:       49,
			Name:     "benu-apn-ambr-dl",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept | UsageAccountingRequest,
		},
		{ID: 50, Name: "benu-tunnel-qos-policy", DataType: DataTypeString},
		{ID: 51, Name: "benu-connect-time", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 52, Name: "benu-socket-latency", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{
			ID:       53,
			Name:     "benu-request-type",
			DataType: DataTypeInteger,
			Usage:    UsageAccessRequest | UsageAccountingRequest,
			Values: map[string]uint32{
				"new-subscriber":        1,
				"time-limit-expired":    2,
				"volume-limit-exceeded": 3,
			},
		},
		{
			ID:       54,
			Name:     "benu-upstream-volume-limit",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{
			ID:       55,
			Name:     "benu-downstream-volume-limit",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{ID: 56, Name: "benu-dm-action", DataType: DataTypeInteger, Usage: UsageDisconnectRequest},
		{ID: 57, Name: "benu-peak-ap-throughput", DataType: DataTypeString, Usage: UsageAccountingRequest},
		// Deprecated in the official dictionary.
		{ID: 58, Name: "benu-dns-server-address", DataType: DataTypeIPAddr, Usage: UsageAccessAccept},
		{ID: 59, Name: "benu-dns-server-port", DataType: DataTypeInteger, Usage: UsageAccessAccept},
		{ID: 60, Name: "benu-tunnel-hqos-policy", DataType: DataTypeString},
		{
			ID:         61,
			Name:       "benu-enc-li-policy",
			DataType:   DataTypeString,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:         62,
			Name:       "benu-enc-li-id",
			DataType:   DataTypeInteger,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:         63,
			Name:       "benu-enc-li-server-port",
			DataType:   DataTypeInteger,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:         64,
			Name:       "benu-enc-li-server-address",
			DataType:   DataTypeIPAddr,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:         65,
			Name:       "benu-enc-li-action",
			DataType:   DataTypeInteger,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:         66,
			Name:       "benu-enc-calling-station-id",
			DataType:   DataTypeString,
			Encryption: EncryptionUserPassword,
		},
		{ID: 67, Name: "benu-ap-hostname", DataType: DataTypeString},
		{ID: 68, Name: "benu-ap-location", DataType: DataTypeString},
		// Deprecated in the official dictionary.
		{ID: 69, Name: "benu-dnsv6-bridge-server-address", DataType: DataTypeIPv6Addr},
		{ID: 70, Name: "benu-dnsv6-bridge-server-port", DataType: DataTypeInteger},
		{
			ID:       71,
			Name:     "benu-dns-bridge-policy",
			DataType: DataTypeString,
			Usage:    UsageAccessAccept | UsageCoARequest,
		},
		{ID: 72, Name: "benu-home-wag-ipv4-address", DataType: DataTypeIPAddr},
		{ID: 73, Name: "benu-home-wag-ipv6-address", DataType: DataTypeIPv6Addr},
		{ID: 74, Name: "benu-visiting-wag-ipv4-address", DataType: DataTypeIPAddr},
		{ID: 75, Name: "benu-visiting-wag-ipv6-address", DataType: DataTypeIPv6Addr},
		{ID: 76, Name: "benu-home-wag-l2tpv3-port", DataType: DataTypeInteger},
		{ID: 77, Name: "benu-visiting-wag-l2tpv3-port", DataType: DataTypeInteger},
		{ID: 78, Name: "benu-hns-id", DataType: DataTypeInteger},
		{ID: 79, Name: "benu-security-level", DataType: DataTypeInteger},
		{ID: 80, Name: "benu-security-custom-categories", DataType: DataTypeString},
		{ID: 81, Name: "benu-security-allowed-urls", DataType: DataTypeString},
		{ID: 82, Name: "benu-security-blocked-urls", DataType: DataTypeString},
		{ID: 83, Name: "benu-cgnat", DataType: DataTypeInteger},
		{ID: 84, Name: "benu-cgnat-block-size", DataType: DataTypeInteger},
		{ID: 85, Name: "benu-upstream-rate-limit", DataType: DataTypeInteger},
		{ID: 86, Name: "benu-downstream-rate-limit", DataType: DataTypeInteger},
		{ID: 87, Name: "benu-qinq-egress-policy", DataType: DataTypeInteger},
		{ID: 88, Name: "benu-lan-ip-address", DataType: DataTypeIPAddr},
		{ID: 89, Name: "benu-lan-netmask", DataType: DataTypeIPAddr},
		{ID: 90, Name: "benu-lan-dhcp-lease", DataType: DataTypeInteger},
		{ID: 91, Name: "benu-lan-gateway-address", DataType: DataTypeIPAddr},
		{ID: 92, Name: "benu-lan-primary-dns", DataType: DataTypeIPAddr},
		{ID: 93, Name: "benu-lan-secondary-dns", DataType: DataTypeIPAddr},
		{ID: 94, Name: "benu-ipv6-firewall-enable", DataType: DataTypeInteger},
		{ID: 95, Name: "benu-dhcpv6-lease", DataType: DataTypeInteger},
		{ID: 96, Name: "benu-dhcp-remote-id", DataType: DataTypeString},
		// Forwards the Access-Reject reply message inside a CoA-NAK.
		{ID: 97, Name: "benu-reply-message", DataType: DataTypeString, Usage: UsageCoANAK},
		{ID: 98, Name: "benu-subscriber-network-context", DataType: DataTypeString},
		{ID: 99, Name: "benu-subscriber-li-context", DataType: DataTypeString},
		{
			ID:       100,
			Name:     "benu-event-timestamp-milli-seconds",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
		},
		{
			ID:       101,
			Name:     "benu-nat-mode",
			DataType: DataTypeInteger,
			Usage:    UsageAccessAccept,
			Values: map[string]uint32{
				"no-nat": 0,
				"nat":    1,
				"napt":   2,
			},
		},
		{ID: 102, Name: "benu-app-filter-policy", DataType: DataTypeString},
		{ID: 103, Name: "benu-app-category-filter-policy", DataType: DataTypeString},
		{ID: 104, Name: "benu-site-vpn-name", DataType: DataTypeString},
		{ID: 105, Name: "benu-li-server-ipv6-address", DataType: DataTypeIPv6Addr},
		{ID: 106, Name: "benu-li-server6-port", DataType: DataTypeInteger},
		{
			ID:         107,
			Name:       "benu-enc-li-server-ipv6-address",
			DataType:   DataTypeIPv6Addr,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:         108,
			Name:       "benu-enc-li-server6-port",
			DataType:   DataTypeInteger,
			Encryption: EncryptionUserPassword,
		},
		// Deprecated in the official dictionary.
		{ID: 109, Name: "benu-hqos-policy", DataType: DataTypeString},
		{ID: 110, Name: "benu-cpe-hqos-policy", DataType: DataTypeString},
		{ID: 111, Name: "benu-mcast-profile-name", DataType: DataTypeString},
		{ID: 112, Name: "benu-mcast-policy-name", DataType: DataTypeString},
		{ID: 113, Name: "benu-igmp-query-interval", DataType: DataTypeInteger},
		{ID: 114, Name: "benu-igmp-query-max-resp-time", DataType: DataTypeInteger},
		// IDs 115-117 are single-octet (byte) enums in the official dictionary.
		{
			ID:       115,
			Name:     "benu-igmp-fast-leave",
			DataType: DataTypeByte,
			Values: map[string]uint32{
				"enable":  1,
				"disable": 2,
			},
		},
		{
			ID:       116,
			Name:     "benu-igmp-router-alert",
			DataType: DataTypeByte,
			Values: map[string]uint32{
				"enable":  1,
				"disable": 2,
			},
		},
		{
			ID:       117,
			Name:     "benu-mcast-replica-type",
			DataType: DataTypeByte,
			Values: map[string]uint32{
				"non-mvlan": 0,
				"mvlan":     1,
			},
		},
		{ID: 118, Name: "benu-igmp-concur-channels-max", DataType: DataTypeInteger},
		{ID: 119, Name: "benu-igmp-grp-query-interval", DataType: DataTypeInteger},
		{ID: 120, Name: "benu-charging-policy", DataType: DataTypeString},
		{
			ID:       121,
			Name:     "benu-nat-logging",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"enable":  1,
				"disable": 2,
			},
		},
		{ID: 122, Name: "benu-dns-primary-server", DataType: DataTypeIPAddr},
		{ID: 123, Name: "benu-dns-secondary-server", DataType: DataTypeIPAddr},
		{ID: 124, Name: "benu-subscriber-dhcp-relay-policy", DataType: DataTypeString},
		{ID: 125, Name: "benu-pipe-hqos-policy", DataType: DataTypeString},
		{ID: 126, Name: "benu-subport-hqos-policy", DataType: DataTypeString},
		{ID: 127, Name: "benu-volume-acl-policy", DataType: DataTypeString},
		{ID: 128, Name: "benu-volume-redirection-url", DataType: DataTypeString},
		{ID: 129, Name: "benu-tunnel-network-context", DataType: DataTypeString},
		{ID: 130, Name: "benu-ipv6-acct-input-octets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 131, Name: "benu-ipv6-acct-output-octets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 132, Name: "benu-ipv6-acct-input-packets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 133, Name: "benu-ipv6-acct-output-packets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 134, Name: "benu-ipv6-acct-input-gigawords", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 135, Name: "benu-ipv6-acct-output-gigawords", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 136, Name: "benu-pppoe-service-tag", DataType: DataTypeString},
		{ID: 137, Name: "benu-dhcp-vendor-specific-info", DataType: DataTypeString},
		{ID: 138, Name: "benu-dhcp-option82-vendor-specific", DataType: DataTypeString},
		{ID: 139, Name: "benu-li-source-port", DataType: DataTypeInteger},
		{ID: 140, Name: "benu-li-source-address", DataType: DataTypeIPAddr},
		{ID: 141, Name: "benu-li-source-ipv6-address", DataType: DataTypeIPv6Addr},
		{ID: 142, Name: "benu-li-source6-port", DataType: DataTypeInteger},
		{
			ID:       143,
			Name:     "benu-li-header-field",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"acct-session-id": 1,
				"direction":       2,
				"label":           4,
				"li-id":           8,
				"sequence-number": 16,
				"session-id":      32,
			},
		},
		{ID: 144, Name: "benu-li-ipsec-policy", DataType: DataTypeString},
		{
			ID:         145,
			Name:       "benu-enc-li-source-port",
			DataType:   DataTypeInteger,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:         146,
			Name:       "benu-enc-li-source-address",
			DataType:   DataTypeIPAddr,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:         147,
			Name:       "benu-enc-li-source-ipv6-address",
			DataType:   DataTypeIPv6Addr,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:         148,
			Name:       "benu-enc-li-source6-port",
			DataType:   DataTypeInteger,
			Encryption: EncryptionUserPassword,
		},
		{
			ID:         149,
			Name:       "benu-enc-li-header-field",
			DataType:   DataTypeInteger,
			Encryption: EncryptionUserPassword,
			Values: map[string]uint32{
				"acct-session-id": 1,
				"direction":       2,
				"label":           4,
				"li-id":           8,
				"sequence-number": 16,
				"session-id":      32,
			},
		},
		{
			ID:         150,
			Name:       "benu-enc-li-ipsec-policy",
			DataType:   DataTypeString,
			Encryption: EncryptionUserPassword,
		},
		{ID: 151, Name: "benu-subscriber-dhcpv6-relay-policy", DataType: DataTypeString},
		{
			ID:       152,
			Name:     "benu-subscriber-deny-lease-renew",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"enable":  1,
				"disable": 2,
			},
		},
		{
			ID:       153,
			Name:     "benu-duid-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"other":    0,
				"duid-llt": 1,
				"duid-en":  2,
				"duid-ll":  3,
			},
		},
		{ID: 154, Name: "benu-duid-hardware-type", DataType: DataTypeInteger},
		{ID: 155, Name: "benu-duid-timestamp-seconds", DataType: DataTypeInteger},
		{ID: 156, Name: "benu-duid-linklayer-address", DataType: DataTypeString},
		{ID: 157, Name: "benu-duid-enterprise-number", DataType: DataTypeInteger},
		{ID: 158, Name: "benu-duid-enterprise-identifier", DataType: DataTypeString},
	},
}
