package goradius

// NokiaSRVendorDefinition defines the Nokia SR vendor (ID 6527), formerly
// Alcatel-Lucent / Timetra, used by the 7750 SR family of BNG routers.
// Ported from FreeRADIUS dictionary.nokia.sr; the raw attribute names
// (Timetra-* and the bare subscriber/accounting names) are carried under the
// nokia-sr- namespace. Source: Nokia "7750 Service Router RADIUS Attributes
// Reference Guide".
//
// Tagged tunnel attributes keep their has_tag flag; the lawful-intercept and
// APN-password attributes keep Tunnel-Password salted encryption. The 64-bit
// accounting counters are modeled as fixed-layout structs (byte/short +
// integer64 members). The dictionary carries no per-packet placement data, so
// all attributes stay unrestricted (several are CoA-only in practice).
var NokiaSRVendorDefinition = &VendorDefinition{
	ID:   6527,
	Name: "nokia-sr",
	Attributes: []*AttributeDefinition{
		{
			ID:       1,
			Name:     "nokia-sr-timetra-access",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ftp":     1,
				"console": 2,
				"both":    3,
			},
		},
		{ID: 2, Name: "nokia-sr-timetra-home-directory", DataType: DataTypeString},
		{
			ID:       3,
			Name:     "nokia-sr-timetra-restrict-to-home",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"true":  1,
				"false": 2,
			},
		},
		{ID: 4, Name: "nokia-sr-timetra-profile", DataType: DataTypeString},
		{
			ID:       5,
			Name:     "nokia-sr-timetra-default-action",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"permit-all": 1,
				"deny-all":   2,
				"none":       3,
			},
		},
		{ID: 6, Name: "nokia-sr-timetra-cmd", DataType: DataTypeString},
		{
			ID:       7,
			Name:     "nokia-sr-timetra-action",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"permit": 1,
				"deny":   2,
			},
		},
		{ID: 8, Name: "nokia-sr-timetra-exec-file", DataType: DataTypeString},
		{ID: 9, Name: "nokia-sr-primary-dns", DataType: DataTypeIPAddr},
		{ID: 10, Name: "nokia-sr-secondary-dns", DataType: DataTypeIPAddr},
		{ID: 11, Name: "nokia-sr-subsc-id-str", DataType: DataTypeString},
		{ID: 12, Name: "nokia-sr-subsc-prof-str", DataType: DataTypeString},
		{ID: 13, Name: "nokia-sr-sla-prof-str", DataType: DataTypeString},
		{ID: 14, Name: "nokia-sr-force-renew", DataType: DataTypeString},
		{ID: 15, Name: "nokia-sr-create-host", DataType: DataTypeString},
		{ID: 16, Name: "nokia-sr-ancp-str", DataType: DataTypeString},
		{ID: 17, Name: "nokia-sr-retail-serv-id", DataType: DataTypeInteger},
		{ID: 18, Name: "nokia-sr-default-router", DataType: DataTypeIPAddr},
		{
			ID:       19,
			Name:     "nokia-sr-acct-i-inprof-octets-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-inprof-octets-selection", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-inprof-octets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-inprof-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       20,
			Name:     "nokia-sr-acct-i-outprof-octets-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-outprof-octets-selection", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-outprof-octets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-outprof-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       21,
			Name:     "nokia-sr-acct-o-inprof-octets-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-inprof-octets-selection", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-inprof-octets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-inprof-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       22,
			Name:     "nokia-sr-acct-o-outprof-octets-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-outprof-octets-selection", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-outprof-octets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-outprof-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       23,
			Name:     "nokia-sr-acct-i-inprof-pkts-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-inprof-pkts-selection", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-inprof-pkts-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-inprof-pkts", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       24,
			Name:     "nokia-sr-acct-i-outprof-pkts-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-outprof-pkts-selection", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-outprof-pkts-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-outprof-pkts", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       25,
			Name:     "nokia-sr-acct-o-inprof-pkts-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-inprof-pkts-selection", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-inprof-pkts-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-inprof-pkts", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       26,
			Name:     "nokia-sr-acct-o-outprof-pkts-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-outprof-pkts-selection", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-outprof-pkts-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-outprof-pkts", DataType: DataTypeInteger64},
			},
		},
		{ID: 27, Name: "nokia-sr-client-hardware-addr", DataType: DataTypeString},
		{ID: 28, Name: "nokia-sr-int-dest-id-str", DataType: DataTypeString},
		{ID: 29, Name: "nokia-sr-primary-nbns", DataType: DataTypeIPAddr},
		{ID: 30, Name: "nokia-sr-secondary-nbns", DataType: DataTypeIPAddr},
		{ID: 31, Name: "nokia-sr-msap-serv-id", DataType: DataTypeInteger},
		{ID: 32, Name: "nokia-sr-msap-policy", DataType: DataTypeString},
		{ID: 33, Name: "nokia-sr-msap-interface", DataType: DataTypeString},
		{ID: 34, Name: "nokia-sr-pppoe-pado-delay", DataType: DataTypeInteger},
		{ID: 35, Name: "nokia-sr-pppoe-service-name", DataType: DataTypeString},
		{ID: 36, Name: "nokia-sr-dhcp-vendor-class-id", DataType: DataTypeString},
		{
			ID:       37,
			Name:     "nokia-sr-acct-oc-i-inprof-octets-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-oc-i-inprof-octets-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-oc-i-inprof-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       38,
			Name:     "nokia-sr-acct-oc-i-outprof-octets-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-oc-i-outprof-octets-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-oc-i-outprof-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       39,
			Name:     "nokia-sr-acct-oc-o-inprof-octets-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-oc-o-inprof-octets-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-oc-o-inprof-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       40,
			Name:     "nokia-sr-acct-oc-o-outprof-octets-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-oc-o-outprof-octets-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-oc-o-outprof-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       41,
			Name:     "nokia-sr-acct-oc-i-inprof-pkts-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-oc-i-inprof-pkts-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-oc-i-inprof-pkts", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       42,
			Name:     "nokia-sr-acct-oc-i-outprof-pkts-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-oc-i-outprof-pkts-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-oc-i-outprof-pkts", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       43,
			Name:     "nokia-sr-acct-oc-o-inprof-pkts-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-oc-o-inprof-pkts-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-oc-o-inprof-pkts", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       44,
			Name:     "nokia-sr-acct-oc-o-outprof-pkts-64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-oc-o-outprof-pkts-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-oc-o-outprof-pkts", DataType: DataTypeInteger64},
			},
		},
		{ID: 45, Name: "nokia-sr-app-prof-str", DataType: DataTypeString},
		{ID: 46, Name: "nokia-sr-tunnel-group", DataType: DataTypeString},
		{
			ID:       47,
			Name:     "nokia-sr-tunnel-algorithm",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"weighted-access": 1,
				"existing-first":  2,
			},
		},
		{
			ID:       48,
			Name:     "nokia-sr-tunnel-max-sessions",
			DataType: DataTypeInteger,
			HasTag:   true,
		},
		{
			ID:       49,
			Name:     "nokia-sr-tunnel-idle-timeout",
			DataType: DataTypeInteger,
			HasTag:   true,
		},
		{
			ID:       50,
			Name:     "nokia-sr-tunnel-hello-interval",
			DataType: DataTypeInteger,
			HasTag:   true,
		},
		{
			ID:       51,
			Name:     "nokia-sr-tunnel-destruct-timeout",
			DataType: DataTypeInteger,
			HasTag:   true,
		},
		{
			ID:       52,
			Name:     "nokia-sr-tunnel-max-retries-estab",
			DataType: DataTypeInteger,
			HasTag:   true,
		},
		{
			ID:       53,
			Name:     "nokia-sr-tunnel-max-retries-not-estab",
			DataType: DataTypeInteger,
			HasTag:   true,
		},
		{
			ID:       54,
			Name:     "nokia-sr-tunnel-avp-hiding",
			DataType: DataTypeInteger,
			HasTag:   true,
			Values: map[string]uint32{
				"nothing":        1,
				"sensitive-only": 2,
				"all":            3,
			},
		},
		{ID: 55, Name: "nokia-sr-bgp-policy", DataType: DataTypeString},
		{ID: 56, Name: "nokia-sr-bgp-auth-keychain", DataType: DataTypeString},
		{ID: 57, Name: "nokia-sr-bgp-auth-key", DataType: DataTypeOctets},
		{ID: 58, Name: "nokia-sr-bgp-export-policy", DataType: DataTypeString},
		{ID: 59, Name: "nokia-sr-bgp-import-policy", DataType: DataTypeString},
		{ID: 60, Name: "nokia-sr-bgp-peeras", DataType: DataTypeInteger},
		{ID: 61, Name: "nokia-sr-ipsec-serv-id", DataType: DataTypeInteger},
		{ID: 62, Name: "nokia-sr-ipsec-interface", DataType: DataTypeString},
		{ID: 63, Name: "nokia-sr-ipsec-tunnel-template-id", DataType: DataTypeInteger},
		{ID: 64, Name: "nokia-sr-ipsec-sa-lifetime", DataType: DataTypeInteger},
		{
			ID:       65,
			Name:     "nokia-sr-ipsec-sa-pfs-group",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"group1": 1,
				"group2": 2,
				"group5": 5,
			},
		},
		{
			ID:       66,
			Name:     "nokia-sr-ipsec-sa-encr-algorithm",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"null":   1,
				"des":    2,
				"des3":   3,
				"aes128": 4,
				"aes192": 5,
				"aes256": 6,
			},
		},
		{
			ID:       67,
			Name:     "nokia-sr-ipsec-sa-auth-algorithm",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"null": 1,
				"md5":  2,
				"sha1": 3,
			},
		},
		{ID: 68, Name: "nokia-sr-ipsec-sa-replay-window", DataType: DataTypeInteger},
		{
			ID:       69,
			Name:     "nokia-sr-acct-i-high-octets-drop_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-high-octets-drop-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-high-octets-drop", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       70,
			Name:     "nokia-sr-acct-i-low-octets-drop_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-low-octets-drop-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-low-octets-drop", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       71,
			Name:     "nokia-sr-acct-i-high-pack-drop_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-high-pack-drop-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-high-pack-drop", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       72,
			Name:     "nokia-sr-acct-i-low-pack-drop_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-low-pack-drop-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-low-pack-drop", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       73,
			Name:     "nokia-sr-acct-i-high-octets-offer_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-high-octets-offer-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-high-octets-offer", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       74,
			Name:     "nokia-sr-acct-i-low-octets-offer_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-low-octets-offer-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-higlow-octets-offer", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       75,
			Name:     "nokia-sr-acct-i-high-pack-offer_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-high-packs-offer-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-high-packs-offer", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       76,
			Name:     "nokia-sr-acct-i-low-pack-offer_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-low-pack-offer-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-low-pack-offer", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       77,
			Name:     "nokia-sr-acct-i-unc-octets-offer_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-unc-octets-offer-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-unc-octets-offer", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       78,
			Name:     "nokia-sr-acct-i-unc-pack-offer_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-unc-pack-offer-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-unc-pack-offer", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       79,
			Name:     "nokia-sr-acct-i-all-octets-offer_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-all-octets-offer-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-all-octets-offer", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       80,
			Name:     "nokia-sr-acct-i-all-pack-offer_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-all-pack-offer-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-i-all-pack-offer", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       81,
			Name:     "nokia-sr-acct-o-inprof-pack-drop_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-inprof-pack-drop-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-o-inprof-pack-drop", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       82,
			Name:     "nokia-sr-acct-o-outprof-pack-drop_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-outprof-pack-drop-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-o-outprof-pack-drop", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       83,
			Name:     "nokia-sr-acct-o-inprof-octs-drop_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-inprof-octs-drop-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-o-inprof-octs-drop", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       84,
			Name:     "nokia-sr-acct-o-outprof-octs-drop_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-outprof-octs-drop-id", DataType: DataTypeShort},
				{Name: "nokia-sr-acct-o-outprof-octs-drop", DataType: DataTypeInteger64},
			},
		},
		{ID: 85, Name: "nokia-sr-acct-oc-i-all-octs-offer_64", DataType: DataTypeOctets},
		{ID: 86, Name: "nokia-sr-acct-oc-i-all-pack-offer_64", DataType: DataTypeOctets},
		{ID: 87, Name: "nokia-sr-acct-oc-i-inpr-octs-drop_64", DataType: DataTypeOctets},
		{ID: 88, Name: "nokia-sr-acct-oc-i-outpr-octs-drop_64", DataType: DataTypeOctets},
		{ID: 89, Name: "nokia-sr-acct-oc-i-inpr-pack-drop_64", DataType: DataTypeOctets},
		{ID: 90, Name: "nokia-sr-acct-oc-i-outpr-pack-drop_64", DataType: DataTypeOctets},
		{ID: 91, Name: "nokia-sr-acct-oc-o-inpr-pack-drop_64", DataType: DataTypeOctets},
		{ID: 92, Name: "nokia-sr-acct-oc-o-outpr-pack-drop_64", DataType: DataTypeOctets},
		{ID: 93, Name: "nokia-sr-acct-oc-o-inpr-octs-drop_64", DataType: DataTypeOctets},
		{ID: 94, Name: "nokia-sr-acct-oc-o-outpr-octs-drop_64", DataType: DataTypeOctets},
		{ID: 95, Name: "nokia-sr-credit-control-categorymap", DataType: DataTypeString},
		{ID: 96, Name: "nokia-sr-credit-control-quota", DataType: DataTypeString},
		{
			ID:       97,
			Name:     "nokia-sr-tunnel-challenge",
			DataType: DataTypeInteger,
			HasTag:   true,
			Values: map[string]uint32{
				"never":  1,
				"always": 2,
			},
		},
		{ID: 98, Name: "nokia-sr-force-nak", DataType: DataTypeString},
		{ID: 99, Name: "nokia-sr-ipv6-address", DataType: DataTypeIPv6Addr},
		{ID: 100, Name: "nokia-sr-serv-id", DataType: DataTypeInteger},
		{ID: 101, Name: "nokia-sr-interface", DataType: DataTypeString},
		{ID: 102, Name: "nokia-sr-toserver-dhcp-options", DataType: DataTypeOctets},
		{ID: 103, Name: "nokia-sr-toclient-dhcp-options", DataType: DataTypeOctets},
		{ID: 104, Name: "nokia-sr-tunnel-serv-id", DataType: DataTypeInteger},
		{ID: 105, Name: "nokia-sr-ipv6-primary-dns", DataType: DataTypeIPv6Addr},
		{ID: 106, Name: "nokia-sr-ipv6-secondary-dns", DataType: DataTypeIPv6Addr},
		{ID: 107, Name: "nokia-sr-acct-i-statmode", DataType: DataTypeString},
		{
			ID:       108,
			Name:     "nokia-sr-acct-i-hiprio-octets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-hiprio-octets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-hiprio-octets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-hiprio-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       109,
			Name:     "nokia-sr-acct-i-lowprio-octets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-lowprio-octets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-lowprio-octets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-lowprio-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       110,
			Name:     "nokia-sr-acct-o-hiprio-octets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-hiprio-octets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-hiprio-octets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-hiprio-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       111,
			Name:     "nokia-sr-acct-o-lowprio-octets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-lowprio-octets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-lowprio-octets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-lowprio-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       112,
			Name:     "nokia-sr-acct-i-hiprio-packets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-hiprio-packets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-hiprio-packets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-hiprio-packets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       113,
			Name:     "nokia-sr-acct-i-lowprio-packets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-lowprio-packets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-lowprio-packets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-lowprio-packets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       114,
			Name:     "nokia-sr-acct-o-hiprio-packets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-hiprio-packets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-hiprio-packets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-hiprio-packets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       115,
			Name:     "nokia-sr-acct-o-lowprio-packets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-lowprio-packets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-lowprio-packets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-lowprio-packets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       116,
			Name:     "nokia-sr-acct-i-all-octets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-all-octets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-all-octets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-all-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       117,
			Name:     "nokia-sr-acct-o-all-octets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-all-octets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-all-octets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-all-octets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       118,
			Name:     "nokia-sr-acct-i-all-packets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-i-all-packets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-all-packets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-i-all-packets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       119,
			Name:     "nokia-sr-acct-o-all-packets_64",
			DataType: DataTypeStruct,
			Children: []*AttributeDefinition{
				{Name: "nokia-sr-acct-o-all-packets-x80", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-all-packets-id", DataType: DataTypeByte},
				{Name: "nokia-sr-acct-o-all-packets", DataType: DataTypeInteger64},
			},
		},
		{
			ID:       120,
			Name:     "nokia-sr-tunnel-rx-window-size",
			DataType: DataTypeInteger,
			HasTag:   true,
		},
		{ID: 121, Name: "nokia-sr-nat-port-range", DataType: DataTypeString},
		{
			ID:         122,
			Name:       "nokia-sr-li-action",
			DataType:   DataTypeInteger,
			Encryption: EncryptionTunnelPassword,
			Values: map[string]uint32{
				"no-action": 1,
				"enable":    2,
				"disable":   3,
			},
		},
		{
			ID:         123,
			Name:       "nokia-sr-li-destination",
			DataType:   DataTypeString,
			Encryption: EncryptionTunnelPassword,
		},
		{
			ID:         124,
			Name:       "nokia-sr-li-fc",
			DataType:   DataTypeInteger,
			Encryption: EncryptionTunnelPassword,
			Values: map[string]uint32{
				"be": 0,
				"l2": 1,
				"af": 2,
				"l1": 3,
				"h2": 4,
				"ef": 5,
				"h1": 6,
				"nc": 7,
			},
		},
		{
			ID:         125,
			Name:       "nokia-sr-li-direction",
			DataType:   DataTypeInteger,
			Encryption: EncryptionTunnelPassword,
			Values: map[string]uint32{
				"ingress": 1,
				"egress":  2,
			},
		},
		{ID: 126, Name: "nokia-sr-subscriber-qos-override", DataType: DataTypeString},
		{ID: 127, Name: "nokia-sr-acct-o-statmode", DataType: DataTypeString},
		{ID: 128, Name: "nokia-sr-atm-ingress-td-profile", DataType: DataTypeInteger},
		{ID: 129, Name: "nokia-sr-atm-egress-td-profile", DataType: DataTypeInteger},
		{
			ID:       130,
			Name:     "nokia-sr-aa-transit-ip",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"host":        1,
				"audit-start": 2,
				"audit-end":   3,
			},
		},
		{ID: 131, Name: "nokia-sr-delegated-ipv6-pool", DataType: DataTypeString},
		{ID: 132, Name: "nokia-sr-access-loop-rate-down", DataType: DataTypeInteger},
		{ID: 133, Name: "nokia-sr-access-loop-encap-offset", DataType: DataTypeOctets},
		{ID: 134, Name: "nokia-sr-subscriber-filter", DataType: DataTypeString},
		{ID: 135, Name: "nokia-sr-ppp-force-ipv6cp", DataType: DataTypeInteger},
		{ID: 136, Name: "nokia-sr-onetime-http-redirection-filter-id", DataType: DataTypeString},
		{ID: 137, Name: "nokia-sr-authentication-policy-name", DataType: DataTypeString},
		{
			ID:         138,
			Name:       "nokia-sr-li-intercept-id",
			DataType:   DataTypeInteger,
			Encryption: EncryptionTunnelPassword,
		},
		{
			ID:         139,
			Name:       "nokia-sr-li-session-id",
			DataType:   DataTypeInteger,
			Encryption: EncryptionTunnelPassword,
		},
		{ID: 140, Name: "nokia-sr-nat-outside-serv-id", DataType: DataTypeInteger},
		{ID: 141, Name: "nokia-sr-nat-outside-ip-addr", DataType: DataTypeIPAddr},
		{
			ID:         142,
			Name:       "nokia-sr-apn-password",
			DataType:   DataTypeString,
			Encryption: EncryptionTunnelPassword,
		},
		{ID: 143, Name: "nokia-sr-apn-name", DataType: DataTypeString},
		{
			ID:       144,
			Name:     "nokia-sr-tunnel-acct-policy",
			DataType: DataTypeString,
			HasTag:   true,
		},
		{
			ID:       145,
			Name:     "nokia-sr-mgw-interface-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"gn":  1,
				"s2a": 2,
				"s2b": 3,
			},
		},
		{ID: 146, Name: "nokia-sr-wlan-apn-name", DataType: DataTypeString},
		{ID: 147, Name: "nokia-sr-msisdn", DataType: DataTypeString},
		{ID: 148, Name: "nokia-sr-rssi", DataType: DataTypeInteger},
		{ID: 149, Name: "nokia-sr-num-attached-ues", DataType: DataTypeInteger},
		{ID: 150, Name: "nokia-sr-charging-prof-id", DataType: DataTypeInteger},
		{ID: 156, Name: "nokia-sr-aa-group-partition-isa-id", DataType: DataTypeString},
		{ID: 157, Name: "nokia-sr-aa-peer-identifier", DataType: DataTypeString},
		{ID: 158, Name: "nokia-sr-nas-filter-rule-shared", DataType: DataTypeString},
		{ID: 159, Name: "nokia-sr-ascend-data-filter-host-spec", DataType: DataTypeString},
		{ID: 160, Name: "nokia-sr-relative-session-timeout", DataType: DataTypeInteger},
		{
			ID:       163,
			Name:     "nokia-sr-acct-triggered-reason",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"regular":                    1,
				"sla-start":                  2,
				"sla-stop":                   3,
				"framed-ip-address-up":       4,
				"framed-ip-address-down":     5,
				"ipv6-address-up":            6,
				"ipv6-address-down":          7,
				"delegated-ipv6-prefix-up":   8,
				"delegated-ipv6-prefix-down": 9,
				"framed-ipv6-prefix-up":      10,
				"framed-ipv6-prefix-down":    11,
			},
		},
		{ID: 172, Name: "nokia-sr-wlan-portal-redirect", DataType: DataTypeString},
		{ID: 173, Name: "nokia-sr-wlan-portal-url", DataType: DataTypeString},
		{ID: 174, Name: "nokia-sr-lease-time", DataType: DataTypeInteger},
		{ID: 175, Name: "nokia-sr-dsl-line-state", DataType: DataTypeInteger},
		{ID: 176, Name: "nokia-sr-dsl-type", DataType: DataTypeInteger},
		{ID: 177, Name: "nokia-sr-portal-url", DataType: DataTypeString},
		{ID: 178, Name: "nokia-sr-ipv6-portal-url", DataType: DataTypeString},
		{ID: 180, Name: "nokia-sr-sap-session-index", DataType: DataTypeInteger},
		{ID: 181, Name: "nokia-sr-slaac-ipv6-pool", DataType: DataTypeString},
		{ID: 183, Name: "nokia-sr-wpp-errorcode", DataType: DataTypeInteger},
		{ID: 185, Name: "nokia-sr-onetime-http-redirect-reactivate", DataType: DataTypeString},
		{ID: 191, Name: "nokia-sr-toserver-dhcp6-options", DataType: DataTypeOctets},
		{ID: 192, Name: "nokia-sr-toclient-dhcp6-options", DataType: DataTypeOctets},
		{ID: 193, Name: "nokia-sr-aa-app-service-options", DataType: DataTypeString},
		{ID: 194, Name: "nokia-sr-ipv6-acct-input-packets", DataType: DataTypeInteger},
		{ID: 195, Name: "nokia-sr-ipv6-acct-input-octets", DataType: DataTypeInteger},
		{ID: 196, Name: "nokia-sr-ipv6-acct-input-gigawords", DataType: DataTypeInteger},
		{ID: 197, Name: "nokia-sr-ipv6-acct-output-packets", DataType: DataTypeInteger},
		{ID: 198, Name: "nokia-sr-ipv6-acct-output-octets", DataType: DataTypeInteger},
		{ID: 199, Name: "nokia-sr-ipv6-acct-output-gigawords", DataType: DataTypeInteger},
		{ID: 200, Name: "nokia-sr-v6-preferred-lifetime", DataType: DataTypeTimeDelta},
		{ID: 201, Name: "nokia-sr-v6-valid-lifetime", DataType: DataTypeTimeDelta},
		{ID: 202, Name: "nokia-sr-dhcp6-renew-time", DataType: DataTypeTimeDelta},
		{ID: 203, Name: "nokia-sr-dhcp6-rebind-time", DataType: DataTypeTimeDelta},
		{ID: 206, Name: "nokia-sr-wlan-ssid-vlan", DataType: DataTypeString},
		{ID: 217, Name: "nokia-sr-upnp-sub-override-policy", DataType: DataTypeString},
		{ID: 226, Name: "nokia-sr-error-code", DataType: DataTypeInteger},
		{ID: 227, Name: "nokia-sr-error-message", DataType: DataTypeString},
		{ID: 228, Name: "nokia-sr-trigger-acct-interim", DataType: DataTypeString},
		{
			ID:       232,
			Name:     "nokia-sr-acct-interim-level",
			DataType: DataTypeInteger,
			HasTag:   true,
		},
		{ID: 234, Name: "nokia-sr-dnat-override", DataType: DataTypeString},
		{ID: 238, Name: "nokia-sr-remove-override", DataType: DataTypeString},
		{ID: 242, Name: "nokia-sr-radius-py", DataType: DataTypeOctets},
		{ID: 244, Name: "nokia-sr-force-dhcp-relay", DataType: DataTypeString},
	},
}
