package goradius

// EricssonVendorDefinition defines the Ericsson vendor (ID 193). Ported from
// FreeRADIUS dictionary.ericsson. This is the Ericsson IP telephony / session
// control attribute set (SiteKeeper, call routing, charging). It is distinct
// from Ericsson-AB (2352, the Redback/SmartEdge BNG set) and
// Ericsson-Packet-Core-Networks (10923).
//
// The dictionary carries no per-packet placement information, so all
// attributes stay unrestricted.
var EricssonVendorDefinition = &VendorDefinition{
	ID:   193,
	Name: "ericsson",
	Attributes: []*AttributeDefinition{
		{ID: 3, Name: "ericsson-balance", DataType: DataTypeInteger},
		{ID: 4, Name: "ericsson-codec", DataType: DataTypeInteger},
		{ID: 5, Name: "ericsson-currency", DataType: DataTypeString},
		{ID: 6, Name: "ericsson-currency-quote", DataType: DataTypeString},
		{ID: 8, Name: "ericsson-endpoint-type", DataType: DataTypeInteger},
		{ID: 9, Name: "ericsson-sequence-number", DataType: DataTypeInteger},
		{ID: 11, Name: "ericsson-access-agent-ip-address", DataType: DataTypeIPAddr},
		{ID: 12, Name: "ericsson-qos-class", DataType: DataTypeInteger},
		{ID: 14, Name: "ericsson-digest-response", DataType: DataTypeString},
		{ID: 15, Name: "ericsson-digest-attributes", DataType: DataTypeOctets},
		{ID: 16, Name: "ericsson-business-agreement-name", DataType: DataTypeString},
		{ID: 17, Name: "ericsson-call-role", DataType: DataTypeInteger},
		{ID: 20, Name: "ericsson-remote-sk-ua-ip-address", DataType: DataTypeIPAddr},
		{ID: 23, Name: "ericsson-site", DataType: DataTypeString},
		{ID: 32, Name: "ericsson-ttl-relative", DataType: DataTypeInteger},
		{ID: 33, Name: "ericsson-account-error-reason", DataType: DataTypeInteger},
		{ID: 34, Name: "ericsson-layer-identity", DataType: DataTypeInteger},
		{ID: 35, Name: "ericsson-major-protocol-version", DataType: DataTypeInteger},
		{ID: 36, Name: "ericsson-minor-protocol-version", DataType: DataTypeInteger},
		{ID: 37, Name: "ericsson-authentication-type", DataType: DataTypeInteger},
		{ID: 38, Name: "ericsson-trusted-access", DataType: DataTypeInteger},
		{ID: 39, Name: "ericsson-user-name", DataType: DataTypeString},
		{ID: 40, Name: "ericsson-global-unique-call-id", DataType: DataTypeString},
		{ID: 41, Name: "ericsson-global-unique-service-id", DataType: DataTypeString},
		{ID: 42, Name: "ericsson-interim-interval", DataType: DataTypeInteger},
		{ID: 43, Name: "ericsson-alive-indicator", DataType: DataTypeInteger},
		{ID: 44, Name: "ericsson-ttl-absolute", DataType: DataTypeInteger},
		{ID: 45, Name: "ericsson-ttl-start-event", DataType: DataTypeInteger},
		{ID: 46, Name: "ericsson-sk-ip-address", DataType: DataTypeIPAddr},
		{ID: 47, Name: "ericsson-ua-ip-address", DataType: DataTypeIPAddr},
		{ID: 48, Name: "ericsson-sa-ip-address", DataType: DataTypeIPAddr},
		{ID: 49, Name: "ericsson-calling-e164-number", DataType: DataTypeString},
		{ID: 50, Name: "ericsson-calling-h323id", DataType: DataTypeString},
		{ID: 51, Name: "ericsson-calling-email-address", DataType: DataTypeString},
		{ID: 52, Name: "ericsson-dialled-e164-number", DataType: DataTypeString},
		{ID: 53, Name: "ericsson-dialled-h323id", DataType: DataTypeString},
		{ID: 54, Name: "ericsson-dialled-email-address", DataType: DataTypeString},
		{ID: 55, Name: "ericsson-routed-e164-number", DataType: DataTypeString},
		{ID: 56, Name: "ericsson-routed-h323id", DataType: DataTypeString},
		{ID: 57, Name: "ericsson-routed-email-address", DataType: DataTypeString},
		{ID: 58, Name: "ericsson-sitekeeper-name", DataType: DataTypeString},
		{ID: 59, Name: "ericsson-access-group-name", DataType: DataTypeString},
		{ID: 60, Name: "ericsson-access-agent-name", DataType: DataTypeString},
		{ID: 61, Name: "ericsson-user-agent-group-name", DataType: DataTypeString},
		{ID: 62, Name: "ericsson-user-agent-name", DataType: DataTypeString},
		{ID: 63, Name: "ericsson-routing-tariff", DataType: DataTypeInteger},
		{ID: 64, Name: "ericsson-re-selection-counter", DataType: DataTypeInteger},
		{ID: 65, Name: "ericsson-cpn-digits", DataType: DataTypeString},
		{ID: 66, Name: "ericsson-cpn-ton", DataType: DataTypeInteger},
		{ID: 67, Name: "ericsson-cpn-np", DataType: DataTypeInteger},
		{ID: 68, Name: "ericsson-cpn-pi", DataType: DataTypeInteger},
		{ID: 69, Name: "ericsson-cpn-si", DataType: DataTypeInteger},
		{ID: 70, Name: "ericsson-dialled-num-digits", DataType: DataTypeString},
		{ID: 71, Name: "ericsson-dialled-num-ton", DataType: DataTypeInteger},
		{ID: 72, Name: "ericsson-dialled-num-np", DataType: DataTypeInteger},
		{ID: 73, Name: "ericsson-routing-num-digits", DataType: DataTypeString},
		{ID: 74, Name: "ericsson-routing-num-ton", DataType: DataTypeInteger},
		{ID: 75, Name: "ericsson-routing-num-np", DataType: DataTypeInteger},
		{ID: 76, Name: "ericsson-redirecting-num-digits", DataType: DataTypeString},
		{ID: 77, Name: "ericsson-redirecting-num-ton", DataType: DataTypeInteger},
		{ID: 78, Name: "ericsson-redirecting-num-np", DataType: DataTypeInteger},
		{ID: 79, Name: "ericsson-redirecting-num-pi", DataType: DataTypeInteger},
		{ID: 80, Name: "ericsson-redirecting-num-rfd", DataType: DataTypeInteger},
		{ID: 81, Name: "ericsson-time-stamp-utc", DataType: DataTypeInteger},
		{ID: 82, Name: "ericsson-time-stamp-tz", DataType: DataTypeInteger},
		{ID: 83, Name: "ericsson-time-stamp-dst", DataType: DataTypeInteger},
		{ID: 84, Name: "ericsson-session-routing-duration", DataType: DataTypeInteger},
		{ID: 85, Name: "ericsson-session-ringing-duration", DataType: DataTypeInteger},
		{ID: 86, Name: "ericsson-access-type", DataType: DataTypeInteger},
		{ID: 87, Name: "ericsson-requested-bandwidth", DataType: DataTypeInteger},
		{ID: 88, Name: "ericsson-allowed-bandwidth", DataType: DataTypeInteger},
		{ID: 89, Name: "ericsson-media-channel-count", DataType: DataTypeInteger},
		{ID: 90, Name: "ericsson-voice-media-rec-forward", DataType: DataTypeString},
		{ID: 91, Name: "ericsson-voice-media-rec-backward", DataType: DataTypeString},
		{ID: 92, Name: "ericsson-video-media-rec-forward", DataType: DataTypeString},
		{ID: 93, Name: "ericsson-video-media-rec-backward", DataType: DataTypeString},
		{ID: 94, Name: "ericsson-fax-media-rec-forward", DataType: DataTypeString},
		{ID: 95, Name: "ericsson-fax-media-rec-backward", DataType: DataTypeString},
		{ID: 96, Name: "ericsson-data-media-rec-forward", DataType: DataTypeString},
		{ID: 97, Name: "ericsson-data-media-rec-backward", DataType: DataTypeString},
		{ID: 98, Name: "ericsson-charging-case", DataType: DataTypeInteger},
		{ID: 99, Name: "ericsson-rel-cause-coding-std", DataType: DataTypeInteger},
		{ID: 100, Name: "ericsson-rel-cause-location", DataType: DataTypeInteger},
		{ID: 101, Name: "ericsson-rel-cause-class", DataType: DataTypeInteger},
		{ID: 102, Name: "ericsson-rel-cause-value", DataType: DataTypeInteger},
		{ID: 103, Name: "ericsson-rel-reason", DataType: DataTypeInteger},
		{ID: 104, Name: "ericsson-internal-rel-reason-val", DataType: DataTypeInteger},
		{ID: 105, Name: "ericsson-internal-rel-reason-orig", DataType: DataTypeInteger},
		{ID: 106, Name: "ericsson-service-id", DataType: DataTypeInteger},
		{ID: 107, Name: "ericsson-user-id", DataType: DataTypeString},
		{ID: 108, Name: "ericsson-service-name", DataType: DataTypeString},
		{ID: 109, Name: "ericsson-test-call-indicator", DataType: DataTypeInteger},
		{ID: 110, Name: "ericsson-emergency-call-indicator", DataType: DataTypeInteger},
		{ID: 111, Name: "ericsson-calling-id", DataType: DataTypeString},
		{ID: 112, Name: "ericsson-called-id", DataType: DataTypeString},
		{ID: 113, Name: "ericsson-translated-id", DataType: DataTypeString},
		{ID: 114, Name: "ericsson-calling-user-group-id", DataType: DataTypeString},
		{ID: 115, Name: "ericsson-calling-usr-sub-group-id", DataType: DataTypeString},
		{ID: 116, Name: "ericsson-called-usr-group-id", DataType: DataTypeString},
		{ID: 117, Name: "ericsson-called-usr-sub-group-id", DataType: DataTypeString},
		{ID: 118, Name: "ericsson-terminal-type", DataType: DataTypeString},
		{ID: 119, Name: "ericsson-service-duration", DataType: DataTypeInteger},
		{ID: 120, Name: "ericsson-service-execution-result", DataType: DataTypeInteger},
		{ID: 121, Name: "ericsson-service-exe-rslt-desc", DataType: DataTypeString},
		{ID: 122, Name: "ericsson-service-description", DataType: DataTypeString},
		{ID: 123, Name: "ericsson-service-specific-info", DataType: DataTypeString},
		{ID: 124, Name: "ericsson-proxy-ip-address", DataType: DataTypeIPAddr},
		{ID: 125, Name: "ericsson-auth-datarequest", DataType: DataTypeInteger},
		{ID: 126, Name: "ericsson-ipt-time-stamp", DataType: DataTypeInteger},
		{ID: 127, Name: "ericsson-user-name-info", DataType: DataTypeInteger},
	},
}
