package goradius

// ERXVendorDefinition contains the ERX vendor definition with all its attributes
var ERXVendorDefinition = &VendorDefinition{
	ID:          4874,
	Name:        "erx",
	Description: "Juniper ERX Series",
	Attributes: []*AttributeDefinition{
		{ID: 1, Name: "erx-virtual-router-name", DataType: DataTypeString},
		{ID: 2, Name: "erx-address-pool-name", DataType: DataTypeString},
		{ID: 3, Name: "erx-local-loopback-interface", DataType: DataTypeString},
		{ID: 4, Name: "erx-primary-dns", DataType: DataTypeIPAddr},
		{ID: 5, Name: "erx-secondary-dns", DataType: DataTypeIPAddr},
		{ID: 6, Name: "erx-primary-wins", DataType: DataTypeIPAddr},
		{ID: 7, Name: "erx-secondary-wins", DataType: DataTypeIPAddr},
		{ID: 8, Name: "erx-tunnel-virtual-router", DataType: DataTypeString, HasTag: true},
		{ID: 9, Name: "erx-tunnel-password", DataType: DataTypeString, HasTag: true},
		{ID: 10, Name: "erx-ingress-policy-name", DataType: DataTypeString},
		{ID: 11, Name: "erx-egress-policy-name", DataType: DataTypeString},
		{
			ID:       12,
			Name:     "erx-ingress-statistics",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disable": 0,
				"enable":  1,
			},
		},
		{
			ID:       13,
			Name:     "erx-egress-statistics",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disable": 0,
				"enable":  1,
			},
		},
		{
			ID:       14,
			Name:     "erx-atm-service-category",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"UBR":    1,
				"UBRPCR": 2,
				"nrtVBR": 3,
				"CBR":    4,
			},
		},
		{ID: 15, Name: "erx-atm-pcr", DataType: DataTypeInteger},
		{ID: 16, Name: "erx-atm-scr", DataType: DataTypeInteger},
		{ID: 17, Name: "erx-atm-mbs", DataType: DataTypeInteger},
		{ID: 18, Name: "erx-cli-initial-access-level", DataType: DataTypeString},
		{
			ID:       19,
			Name:     "erx-cli-allow-all-vr-access",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disable": 0,
				"enable":  1,
			},
		},
		{ID: 20, Name: "erx-alternate-cli-access-level", DataType: DataTypeString},
		{ID: 21, Name: "erx-alternate-cli-vrouter-name", DataType: DataTypeString},
		{
			ID:       22,
			Name:     "erx-sa-validate",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disable": 0,
				"enable":  1,
			},
		},
		{
			ID:       23,
			Name:     "erx-igmp-enable",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disable": 0,
				"enable":  1,
			},
		},
		{ID: 24, Name: "erx-pppoe-description", DataType: DataTypeString},
		{ID: 25, Name: "erx-redirect-vr-name", DataType: DataTypeString},
		{ID: 26, Name: "erx-qos-profile-name", DataType: DataTypeString},
		{ID: 27, Name: "erx-pppoe-max-sessions", DataType: DataTypeInteger},
		{ID: 28, Name: "erx-pppoe-url", DataType: DataTypeString},
		{
			ID:       29,
			Name:     "erx-qos-profile-interface-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"IP":          1,
				"ATM":         2,
				"HDLC":        3,
				"ETHERNET":    4,
				"SERVER-PORT": 5,
				"ATM-1483":    6,
				"FRAME-RELAY": 7,
				"MPLS-MINOR":  8,
				"CBF":         9,
				"IP-TUNNEL":   10,
				"VLAN-SUB":    11,
				"PPPOE-SUB":   12,
			},
		},
		{
			ID:       30,
			Name:     "erx-tunnel-nas-port-method",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"None":       0,
				"CISCO-CLID": 1,
			},
		},
		{ID: 31, Name: "erx-service-bundle", DataType: DataTypeString},
		{ID: 32, Name: "erx-tunnel-tos", DataType: DataTypeInteger},
		{ID: 33, Name: "erx-tunnel-maximum-sessions", DataType: DataTypeInteger},
		{ID: 34, Name: "erx-framed-ip-route-tag", DataType: DataTypeString},
		{ID: 35, Name: "erx-dial-out-number", DataType: DataTypeString},
		{ID: 36, Name: "erx-ppp-username", DataType: DataTypeString},
		{ID: 37, Name: "erx-ppp-password", DataType: DataTypeString},
		{
			ID:       38,
			Name:     "erx-ppp-auth-protocol",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"None":     0,
				"PAP":      1,
				"CHAP":     2,
				"PAP-CHAP": 3,
				"CHAP-PAP": 4,
			},
		},
		{ID: 39, Name: "erx-minimum-bps", DataType: DataTypeInteger},
		{ID: 40, Name: "erx-maximum-bps", DataType: DataTypeInteger},
		{
			ID:       41,
			Name:     "erx-bearer-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"None":    0,
				"Analog":  1,
				"Digital": 2,
			},
		},
		{ID: 42, Name: "erx-input-gigapkts", DataType: DataTypeInteger},
		{ID: 43, Name: "erx-output-gigapkts", DataType: DataTypeInteger},
		{ID: 44, Name: "erx-tunnel-interface-id", DataType: DataTypeString},
		{ID: 45, Name: "erx-ipv6-virtual-router", DataType: DataTypeString},
		{ID: 46, Name: "erx-ipv6-local-interface", DataType: DataTypeString},
		{ID: 47, Name: "erx-ipv6-primary-dns", DataType: DataTypeIPv6Addr},
		{ID: 48, Name: "erx-ipv6-secondary-dns", DataType: DataTypeIPv6Addr},
		{ID: 49, Name: "sdx-service-name", DataType: DataTypeString},
		{ID: 50, Name: "sdx-session-volume-quota", DataType: DataTypeString},
		{ID: 51, Name: "sdx-tunnel-disconnect-cause-info", DataType: DataTypeString},
		{ID: 52, Name: "erx-radius-client-address", DataType: DataTypeIPAddr},
		{ID: 53, Name: "erx-service-description", DataType: DataTypeString},
		{ID: 54, Name: "erx-l2tp-recv-window-size", DataType: DataTypeInteger},
		{ID: 55, Name: "erx-dhcp-options", DataType: DataTypeOctets},
		{ID: 56, Name: "erx-dhcp-mac-addr", DataType: DataTypeString},
		{ID: 57, Name: "erx-dhcp-gi-address", DataType: DataTypeIPAddr},
		{ID: 58, Name: "erx-li-action", DataType: DataTypeInteger, Encryption: EncryptionTunnelPassword, Values: map[string]uint32{
			"off":  0,
			"on":   1,
			"noop": 2,
		}},
		{ID: 59, Name: "erx-med-dev-handle", DataType: DataTypeOctets, Encryption: EncryptionTunnelPassword},
		{ID: 60, Name: "erx-med-ip-address", DataType: DataTypeIPAddr, Encryption: EncryptionTunnelPassword},
		{ID: 61, Name: "erx-med-port-number", DataType: DataTypeInteger, Encryption: EncryptionTunnelPassword},
		{ID: 62, Name: "erx-mlppp-bundle-name", DataType: DataTypeString},
		{ID: 63, Name: "erx-interface-desc", DataType: DataTypeString},
		{ID: 64, Name: "erx-tunnel-group", DataType: DataTypeString},
		{ID: 65, Name: "erx-service-activate", DataType: DataTypeString, HasTag: true},
		{ID: 66, Name: "erx-service-deactivate", DataType: DataTypeString},
		{ID: 67, Name: "erx-service-volume", DataType: DataTypeInteger, HasTag: true},
		{ID: 68, Name: "erx-service-timeout", DataType: DataTypeInteger, HasTag: true},
		{
			ID:       69,
			Name:     "erx-service-statistics",
			DataType: DataTypeInteger,
			HasTag:   true,
			Values: map[string]uint32{
				"disabled":    0,
				"time":        1,
				"time-volume": 2,
			},
		},
		{
			ID:       70,
			Name:     "erx-df-bit",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"dont-ignore-df-bit": 0,
				"ignore-df-bit":      1,
			},
		},
		{ID: 71, Name: "erx-igmp-access-name", DataType: DataTypeString},
		{ID: 72, Name: "erx-igmp-access-src-name", DataType: DataTypeString},
		{ID: 73, Name: "erx-igmp-oif-map-name", DataType: DataTypeString},
		{ID: 74, Name: "erx-mld-access-name", DataType: DataTypeString},
		{ID: 75, Name: "erx-mld-access-src-name", DataType: DataTypeString},
		{ID: 76, Name: "erx-mld-oif-map-name", DataType: DataTypeString},
		{
			ID:       77,
			Name:     "erx-mld-version",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"v1": 1,
				"v2": 2,
			},
		},
		{
			ID:       78,
			Name:     "erx-igmp-version",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"v1": 1,
				"v2": 2,
				"v3": 3,
			},
		},
		{ID: 79, Name: "erx-ip-mcast-adm-bw-limit", DataType: DataTypeInteger},
		{ID: 80, Name: "erx-ipv6-mcast-adm-bw-limit", DataType: DataTypeInteger},
		{ID: 82, Name: "erx-qos-parameters", DataType: DataTypeString},
		{ID: 83, Name: "erx-service-session", DataType: DataTypeString},
		{ID: 84, Name: "erx-mobile-ip-algorithm", DataType: DataTypeInteger},
		{ID: 85, Name: "erx-mobile-ip-spi", DataType: DataTypeInteger},
		{ID: 86, Name: "erx-mobile-ip-key", DataType: DataTypeString},
		{ID: 87, Name: "erx-mobile-ip-replay", DataType: DataTypeInteger},
		{ID: 88, Name: "erx-mobile-ip-access-control", DataType: DataTypeString},
		{ID: 89, Name: "erx-mobile-ip-lifetime", DataType: DataTypeInteger},
		{
			ID:       90,
			Name:     "erx-l2tp-resynch-method",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disable":                     0,
				"failover":                    1,
				"silent-failover":             2,
				"failover-with-silent-backup": 3,
			},
		},
		{ID: 91, Name: "erx-tunnel-switch-profile", DataType: DataTypeString},
		{ID: 92, Name: "erx-l2c-up-stream-data", DataType: DataTypeString},
		{ID: 93, Name: "erx-l2c-down-stream-data", DataType: DataTypeString},
		{
			ID:       94,
			Name:     "erx-tunnel-tx-speed-method",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"static-layer2":  1,
				"dynamic-layer2": 2,
				"qos":            3,
				"actual":         4,
			},
		},
		{ID: 95, Name: "erx-igmp-query-interval", DataType: DataTypeInteger},
		{ID: 96, Name: "erx-igmp-max-resp-time", DataType: DataTypeInteger},
		{
			ID:       97,
			Name:     "erx-igmp-immediate-leave",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{ID: 98, Name: "erx-mld-query-interval", DataType: DataTypeInteger},
		{ID: 99, Name: "erx-mld-max-resp-time", DataType: DataTypeInteger},
		{
			ID:       100,
			Name:     "erx-mld-immediate-leave",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       101,
			Name:     "erx-ip-block-multicast",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       102,
			Name:     "erx-igmp-explicit-tracking",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       103,
			Name:     "erx-igmp-no-tracking-v2-grps",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       104,
			Name:     "erx-mld-explicit-tracking",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{
			ID:       105,
			Name:     "erx-mld-no-tracking-v1-grps",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{ID: 106, Name: "erx-ipv6-ingress-policy-name", DataType: DataTypeString},
		{ID: 107, Name: "erx-ipv6-egress-policy-name", DataType: DataTypeString},
		{ID: 108, Name: "erx-cos-shaping-pmt-type", DataType: DataTypeString},
		{ID: 109, Name: "erx-dhcp-guided-relay-server", DataType: DataTypeIPAddr},
		{ID: 110, Name: "erx-acc-loop-cir-id", DataType: DataTypeString},
		{ID: 111, Name: "erx-acc-aggr-cir-id-bin", DataType: DataTypeOctets},
		{ID: 112, Name: "erx-acc-aggr-cir-id-asc", DataType: DataTypeString},
		{ID: 113, Name: "erx-act-data-rate-up", DataType: DataTypeInteger},
		{ID: 114, Name: "erx-act-data-rate-dn", DataType: DataTypeInteger},
		{ID: 115, Name: "erx-min-data-rate-up", DataType: DataTypeInteger},
		{ID: 116, Name: "erx-min-data-rate-dn", DataType: DataTypeInteger},
		{ID: 117, Name: "erx-att-data-rate-up", DataType: DataTypeInteger},
		{ID: 118, Name: "erx-att-data-rate-dn", DataType: DataTypeInteger},
		{ID: 119, Name: "erx-max-data-rate-up", DataType: DataTypeInteger},
		{ID: 120, Name: "erx-max-data-rate-dn", DataType: DataTypeInteger},
		{ID: 121, Name: "erx-min-lp-data-rate-up", DataType: DataTypeInteger},
		{ID: 122, Name: "erx-min-lp-data-rate-dn", DataType: DataTypeInteger},
		{ID: 123, Name: "erx-max-interlv-delay-up", DataType: DataTypeInteger},
		{ID: 124, Name: "erx-act-interlv-delay-up", DataType: DataTypeInteger},
		{ID: 125, Name: "erx-max-interlv-delay-dn", DataType: DataTypeInteger},
		{ID: 126, Name: "erx-act-interlv-delay-dn", DataType: DataTypeInteger},
		{
			ID:       127,
			Name:     "erx-dsl-line-state",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"SHOWTIME": 1,
				"IDLE":     2,
				"SILENT":   3,
			},
		},
		{
			ID:       128,
			Name:     "erx-dsl-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"ADSL1":     1,
				"ADSL2":     2,
				"ADSL2PLUS": 3,
				"VDSL1":     4,
				"VDSL2":     5,
				"SDSL":      6,
				"UNKNOWN":   7,
			},
		},
		{ID: 129, Name: "erx-ipv6-ndra-prefix", DataType: DataTypeIPv6Prefix},
		{ID: 130, Name: "erx-qos-set-name", DataType: DataTypeString},
		{ID: 140, Name: "erx-service-acct-interval", DataType: DataTypeInteger, HasTag: true},
		{ID: 141, Name: "erx-downstream-calc-rate", DataType: DataTypeInteger},
		{ID: 142, Name: "erx-upstream-calc-rate", DataType: DataTypeInteger},
		{ID: 143, Name: "erx-max-clients-per-interface", DataType: DataTypeInteger},
		{
			ID:       144,
			Name:     "erx-ppp-monitor-ingress-only",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{ID: 146, Name: "erx-cos-scheduler-pmt-type", DataType: DataTypeString},
		{ID: 147, Name: "erx-backup-address-pool", DataType: DataTypeString},
		{ID: 150, Name: "erx-icr-partition-id", DataType: DataTypeString},
		{ID: 151, Name: "erx-ipv6-acct-input-octets", DataType: DataTypeInteger},
		{ID: 152, Name: "erx-ipv6-acct-output-octets", DataType: DataTypeInteger},
		{ID: 153, Name: "erx-ipv6-acct-input-packets", DataType: DataTypeInteger},
		{ID: 154, Name: "erx-ipv6-acct-output-packets", DataType: DataTypeInteger},
		{ID: 155, Name: "erx-ipv6-acct-input-gigawords", DataType: DataTypeInteger},
		{ID: 156, Name: "erx-ipv6-acct-output-gigawords", DataType: DataTypeInteger},
		{ID: 157, Name: "erx-ipv6-ndra-pool-name", DataType: DataTypeString},
		{ID: 158, Name: "erx-pppoe-padn", DataType: DataTypeString},
		{ID: 159, Name: "erx-dhcp-option-82", DataType: DataTypeOctets},
		{ID: 160, Name: "erx-vlan-map-id", DataType: DataTypeInteger},
		{ID: 161, Name: "erx-ipv6-delegated-pool-name", DataType: DataTypeString},
		{ID: 162, Name: "erx-tx-connect-speed", DataType: DataTypeInteger},
		{ID: 163, Name: "erx-rx-connect-speed", DataType: DataTypeInteger},
		{
			ID:       173,
			Name:     "erx-service-activate-type",
			DataType: DataTypeInteger,
			HasTag:   true,
			Values: map[string]uint32{
				"dynamic":  1,
				"opscript": 1,
			},
		},
		{ID: 174, Name: "erx-client-profile-name", DataType: DataTypeString},
		{ID: 175, Name: "erx-redirect-gw-address", DataType: DataTypeIPAddr},
		{ID: 176, Name: "erx-apn-name", DataType: DataTypeString},
		{ID: 177, Name: "erx-cos-shaping-rate", DataType: DataTypeString},
		{ID: 178, Name: "erx-action-reason", DataType: DataTypeString},
		{ID: 179, Name: "erx-service-volume-gigawords", DataType: DataTypeInteger, HasTag: true},
		{ID: 180, Name: "erx-update-service", DataType: DataTypeString, HasTag: true},
		{ID: 181, Name: "erx-dhcpv6-guided-relay-server", DataType: DataTypeIPv6Addr},
		{ID: 182, Name: "erx-acc-loop-remote-id", DataType: DataTypeString},
		{ID: 183, Name: "erx-acc-loop-encap", DataType: DataTypeOctets},
		{ID: 184, Name: "erx-inner-vlan-map-id", DataType: DataTypeInteger},
		{ID: 185, Name: "erx-core-facing-interface", DataType: DataTypeString},
		{ID: 189, Name: "erx-dhcp-first-relay-ipv4-address", DataType: DataTypeIPAddr},
		{ID: 190, Name: "erx-dhcp-first-relay-ipv6-address", DataType: DataTypeIPv6Addr},
		{ID: 191, Name: "erx-input-interface-filter", DataType: DataTypeString},
		{ID: 192, Name: "erx-output-interface-filter", DataType: DataTypeString},
		{
			ID:       193,
			Name:     "erx-pim-enable",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{ID: 194, Name: "erx-bulk-coa-transaction-id", DataType: DataTypeInteger},
		{ID: 195, Name: "erx-bulk-coa-identifier", DataType: DataTypeInteger},
		{ID: 196, Name: "erx-ipv4-input-service-set", DataType: DataTypeString},
		{ID: 197, Name: "erx-ipv4-output-service-set", DataType: DataTypeString},
		{ID: 198, Name: "erx-ipv4-input-service-filter", DataType: DataTypeString},
		{ID: 199, Name: "erx-ipv4-output-service-filter", DataType: DataTypeString},
		{ID: 200, Name: "erx-ipv6-input-service-set", DataType: DataTypeString},
		{ID: 201, Name: "erx-ipv6-output-service-set", DataType: DataTypeString},
		{ID: 202, Name: "erx-ipv6-input-service-filter", DataType: DataTypeString},
		{ID: 203, Name: "erx-ipv6-output-service-filter", DataType: DataTypeString},
		{ID: 204, Name: "erx-adv-pcef-profile-name", DataType: DataTypeString},
		{ID: 205, Name: "erx-adv-pcef-rule-name", DataType: DataTypeString},
		{
			ID:       206,
			Name:     "erx-re-authentication-catalyst",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled":     0,
				"client-renew": 1,
			},
		},
		{ID: 207, Name: "erx-dhcpv6-options", DataType: DataTypeOctets},
		{ID: 208, Name: "erx-dhcp-header", DataType: DataTypeOctets},
		{ID: 209, Name: "erx-dhcpv6-header", DataType: DataTypeOctets},
		{
			ID:       210,
			Name:     "erx-acct-request-reason",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"Acct-Start-Ack":            1,
				"Periodic":                  2,
				"IP-Active":                 4,
				"IP-Inactive":               8,
				"IPv6-Active":               16,
				"IPv6-Inactive":             32,
				"Session-Active":            64,
				"Session-Inactive":          128,
				"Line-Speed-Change":         256,
				"Address-Assignment-Change": 512,
				"CoA-Complete":              1024,
			},
		},
		{ID: 211, Name: "erx-inner-tag-protocol-id", DataType: DataTypeString},
		{
			ID:       212,
			Name:     "erx-routing-services",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"disabled": 0,
				"enabled":  1,
			},
		},
		{ID: 213, Name: "erx-interface-set-targeting-weight", DataType: DataTypeInteger},
		{ID: 214, Name: "erx-interface-targeting-weight", DataType: DataTypeInteger},
		{ID: 216, Name: "erx-hybrid-access-dsl-downstream-speed", DataType: DataTypeInteger},
		{ID: 217, Name: "erx-hybrid-access-lte-downstream-speed", DataType: DataTypeInteger},
		{
			ID:       219,
			Name:     "erx-pon-access-type",
			DataType: DataTypeInteger,
			Values: map[string]uint32{
				"Other":    0,
				"GPON":     1,
				"XG-PON1":  2,
				"TWDM-PON": 3,
				"XGS-PON":  4,
				"WDM-PON":  5,
				"UNKNOWN":  7,
			},
		},
		{ID: 220, Name: "erx-ont-onu-average-data-rate-downstream", DataType: DataTypeInteger},
		{ID: 221, Name: "erx-ont-onu-peak-data-rate-downstream", DataType: DataTypeInteger},
		{ID: 222, Name: "erx-ont-onu-maximum-data-rate-upstream", DataType: DataTypeInteger},
		{ID: 223, Name: "erx-ont-onu-assured-data-rate-upstream", DataType: DataTypeInteger},
		{ID: 224, Name: "erx-pon-tree-maximum-data-rate-upstream", DataType: DataTypeInteger},
		{ID: 225, Name: "erx-pon-tree-maximum-data-rate-downstream", DataType: DataTypeInteger},
		{ID: 226, Name: "erx-expected-throughput-upstream", DataType: DataTypeInteger},
		{ID: 227, Name: "erx-expected-throughput-downstream", DataType: DataTypeInteger},
		{ID: 228, Name: "erx-attainable-expected-throughput-upstream", DataType: DataTypeInteger},
		{ID: 229, Name: "erx-attainable-expected-throughput-downstream", DataType: DataTypeInteger},
		{ID: 230, Name: "erx-gamma-data-rate-upstream", DataType: DataTypeInteger},
		{ID: 231, Name: "erx-gamma-data-rate-downstream", DataType: DataTypeInteger},
		{ID: 232, Name: "erx-attainable-gamma-data-rate-upstream", DataType: DataTypeInteger},
		{ID: 233, Name: "erx-attainable-gamma-data-rate-downstream", DataType: DataTypeInteger},
	},
}
