package goradius

// CiscoVendorDefinition defines the Cisco vendor (ID 9) and its attributes.
// Ported from FreeRADIUS dictionary.cisco.
// Reference: https://www.cisco.com/univercd/cc/td/doc/product/access/acs_serv/vapp_dev/vsaig3.htm
// Usage masks are transcribed from the vsaig3 guide tables of gateway-sent VSAs
// (Access-Request and Accounting-Request) and server-sent VSAs (Access-Accept),
// the IOS "RADIUS Vendor-Proprietary Attributes" guide for the 187-255 range, and
// the ISG RADIUS CoA interface guide for 250-253. Attributes without a documented
// packet placement stay unrestricted.
var CiscoVendorDefinition = &VendorDefinition{
	ID:   9,
	Name: "cisco",
	Attributes: []*AttributeDefinition{
		// cisco-avpair is a generic container documented in every packet type,
		// including ISG CoA requests, so it stays unrestricted.
		{ID: 1, Name: "cisco-avpair", DataType: DataTypeString},
		{ID: 2, Name: "cisco-nas-port", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},

		// T.37 Store-and-Forward attributes
		{ID: 3, Name: "cisco-fax-account-id-origin", DataType: DataTypeString},
		{ID: 4, Name: "cisco-fax-msg-id", DataType: DataTypeString},
		{ID: 5, Name: "cisco-fax-pages", DataType: DataTypeString},
		{ID: 6, Name: "cisco-fax-coverpage-flag", DataType: DataTypeString},
		{ID: 7, Name: "cisco-fax-modem-time", DataType: DataTypeString},
		{ID: 8, Name: "cisco-fax-connect-speed", DataType: DataTypeString},
		{ID: 9, Name: "cisco-fax-recipient-count", DataType: DataTypeString},
		{ID: 10, Name: "cisco-fax-process-abort-flag", DataType: DataTypeString},
		{ID: 11, Name: "cisco-fax-dsn-address", DataType: DataTypeString},
		{ID: 12, Name: "cisco-fax-dsn-flag", DataType: DataTypeString},
		{ID: 13, Name: "cisco-fax-mdn-address", DataType: DataTypeString},
		{ID: 14, Name: "cisco-fax-mdn-flag", DataType: DataTypeString},
		{ID: 15, Name: "cisco-fax-auth-status", DataType: DataTypeString},
		{ID: 16, Name: "cisco-email-server-address", DataType: DataTypeString},
		{ID: 17, Name: "cisco-email-server-ack-flag", DataType: DataTypeString},
		{ID: 18, Name: "cisco-gateway-id", DataType: DataTypeString},
		{ID: 19, Name: "cisco-call-type", DataType: DataTypeString},
		{ID: 20, Name: "cisco-port-used", DataType: DataTypeString},
		{ID: 21, Name: "cisco-abort-cause", DataType: DataTypeString},

		// Voice over IP attributes; the vsaig3 guide lists these as gateway-sent
		// (Access-Request, Accounting-Start, and Accounting-Stop records).
		{ID: 23, Name: "cisco-h323-remote-address", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 24, Name: "cisco-h323-conf-id", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 25, Name: "cisco-h323-setup-time", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 26, Name: "cisco-h323-call-origin", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 27, Name: "cisco-h323-call-type", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 28, Name: "cisco-h323-connect-time", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 29, Name: "cisco-h323-disconnect-time", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 30, Name: "cisco-h323-disconnect-cause", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 31, Name: "cisco-h323-voice-quality", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 33, Name: "cisco-h323-gw-id", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 35, Name: "cisco-h323-incoming-conf-id", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},

		{ID: 37, Name: "cisco-policy-up", DataType: DataTypeString},
		{ID: 38, Name: "cisco-policy-down", DataType: DataTypeString},

		{ID: 46, Name: "cisco-relay-information-option", DataType: DataTypeString},
		{ID: 47, Name: "cisco-dhcp-user-class", DataType: DataTypeString},
		{ID: 48, Name: "cisco-dhcp-vendor-class", DataType: DataTypeString},
		{ID: 49, Name: "cisco-dhcp-client-id", DataType: DataTypeOctets},
		{ID: 50, Name: "cisco-dhcp-relay-giaddr", DataType: DataTypeString},
		{ID: 51, Name: "cisco-service-name", DataType: DataTypeString},
		{ID: 52, Name: "cisco-parent-session-id", DataType: DataTypeString},

		{ID: 55, Name: "cisco-sub-qos-pol-in", DataType: DataTypeString},
		{ID: 56, Name: "cisco-sub-qos-pol-out", DataType: DataTypeString},
		{ID: 57, Name: "cisco-in-acl", DataType: DataTypeString},
		{ID: 58, Name: "cisco-out-acl", DataType: DataTypeString},
		{ID: 59, Name: "cisco-sub-pbr-policy-in", DataType: DataTypeString},
		{ID: 60, Name: "cisco-sub-activate-service", DataType: DataTypeString},
		{ID: 61, Name: "cisco-ipv6-in-acl", DataType: DataTypeString},
		{ID: 62, Name: "cisco-ipv6-out-acl", DataType: DataTypeString},
		{ID: 63, Name: "cisco-sub-deactivate-service", DataType: DataTypeString},

		{ID: 65, Name: "cisco-dhcp-subscriber-id", DataType: DataTypeString},
		{ID: 66, Name: "cisco-dhcpv6-link-address", DataType: DataTypeString},

		{ID: 90, Name: "cisco-dhcpv4-option-to-aaa", DataType: DataTypeString},

		{ID: 100, Name: "cisco-sip-conf-id", DataType: DataTypeString},
		// IDs 101-110 are server-sent per the vsaig3 guide, which also forbids
		// voice VSAs in Accounting-Response packets; 105 is listed in both the
		// gateway-sent and the server-sent tables.
		{ID: 101, Name: "cisco-h323-credit-amount", DataType: DataTypeString, Usage: UsageAccessAccept},
		{ID: 102, Name: "cisco-h323-credit-time", DataType: DataTypeString, Usage: UsageAccessAccept},
		{ID: 103, Name: "cisco-h323-return-code", DataType: DataTypeString, Usage: UsageAccessAccept},
		{ID: 104, Name: "cisco-h323-prompt-id", DataType: DataTypeString, Usage: UsageAccessAccept},
		{ID: 105, Name: "cisco-h323-time-and-day", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccessAccept | UsageAccountingRequest},
		{ID: 106, Name: "cisco-h323-redirect-number", DataType: DataTypeString, Usage: UsageAccessAccept},
		{ID: 107, Name: "cisco-h323-preferred-lang", DataType: DataTypeString, Usage: UsageAccessAccept},
		{ID: 108, Name: "cisco-h323-redirect-ip-address", DataType: DataTypeString, Usage: UsageAccessAccept},
		{ID: 109, Name: "cisco-h323-billing-model", DataType: DataTypeString, Usage: UsageAccessAccept},
		{ID: 110, Name: "cisco-h323-currency", DataType: DataTypeString, Usage: UsageAccessAccept},
		{ID: 111, Name: "cisco-subscriber", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		// IDs 112-117 and 141-150 are call detail record fields emitted in
		// accounting start and stop records.
		{ID: 112, Name: "cisco-gw-rxd-cdn", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 113, Name: "cisco-gw-final-xlated-cdn", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 114, Name: "cisco-remote-media-address", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 115, Name: "cisco-release-source", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 116, Name: "cisco-gw-rxd-cgn", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 117, Name: "cisco-gw-final-xlated-cgn", DataType: DataTypeString, Usage: UsageAccountingRequest},

		{ID: 141, Name: "cisco-call-id", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 142, Name: "cisco-session-protocol", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 143, Name: "cisco-method", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 144, Name: "cisco-prev-hop-via", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 145, Name: "cisco-prev-hop-ip", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 146, Name: "cisco-incoming-req-uri", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 147, Name: "cisco-outgoing-req-uri", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 148, Name: "cisco-next-hop-ip", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 149, Name: "cisco-next-hop-dn", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 150, Name: "cisco-sip-hdr", DataType: DataTypeString, Usage: UsageAccountingRequest},
		{ID: 151, Name: "cisco-dsp-id", DataType: DataTypeString},

		// Per the IOS vendor-proprietary attributes guide: multilink-id is sent
		// in authentication-response packets, num-in-multilink additionally in
		// accounting-request packets, and the pre-session counters in
		// accounting-stop records.
		{ID: 187, Name: "cisco-multilink-id", DataType: DataTypeInteger, Usage: UsageAccessAccept},
		{ID: 188, Name: "cisco-num-in-multilink", DataType: DataTypeInteger, Usage: UsageAccessAccept | UsageAccountingRequest},
		{ID: 190, Name: "cisco-pre-input-octets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 191, Name: "cisco-pre-output-octets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 192, Name: "cisco-pre-input-packets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 193, Name: "cisco-pre-output-packets", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 194, Name: "cisco-maximum-time", DataType: DataTypeInteger},
		{
			ID:       195,
			Name:     "cisco-disconnect-cause",
			DataType: DataTypeInteger,
			Usage:    UsageAccountingRequest,
			Values: map[string]uint32{
				"no-reason":                     0,
				"no-disconnect":                 1,
				"unknown":                       2,
				"call-disconnect":               3,
				"clid-authentication-failure":   4,
				"no-modem-available":            9,
				"no-carrier":                    10,
				"lost-carrier":                  11,
				"no-detected-result-codes":      12,
				"user-ends-session":             20,
				"idle-timeout":                  21,
				"exit-telnet-session":           22,
				"no-remote-ip-addr":             23,
				"exit-raw-tcp":                  24,
				"password-fail":                 25,
				"raw-tcp-disabled":              26,
				"control-c-detected":            27,
				"exec-program-destroyed":        28,
				"close-virtual-connection":      29,
				"end-virtual-connection":        30,
				"exit-rlogin":                   31,
				"invalid-rlogin-option":         32,
				"insufficient-resources":        33,
				"timeout-ppp-lcp":               40,
				"failed-ppp-lcp-negotiation":    41,
				"failed-ppp-pap-auth-fail":      42,
				"failed-ppp-chap-auth":          43,
				"failed-ppp-remote-auth":        44,
				"ppp-remote-terminate":          45,
				"ppp-closed-event":              46,
				"ncp-closed-ppp":                47,
				"mp-error-ppp":                  48,
				"ppp-maximum-channels":          49,
				"tables-full":                   50,
				"resources-full":                51,
				"invalid-ip-address":            52,
				"bad-hostname":                  53,
				"bad-port":                      54,
				"reset-tcp":                     60,
				"tcp-connection-refused":        61,
				"timeout-tcp":                   62,
				"foreign-host-close-tcp":        63,
				"tcp-network-unreachable":       64,
				"tcp-host-unreachable":          65,
				"tcp-network-admin-unreachable": 66,
				"tcp-port-unreachable":          67,
				"session-timeout":               100,
				"session-failed-security":       101,
				"session-end-callback":          102,
				"invalid-protocol":              120,
				"radius-disconnect":             150,
				"local-admin-disconnect":        151,
				"snmp-disconnect":               152,
				"v110-retries":                  160,
				"ppp-authentication-timeout":    170,
				"local-hangup":                  180,
				"remote-hangup":                 185,
				"t1-quiesced":                   190,
				"call-duration":                 195,
				"vpn-user-disconnect":           600,
				"vpn-carrier-loss":              601,
				"vpn-no-resources":              602,
				"vpn-bad-control-packet":        603,
				"vpn-admin-disconnect":          604,
				"vpn-tunnel-shut":               605,
				"vpn-local-disconnect":          606,
				"vpn-session-limit":             607,
				"vpn-call-redirect":             608,
			},
		},
		{ID: 197, Name: "cisco-data-rate", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 198, Name: "cisco-presession-time", DataType: DataTypeInteger, Usage: UsageAccountingRequest},
		{ID: 208, Name: "cisco-pw-lifetime", DataType: DataTypeInteger},
		{ID: 209, Name: "cisco-ip-direct", DataType: DataTypeInteger},
		{ID: 210, Name: "cisco-ppp-vj-slot-comp", DataType: DataTypeInteger},
		{ID: 212, Name: "cisco-ppp-async-map", DataType: DataTypeInteger},
		{ID: 217, Name: "cisco-ip-pool-definition", DataType: DataTypeString},
		{ID: 218, Name: "cisco-assign-ip-pool", DataType: DataTypeInteger},
		{ID: 228, Name: "cisco-route-ip", DataType: DataTypeInteger},
		{ID: 233, Name: "cisco-link-compression", DataType: DataTypeInteger},
		{ID: 234, Name: "cisco-target-util", DataType: DataTypeInteger},
		{ID: 235, Name: "cisco-maximum-channels", DataType: DataTypeInteger},
		{ID: 242, Name: "cisco-data-filter", DataType: DataTypeInteger},
		{ID: 243, Name: "cisco-call-filter", DataType: DataTypeInteger},
		{ID: 244, Name: "cisco-idle-limit", DataType: DataTypeInteger},
		{ID: 249, Name: "cisco-subscriber-password", DataType: DataTypeString},
		// IDs 250-253 are ISG subscriber service attributes; placements follow
		// the ISG RADIUS CoA interface guide.
		{ID: 250, Name: "cisco-account-info", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccessAccept | UsageAccountingRequest | UsageCoARequest},
		{ID: 251, Name: "cisco-service-info", DataType: DataTypeString, Usage: UsageAccessAccept | UsageAccountingRequest},
		{ID: 252, Name: "cisco-command-code", DataType: DataTypeString, Usage: UsageCoARequest},
		{ID: 253, Name: "cisco-control-info", DataType: DataTypeString, Usage: UsageAccessRequest | UsageAccountingRequest},
		{ID: 255, Name: "cisco-xmit-rate", DataType: DataTypeInteger},
	},
}
